// Code generated by protoc-gen-pgx-orm. DO NOT EDIT.
package orm

import (
	"time"

	"github.com/jackc/pgtype"
	"github.com/stroppy-io/stroppy-cloud-panel/internal/proto/panel"
	"github.com/stroppy-io/stroppy/pkg/common/proto/stroppy"
	"google.golang.org/protobuf/types/known/anypb"
)

var (
	User          = newUserTableImpl()
	RefreshTokens = newRefreshTokensTableImpl()
	Kvinfo        = newKvinfoTableImpl()
	Template      = newTemplateTableImpl()
	RunRecord     = newRunRecordTableImpl()
	RunRecordStep = newRunRecordStepTableImpl()
	Workflow      = newWorkflowTableImpl()
	WorkflowTask  = newWorkflowTaskTableImpl()
	WorkflowEdge  = newWorkflowEdgeTableImpl()
)

type (
	UserField interface {
		fieldAlias
		mustUserField()
	}
	RefreshTokensField interface {
		fieldAlias
		mustRefreshTokensField()
	}
	KvinfoField interface {
		fieldAlias
		mustKvinfoField()
	}
	TemplateField interface {
		fieldAlias
		mustTemplateField()
	}
	RunRecordField interface {
		fieldAlias
		mustRunRecordField()
	}
	RunRecordStepField interface {
		fieldAlias
		mustRunRecordStepField()
	}
	WorkflowField interface {
		fieldAlias
		mustWorkflowField()
	}
	WorkflowTaskField interface {
		fieldAlias
		mustWorkflowTaskField()
	}
	WorkflowEdgeField interface {
		fieldAlias
		mustWorkflowEdgeField()
	}
)
type (
	useridFieldImpl           struct{ *column[string, UserField] }
	usercreatedAtFieldImpl    struct{ *column[time.Time, UserField] }
	userupdatedAtFieldImpl    struct{ *column[time.Time, UserField] }
	userdeletedAtFieldImpl    struct{ *column[*time.Time, UserField] }
	useremailFieldImpl        struct{ *column[string, UserField] }
	useradminFieldImpl        struct{ *column[bool, UserField] }
	userpasswordHashFieldImpl struct{ *column[string, UserField] }
)

func (f *useridFieldImpl) mustUserField()           {}
func (f *usercreatedAtFieldImpl) mustUserField()    {}
func (f *userupdatedAtFieldImpl) mustUserField()    {}
func (f *userdeletedAtFieldImpl) mustUserField()    {}
func (f *useremailFieldImpl) mustUserField()        {}
func (f *useradminFieldImpl) mustUserField()        {}
func (f *userpasswordHashFieldImpl) mustUserField() {}
func (f fieldAliasImpl) mustUserField()             {}

type (
	refreshTokensuserIdFieldImpl struct {
		*column[string, RefreshTokensField]
	}
	refreshTokenstokenFieldImpl struct {
		*column[string, RefreshTokensField]
	}
)

func (f *refreshTokensuserIdFieldImpl) mustRefreshTokensField() {}
func (f *refreshTokenstokenFieldImpl) mustRefreshTokensField()  {}
func (f fieldAliasImpl) mustRefreshTokensField()                {}

type (
	kvinfoidFieldImpl        struct{ *column[string, KvinfoField] }
	kvinfocreatedAtFieldImpl struct {
		*column[time.Time, KvinfoField]
	}
	kvinfoupdatedAtFieldImpl struct {
		*column[time.Time, KvinfoField]
	}
	kvinfodeletedAtFieldImpl struct {
		*column[*time.Time, KvinfoField]
	}
	kvinfokeyFieldImpl             struct{ *column[string, KvinfoField] }
	kvinfodescriptionFieldImpl     struct{ *column[string, KvinfoField] }
	kvinfodefaultValueFieldImpl    struct{ *column[*string, KvinfoField] }
	kvinfoisRequiredFieldImpl      struct{ *column[bool, KvinfoField] }
	kvinfoimmutableFieldImpl       struct{ *column[bool, KvinfoField] }
	kvinfosystemGeneratedFieldImpl struct{ *column[bool, KvinfoField] }
)

func (f *kvinfoidFieldImpl) mustKvinfoField()              {}
func (f *kvinfocreatedAtFieldImpl) mustKvinfoField()       {}
func (f *kvinfoupdatedAtFieldImpl) mustKvinfoField()       {}
func (f *kvinfodeletedAtFieldImpl) mustKvinfoField()       {}
func (f *kvinfokeyFieldImpl) mustKvinfoField()             {}
func (f *kvinfodescriptionFieldImpl) mustKvinfoField()     {}
func (f *kvinfodefaultValueFieldImpl) mustKvinfoField()    {}
func (f *kvinfoisRequiredFieldImpl) mustKvinfoField()      {}
func (f *kvinfoimmutableFieldImpl) mustKvinfoField()       {}
func (f *kvinfosystemGeneratedFieldImpl) mustKvinfoField() {}
func (f fieldAliasImpl) mustKvinfoField()                  {}

type (
	templateidFieldImpl        struct{ *column[string, TemplateField] }
	templatecreatedAtFieldImpl struct {
		*column[time.Time, TemplateField]
	}
	templateupdatedAtFieldImpl struct {
		*column[time.Time, TemplateField]
	}
	templatedeletedAtFieldImpl struct {
		*column[*time.Time, TemplateField]
	}
	templatenameFieldImpl      struct{ *column[string, TemplateField] }
	templateauthorIdFieldImpl  struct{ *column[string, TemplateField] }
	templateisDefaultFieldImpl struct{ *column[bool, TemplateField] }
	templatetagsFieldImpl      struct {
		*column[[]string, TemplateField]
	}
)

func (f *templateidFieldImpl) mustTemplateField()        {}
func (f *templatecreatedAtFieldImpl) mustTemplateField() {}
func (f *templateupdatedAtFieldImpl) mustTemplateField() {}
func (f *templatedeletedAtFieldImpl) mustTemplateField() {}
func (f *templatenameFieldImpl) mustTemplateField()      {}
func (f *templateauthorIdFieldImpl) mustTemplateField()  {}
func (f *templateisDefaultFieldImpl) mustTemplateField() {}
func (f *templatetagsFieldImpl) mustTemplateField()      {}
func (f fieldAliasImpl) mustTemplateField()              {}

type (
	runRecordidFieldImpl struct {
		*column[string, RunRecordField]
	}
	runRecordauthorIdFieldImpl struct {
		*column[string, RunRecordField]
	}
	runRecordcreatedAtFieldImpl struct {
		*column[time.Time, RunRecordField]
	}
	runRecordupdatedAtFieldImpl struct {
		*column[time.Time, RunRecordField]
	}
	runRecorddeletedAtFieldImpl struct {
		*column[*time.Time, RunRecordField]
	}
	runRecordstatusFieldImpl  struct{ *column[int32, RunRecordField] }
	runRecordrunInfoFieldImpl struct {
		*column[[]byte, RunRecordField]
	}
	runRecordtpsFieldImpl struct {
		*column[[]byte, RunRecordField]
	}
	runRecordgrafanaDashboardUrlFieldImpl struct {
		*column[string, RunRecordField]
	}
	runRecordworkflowIdFieldImpl struct {
		*column[*string, RunRecordField]
	}
	runRecordcloudRunParamsFieldImpl struct {
		*column[pgtype.JSONB, RunRecordField]
	}
)

func (f *runRecordidFieldImpl) mustRunRecordField()                  {}
func (f *runRecordauthorIdFieldImpl) mustRunRecordField()            {}
func (f *runRecordcreatedAtFieldImpl) mustRunRecordField()           {}
func (f *runRecordupdatedAtFieldImpl) mustRunRecordField()           {}
func (f *runRecorddeletedAtFieldImpl) mustRunRecordField()           {}
func (f *runRecordstatusFieldImpl) mustRunRecordField()              {}
func (f *runRecordrunInfoFieldImpl) mustRunRecordField()             {}
func (f *runRecordtpsFieldImpl) mustRunRecordField()                 {}
func (f *runRecordgrafanaDashboardUrlFieldImpl) mustRunRecordField() {}
func (f *runRecordworkflowIdFieldImpl) mustRunRecordField()          {}
func (f *runRecordcloudRunParamsFieldImpl) mustRunRecordField()      {}
func (f fieldAliasImpl) mustRunRecordField()                         {}

type (
	runRecordStepidFieldImpl struct {
		*column[string, RunRecordStepField]
	}
	runRecordStepcreatedAtFieldImpl struct {
		*column[time.Time, RunRecordStepField]
	}
	runRecordStepupdatedAtFieldImpl struct {
		*column[time.Time, RunRecordStepField]
	}
	runRecordStepdeletedAtFieldImpl struct {
		*column[*time.Time, RunRecordStepField]
	}
	runRecordSteprunIdFieldImpl struct {
		*column[string, RunRecordStepField]
	}
	runRecordStepstatusFieldImpl struct {
		*column[int32, RunRecordStepField]
	}
	runRecordStepstepInfoFieldImpl struct {
		*column[[]byte, RunRecordStepField]
	}
)

func (f *runRecordStepidFieldImpl) mustRunRecordStepField()        {}
func (f *runRecordStepcreatedAtFieldImpl) mustRunRecordStepField() {}
func (f *runRecordStepupdatedAtFieldImpl) mustRunRecordStepField() {}
func (f *runRecordStepdeletedAtFieldImpl) mustRunRecordStepField() {}
func (f *runRecordSteprunIdFieldImpl) mustRunRecordStepField()     {}
func (f *runRecordStepstatusFieldImpl) mustRunRecordStepField()    {}
func (f *runRecordStepstepInfoFieldImpl) mustRunRecordStepField()  {}
func (f fieldAliasImpl) mustRunRecordStepField()                   {}

type (
	workflowidFieldImpl        struct{ *column[string, WorkflowField] }
	workflowcreatedAtFieldImpl struct {
		*column[time.Time, WorkflowField]
	}
	workflowupdatedAtFieldImpl struct {
		*column[time.Time, WorkflowField]
	}
	workflowdeletedAtFieldImpl struct {
		*column[*time.Time, WorkflowField]
	}
)

func (f *workflowidFieldImpl) mustWorkflowField()        {}
func (f *workflowcreatedAtFieldImpl) mustWorkflowField() {}
func (f *workflowupdatedAtFieldImpl) mustWorkflowField() {}
func (f *workflowdeletedAtFieldImpl) mustWorkflowField() {}
func (f fieldAliasImpl) mustWorkflowField()              {}

type (
	workflowTaskidFieldImpl struct {
		*column[string, WorkflowTaskField]
	}
	workflowTaskcreatedAtFieldImpl struct {
		*column[time.Time, WorkflowTaskField]
	}
	workflowTaskupdatedAtFieldImpl struct {
		*column[time.Time, WorkflowTaskField]
	}
	workflowTaskdeletedAtFieldImpl struct {
		*column[*time.Time, WorkflowTaskField]
	}
	workflowTasktaskTypeFieldImpl struct {
		*column[int32, WorkflowTaskField]
	}
	workflowTaskstatusFieldImpl struct {
		*column[int32, WorkflowTaskField]
	}
	workflowTaskworkflowIdFieldImpl struct {
		*column[string, WorkflowTaskField]
	}
	workflowTaskcleanedUpFieldImpl struct {
		*column[bool, WorkflowTaskField]
	}
	workflowTaskonWorkerFieldImpl struct {
		*column[string, WorkflowTaskField]
	}
	workflowTaskretryStateFieldImpl struct {
		*column[[]byte, WorkflowTaskField]
	}
	workflowTasklogsFieldImpl struct {
		*column[[][]byte, WorkflowTaskField]
	}
	workflowTaskretrySettingsFieldImpl struct {
		*column[[]byte, WorkflowTaskField]
	}
	workflowTaskinputFieldImpl struct {
		*column[[]byte, WorkflowTaskField]
	}
	workflowTaskoutputFieldImpl struct {
		*column[[]byte, WorkflowTaskField]
	}
	workflowTaskmetadataFieldImpl struct {
		*column[[]byte, WorkflowTaskField]
	}
)

func (f *workflowTaskidFieldImpl) mustWorkflowTaskField()            {}
func (f *workflowTaskcreatedAtFieldImpl) mustWorkflowTaskField()     {}
func (f *workflowTaskupdatedAtFieldImpl) mustWorkflowTaskField()     {}
func (f *workflowTaskdeletedAtFieldImpl) mustWorkflowTaskField()     {}
func (f *workflowTasktaskTypeFieldImpl) mustWorkflowTaskField()      {}
func (f *workflowTaskstatusFieldImpl) mustWorkflowTaskField()        {}
func (f *workflowTaskworkflowIdFieldImpl) mustWorkflowTaskField()    {}
func (f *workflowTaskcleanedUpFieldImpl) mustWorkflowTaskField()     {}
func (f *workflowTaskonWorkerFieldImpl) mustWorkflowTaskField()      {}
func (f *workflowTaskretryStateFieldImpl) mustWorkflowTaskField()    {}
func (f *workflowTasklogsFieldImpl) mustWorkflowTaskField()          {}
func (f *workflowTaskretrySettingsFieldImpl) mustWorkflowTaskField() {}
func (f *workflowTaskinputFieldImpl) mustWorkflowTaskField()         {}
func (f *workflowTaskoutputFieldImpl) mustWorkflowTaskField()        {}
func (f *workflowTaskmetadataFieldImpl) mustWorkflowTaskField()      {}
func (f fieldAliasImpl) mustWorkflowTaskField()                      {}

type (
	workflowEdgefromIdFieldImpl struct {
		*column[string, WorkflowEdgeField]
	}
	workflowEdgetoIdFieldImpl struct {
		*column[string, WorkflowEdgeField]
	}
	workflowEdgeworkflowIdFieldImpl struct {
		*column[string, WorkflowEdgeField]
	}
)

func (f *workflowEdgefromIdFieldImpl) mustWorkflowEdgeField()     {}
func (f *workflowEdgetoIdFieldImpl) mustWorkflowEdgeField()       {}
func (f *workflowEdgeworkflowIdFieldImpl) mustWorkflowEdgeField() {}
func (f fieldAliasImpl) mustWorkflowEdgeField()                   {}

type (
	UserScanner struct {
		Id           string
		CreatedAt    time.Time
		UpdatedAt    time.Time
		DeletedAt    *time.Time
		Email        string
		Admin        bool
		PasswordHash string
	}
	RefreshTokensScanner struct {
		UserId string
		Token  string
	}
	KvinfoScanner struct {
		Id              string
		CreatedAt       time.Time
		UpdatedAt       time.Time
		DeletedAt       *time.Time
		Key             string
		Description     string
		DefaultValue    *string
		IsRequired      bool
		Immutable       bool
		SystemGenerated bool
	}
	TemplateScanner struct {
		Id        string
		CreatedAt time.Time
		UpdatedAt time.Time
		DeletedAt *time.Time
		Name      string
		AuthorId  string
		IsDefault bool
		Tags      []string
	}
	RunRecordScanner struct {
		Id                  string
		AuthorId            string
		CreatedAt           time.Time
		UpdatedAt           time.Time
		DeletedAt           *time.Time
		Status              int32
		RunInfo             []byte
		Tps                 []byte
		GrafanaDashboardUrl string
		WorkflowId          *string
		CloudRunParams      pgtype.JSONB
	}
	RunRecordStepScanner struct {
		Id        string
		CreatedAt time.Time
		UpdatedAt time.Time
		DeletedAt *time.Time
		RunId     string
		Status    int32
		StepInfo  []byte
	}
	WorkflowScanner struct {
		Id        string
		CreatedAt time.Time
		UpdatedAt time.Time
		DeletedAt *time.Time
	}
	WorkflowTaskScanner struct {
		Id            string
		CreatedAt     time.Time
		UpdatedAt     time.Time
		DeletedAt     *time.Time
		TaskType      int32
		Status        int32
		WorkflowId    string
		CleanedUp     bool
		OnWorker      string
		RetryState    []byte
		Logs          [][]byte
		RetrySettings []byte
		Input         []byte
		Output        []byte
		Metadata      []byte
	}
	WorkflowEdgeScanner struct {
		FromId     string
		ToId       string
		WorkflowId string
	}
)

func newUserScanner() *UserScanner {
	return &UserScanner{}
}
func (s *UserScanner) values() []any {
	return []any{
		s.Id,
		s.CreatedAt,
		s.UpdatedAt,
		s.DeletedAt,
		s.Email,
		s.Admin,
		s.PasswordHash,
	}
}
func (s *UserScanner) getTarget(field string) func() any {
	switch field {
	case "id":
		return func() any { return &s.Id }
	case "created_at":
		return func() any { return &s.CreatedAt }
	case "updated_at":
		return func() any { return &s.UpdatedAt }
	case "deleted_at":
		return func() any { return &s.DeletedAt }
	case "email":
		return func() any { return &s.Email }
	case "admin":
		return func() any { return &s.Admin }
	case "password_hash":
		return func() any { return &s.PasswordHash }
	default:
		panic("unknown field: " + field)
	}
}
func (s *UserScanner) getSetter(field UserField) func() ValueSetter[UserField] {
	switch field.String() {
	case "id":
		return func() ValueSetter[UserField] {
			return NewValueSetter[UserField](User.Id, s.Id)
		}
	case "created_at":
		return func() ValueSetter[UserField] {
			return NewValueSetter[UserField](User.CreatedAt, s.CreatedAt)
		}
	case "updated_at":
		return func() ValueSetter[UserField] {
			return NewValueSetter[UserField](User.UpdatedAt, s.UpdatedAt)
		}
	case "deleted_at":
		return func() ValueSetter[UserField] {
			return NewValueSetter[UserField](User.DeletedAt, s.DeletedAt)
		}
	case "email":
		return func() ValueSetter[UserField] {
			return NewValueSetter[UserField](User.Email, s.Email)
		}
	case "admin":
		return func() ValueSetter[UserField] {
			return NewValueSetter[UserField](User.Admin, s.Admin)
		}
	case "password_hash":
		return func() ValueSetter[UserField] {
			return NewValueSetter[UserField](User.PasswordHash, s.PasswordHash)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *UserScanner) getValue(field UserField) func() any {
	switch field.String() {
	case "id":
		return func() any { return s.Id }
	case "created_at":
		return func() any { return s.CreatedAt }
	case "updated_at":
		return func() any { return s.UpdatedAt }
	case "deleted_at":
		return func() any { return s.DeletedAt }
	case "email":
		return func() any { return s.Email }
	case "admin":
		return func() any { return s.Admin }
	case "password_hash":
		return func() any { return s.PasswordHash }
	default:
		panic("unknown field: " + field.String())
	}
}
func newRefreshTokensScanner() *RefreshTokensScanner {
	return &RefreshTokensScanner{}
}
func (s *RefreshTokensScanner) values() []any {
	return []any{
		s.UserId,
		s.Token,
	}
}
func (s *RefreshTokensScanner) getTarget(field string) func() any {
	switch field {
	case "user_id":
		return func() any { return &s.UserId }
	case "token":
		return func() any { return &s.Token }
	default:
		panic("unknown field: " + field)
	}
}
func (s *RefreshTokensScanner) getSetter(field RefreshTokensField) func() ValueSetter[RefreshTokensField] {
	switch field.String() {
	case "user_id":
		return func() ValueSetter[RefreshTokensField] {
			return NewValueSetter[RefreshTokensField](RefreshTokens.UserId, s.UserId)
		}
	case "token":
		return func() ValueSetter[RefreshTokensField] {
			return NewValueSetter[RefreshTokensField](RefreshTokens.Token, s.Token)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *RefreshTokensScanner) getValue(field RefreshTokensField) func() any {
	switch field.String() {
	case "user_id":
		return func() any { return s.UserId }
	case "token":
		return func() any { return s.Token }
	default:
		panic("unknown field: " + field.String())
	}
}
func newKvinfoScanner() *KvinfoScanner {
	return &KvinfoScanner{}
}
func (s *KvinfoScanner) values() []any {
	return []any{
		s.Id,
		s.CreatedAt,
		s.UpdatedAt,
		s.DeletedAt,
		s.Key,
		s.Description,
		s.DefaultValue,
		s.IsRequired,
		s.Immutable,
		s.SystemGenerated,
	}
}
func (s *KvinfoScanner) getTarget(field string) func() any {
	switch field {
	case "id":
		return func() any { return &s.Id }
	case "created_at":
		return func() any { return &s.CreatedAt }
	case "updated_at":
		return func() any { return &s.UpdatedAt }
	case "deleted_at":
		return func() any { return &s.DeletedAt }
	case "key":
		return func() any { return &s.Key }
	case "description":
		return func() any { return &s.Description }
	case "default_value":
		return func() any { return &s.DefaultValue }
	case "is_required":
		return func() any { return &s.IsRequired }
	case "immutable":
		return func() any { return &s.Immutable }
	case "system_generated":
		return func() any { return &s.SystemGenerated }
	default:
		panic("unknown field: " + field)
	}
}
func (s *KvinfoScanner) getSetter(field KvinfoField) func() ValueSetter[KvinfoField] {
	switch field.String() {
	case "id":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.Id, s.Id)
		}
	case "created_at":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.CreatedAt, s.CreatedAt)
		}
	case "updated_at":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.UpdatedAt, s.UpdatedAt)
		}
	case "deleted_at":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.DeletedAt, s.DeletedAt)
		}
	case "key":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.Key, s.Key)
		}
	case "description":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.Description, s.Description)
		}
	case "default_value":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.DefaultValue, s.DefaultValue)
		}
	case "is_required":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.IsRequired, s.IsRequired)
		}
	case "immutable":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.Immutable, s.Immutable)
		}
	case "system_generated":
		return func() ValueSetter[KvinfoField] {
			return NewValueSetter[KvinfoField](Kvinfo.SystemGenerated, s.SystemGenerated)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *KvinfoScanner) getValue(field KvinfoField) func() any {
	switch field.String() {
	case "id":
		return func() any { return s.Id }
	case "created_at":
		return func() any { return s.CreatedAt }
	case "updated_at":
		return func() any { return s.UpdatedAt }
	case "deleted_at":
		return func() any { return s.DeletedAt }
	case "key":
		return func() any { return s.Key }
	case "description":
		return func() any { return s.Description }
	case "default_value":
		return func() any { return s.DefaultValue }
	case "is_required":
		return func() any { return s.IsRequired }
	case "immutable":
		return func() any { return s.Immutable }
	case "system_generated":
		return func() any { return s.SystemGenerated }
	default:
		panic("unknown field: " + field.String())
	}
}
func newTemplateScanner() *TemplateScanner {
	return &TemplateScanner{}
}
func (s *TemplateScanner) values() []any {
	return []any{
		s.Id,
		s.CreatedAt,
		s.UpdatedAt,
		s.DeletedAt,
		s.Name,
		s.AuthorId,
		s.IsDefault,
		s.Tags,
	}
}
func (s *TemplateScanner) getTarget(field string) func() any {
	switch field {
	case "id":
		return func() any { return &s.Id }
	case "created_at":
		return func() any { return &s.CreatedAt }
	case "updated_at":
		return func() any { return &s.UpdatedAt }
	case "deleted_at":
		return func() any { return &s.DeletedAt }
	case "name":
		return func() any { return &s.Name }
	case "author_id":
		return func() any { return &s.AuthorId }
	case "is_default":
		return func() any { return &s.IsDefault }
	case "tags":
		return func() any { return &s.Tags }
	default:
		panic("unknown field: " + field)
	}
}
func (s *TemplateScanner) getSetter(field TemplateField) func() ValueSetter[TemplateField] {
	switch field.String() {
	case "id":
		return func() ValueSetter[TemplateField] {
			return NewValueSetter[TemplateField](Template.Id, s.Id)
		}
	case "created_at":
		return func() ValueSetter[TemplateField] {
			return NewValueSetter[TemplateField](Template.CreatedAt, s.CreatedAt)
		}
	case "updated_at":
		return func() ValueSetter[TemplateField] {
			return NewValueSetter[TemplateField](Template.UpdatedAt, s.UpdatedAt)
		}
	case "deleted_at":
		return func() ValueSetter[TemplateField] {
			return NewValueSetter[TemplateField](Template.DeletedAt, s.DeletedAt)
		}
	case "name":
		return func() ValueSetter[TemplateField] {
			return NewValueSetter[TemplateField](Template.Name, s.Name)
		}
	case "author_id":
		return func() ValueSetter[TemplateField] {
			return NewValueSetter[TemplateField](Template.AuthorId, s.AuthorId)
		}
	case "is_default":
		return func() ValueSetter[TemplateField] {
			return NewValueSetter[TemplateField](Template.IsDefault, s.IsDefault)
		}
	case "tags":
		return func() ValueSetter[TemplateField] {
			return NewValueSetter[TemplateField](Template.Tags, s.Tags)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *TemplateScanner) getValue(field TemplateField) func() any {
	switch field.String() {
	case "id":
		return func() any { return s.Id }
	case "created_at":
		return func() any { return s.CreatedAt }
	case "updated_at":
		return func() any { return s.UpdatedAt }
	case "deleted_at":
		return func() any { return s.DeletedAt }
	case "name":
		return func() any { return s.Name }
	case "author_id":
		return func() any { return s.AuthorId }
	case "is_default":
		return func() any { return s.IsDefault }
	case "tags":
		return func() any { return s.Tags }
	default:
		panic("unknown field: " + field.String())
	}
}
func newRunRecordScanner() *RunRecordScanner {
	return &RunRecordScanner{}
}
func (s *RunRecordScanner) values() []any {
	return []any{
		s.Id,
		s.AuthorId,
		s.CreatedAt,
		s.UpdatedAt,
		s.DeletedAt,
		s.Status,
		s.RunInfo,
		s.Tps,
		s.GrafanaDashboardUrl,
		s.WorkflowId,
		s.CloudRunParams,
	}
}
func (s *RunRecordScanner) getTarget(field string) func() any {
	switch field {
	case "id":
		return func() any { return &s.Id }
	case "author_id":
		return func() any { return &s.AuthorId }
	case "created_at":
		return func() any { return &s.CreatedAt }
	case "updated_at":
		return func() any { return &s.UpdatedAt }
	case "deleted_at":
		return func() any { return &s.DeletedAt }
	case "status":
		return func() any { return &s.Status }
	case "run_info":
		return func() any { return &s.RunInfo }
	case "tps":
		return func() any { return &s.Tps }
	case "grafana_dashboard_url":
		return func() any { return &s.GrafanaDashboardUrl }
	case "workflow_id":
		return func() any { return &s.WorkflowId }
	case "cloud_run_params":
		return func() any { return &s.CloudRunParams }
	default:
		panic("unknown field: " + field)
	}
}
func (s *RunRecordScanner) getSetter(field RunRecordField) func() ValueSetter[RunRecordField] {
	switch field.String() {
	case "id":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.Id, s.Id)
		}
	case "author_id":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.AuthorId, s.AuthorId)
		}
	case "created_at":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.CreatedAt, s.CreatedAt)
		}
	case "updated_at":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.UpdatedAt, s.UpdatedAt)
		}
	case "deleted_at":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.DeletedAt, s.DeletedAt)
		}
	case "status":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.Status, s.Status)
		}
	case "run_info":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.RunInfo, s.RunInfo)
		}
	case "tps":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.Tps, s.Tps)
		}
	case "grafana_dashboard_url":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.GrafanaDashboardUrl, s.GrafanaDashboardUrl)
		}
	case "workflow_id":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.WorkflowId, s.WorkflowId)
		}
	case "cloud_run_params":
		return func() ValueSetter[RunRecordField] {
			return NewValueSetter[RunRecordField](RunRecord.CloudRunParams, s.CloudRunParams)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *RunRecordScanner) getValue(field RunRecordField) func() any {
	switch field.String() {
	case "id":
		return func() any { return s.Id }
	case "author_id":
		return func() any { return s.AuthorId }
	case "created_at":
		return func() any { return s.CreatedAt }
	case "updated_at":
		return func() any { return s.UpdatedAt }
	case "deleted_at":
		return func() any { return s.DeletedAt }
	case "status":
		return func() any { return s.Status }
	case "run_info":
		return func() any { return s.RunInfo }
	case "tps":
		return func() any { return s.Tps }
	case "grafana_dashboard_url":
		return func() any { return s.GrafanaDashboardUrl }
	case "workflow_id":
		return func() any { return s.WorkflowId }
	case "cloud_run_params":
		return func() any { return s.CloudRunParams }
	default:
		panic("unknown field: " + field.String())
	}
}
func newRunRecordStepScanner() *RunRecordStepScanner {
	return &RunRecordStepScanner{}
}
func (s *RunRecordStepScanner) values() []any {
	return []any{
		s.Id,
		s.CreatedAt,
		s.UpdatedAt,
		s.DeletedAt,
		s.RunId,
		s.Status,
		s.StepInfo,
	}
}
func (s *RunRecordStepScanner) getTarget(field string) func() any {
	switch field {
	case "id":
		return func() any { return &s.Id }
	case "created_at":
		return func() any { return &s.CreatedAt }
	case "updated_at":
		return func() any { return &s.UpdatedAt }
	case "deleted_at":
		return func() any { return &s.DeletedAt }
	case "run_id":
		return func() any { return &s.RunId }
	case "status":
		return func() any { return &s.Status }
	case "step_info":
		return func() any { return &s.StepInfo }
	default:
		panic("unknown field: " + field)
	}
}
func (s *RunRecordStepScanner) getSetter(field RunRecordStepField) func() ValueSetter[RunRecordStepField] {
	switch field.String() {
	case "id":
		return func() ValueSetter[RunRecordStepField] {
			return NewValueSetter[RunRecordStepField](RunRecordStep.Id, s.Id)
		}
	case "created_at":
		return func() ValueSetter[RunRecordStepField] {
			return NewValueSetter[RunRecordStepField](RunRecordStep.CreatedAt, s.CreatedAt)
		}
	case "updated_at":
		return func() ValueSetter[RunRecordStepField] {
			return NewValueSetter[RunRecordStepField](RunRecordStep.UpdatedAt, s.UpdatedAt)
		}
	case "deleted_at":
		return func() ValueSetter[RunRecordStepField] {
			return NewValueSetter[RunRecordStepField](RunRecordStep.DeletedAt, s.DeletedAt)
		}
	case "run_id":
		return func() ValueSetter[RunRecordStepField] {
			return NewValueSetter[RunRecordStepField](RunRecordStep.RunId, s.RunId)
		}
	case "status":
		return func() ValueSetter[RunRecordStepField] {
			return NewValueSetter[RunRecordStepField](RunRecordStep.Status, s.Status)
		}
	case "step_info":
		return func() ValueSetter[RunRecordStepField] {
			return NewValueSetter[RunRecordStepField](RunRecordStep.StepInfo, s.StepInfo)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *RunRecordStepScanner) getValue(field RunRecordStepField) func() any {
	switch field.String() {
	case "id":
		return func() any { return s.Id }
	case "created_at":
		return func() any { return s.CreatedAt }
	case "updated_at":
		return func() any { return s.UpdatedAt }
	case "deleted_at":
		return func() any { return s.DeletedAt }
	case "run_id":
		return func() any { return s.RunId }
	case "status":
		return func() any { return s.Status }
	case "step_info":
		return func() any { return s.StepInfo }
	default:
		panic("unknown field: " + field.String())
	}
}
func newWorkflowScanner() *WorkflowScanner {
	return &WorkflowScanner{}
}
func (s *WorkflowScanner) values() []any {
	return []any{
		s.Id,
		s.CreatedAt,
		s.UpdatedAt,
		s.DeletedAt,
	}
}
func (s *WorkflowScanner) getTarget(field string) func() any {
	switch field {
	case "id":
		return func() any { return &s.Id }
	case "created_at":
		return func() any { return &s.CreatedAt }
	case "updated_at":
		return func() any { return &s.UpdatedAt }
	case "deleted_at":
		return func() any { return &s.DeletedAt }
	default:
		panic("unknown field: " + field)
	}
}
func (s *WorkflowScanner) getSetter(field WorkflowField) func() ValueSetter[WorkflowField] {
	switch field.String() {
	case "id":
		return func() ValueSetter[WorkflowField] {
			return NewValueSetter[WorkflowField](Workflow.Id, s.Id)
		}
	case "created_at":
		return func() ValueSetter[WorkflowField] {
			return NewValueSetter[WorkflowField](Workflow.CreatedAt, s.CreatedAt)
		}
	case "updated_at":
		return func() ValueSetter[WorkflowField] {
			return NewValueSetter[WorkflowField](Workflow.UpdatedAt, s.UpdatedAt)
		}
	case "deleted_at":
		return func() ValueSetter[WorkflowField] {
			return NewValueSetter[WorkflowField](Workflow.DeletedAt, s.DeletedAt)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *WorkflowScanner) getValue(field WorkflowField) func() any {
	switch field.String() {
	case "id":
		return func() any { return s.Id }
	case "created_at":
		return func() any { return s.CreatedAt }
	case "updated_at":
		return func() any { return s.UpdatedAt }
	case "deleted_at":
		return func() any { return s.DeletedAt }
	default:
		panic("unknown field: " + field.String())
	}
}
func newWorkflowTaskScanner() *WorkflowTaskScanner {
	return &WorkflowTaskScanner{}
}
func (s *WorkflowTaskScanner) values() []any {
	return []any{
		s.Id,
		s.CreatedAt,
		s.UpdatedAt,
		s.DeletedAt,
		s.TaskType,
		s.Status,
		s.WorkflowId,
		s.CleanedUp,
		s.OnWorker,
		s.RetryState,
		s.Logs,
		s.RetrySettings,
		s.Input,
		s.Output,
		s.Metadata,
	}
}
func (s *WorkflowTaskScanner) getTarget(field string) func() any {
	switch field {
	case "id":
		return func() any { return &s.Id }
	case "created_at":
		return func() any { return &s.CreatedAt }
	case "updated_at":
		return func() any { return &s.UpdatedAt }
	case "deleted_at":
		return func() any { return &s.DeletedAt }
	case "task_type":
		return func() any { return &s.TaskType }
	case "status":
		return func() any { return &s.Status }
	case "workflow_id":
		return func() any { return &s.WorkflowId }
	case "cleaned_up":
		return func() any { return &s.CleanedUp }
	case "on_worker":
		return func() any { return &s.OnWorker }
	case "retry_state":
		return func() any { return &s.RetryState }
	case "logs":
		return func() any { return &s.Logs }
	case "retry_settings":
		return func() any { return &s.RetrySettings }
	case "input":
		return func() any { return &s.Input }
	case "output":
		return func() any { return &s.Output }
	case "metadata":
		return func() any { return &s.Metadata }
	default:
		panic("unknown field: " + field)
	}
}
func (s *WorkflowTaskScanner) getSetter(field WorkflowTaskField) func() ValueSetter[WorkflowTaskField] {
	switch field.String() {
	case "id":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.Id, s.Id)
		}
	case "created_at":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.CreatedAt, s.CreatedAt)
		}
	case "updated_at":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.UpdatedAt, s.UpdatedAt)
		}
	case "deleted_at":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.DeletedAt, s.DeletedAt)
		}
	case "task_type":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.TaskType, s.TaskType)
		}
	case "status":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.Status, s.Status)
		}
	case "workflow_id":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.WorkflowId, s.WorkflowId)
		}
	case "cleaned_up":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.CleanedUp, s.CleanedUp)
		}
	case "on_worker":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.OnWorker, s.OnWorker)
		}
	case "retry_state":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.RetryState, s.RetryState)
		}
	case "logs":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.Logs, s.Logs)
		}
	case "retry_settings":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.RetrySettings, s.RetrySettings)
		}
	case "input":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.Input, s.Input)
		}
	case "output":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.Output, s.Output)
		}
	case "metadata":
		return func() ValueSetter[WorkflowTaskField] {
			return NewValueSetter[WorkflowTaskField](WorkflowTask.Metadata, s.Metadata)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *WorkflowTaskScanner) getValue(field WorkflowTaskField) func() any {
	switch field.String() {
	case "id":
		return func() any { return s.Id }
	case "created_at":
		return func() any { return s.CreatedAt }
	case "updated_at":
		return func() any { return s.UpdatedAt }
	case "deleted_at":
		return func() any { return s.DeletedAt }
	case "task_type":
		return func() any { return s.TaskType }
	case "status":
		return func() any { return s.Status }
	case "workflow_id":
		return func() any { return s.WorkflowId }
	case "cleaned_up":
		return func() any { return s.CleanedUp }
	case "on_worker":
		return func() any { return s.OnWorker }
	case "retry_state":
		return func() any { return s.RetryState }
	case "logs":
		return func() any { return s.Logs }
	case "retry_settings":
		return func() any { return s.RetrySettings }
	case "input":
		return func() any { return s.Input }
	case "output":
		return func() any { return s.Output }
	case "metadata":
		return func() any { return s.Metadata }
	default:
		panic("unknown field: " + field.String())
	}
}
func newWorkflowEdgeScanner() *WorkflowEdgeScanner {
	return &WorkflowEdgeScanner{}
}
func (s *WorkflowEdgeScanner) values() []any {
	return []any{
		s.FromId,
		s.ToId,
		s.WorkflowId,
	}
}
func (s *WorkflowEdgeScanner) getTarget(field string) func() any {
	switch field {
	case "from_id":
		return func() any { return &s.FromId }
	case "to_id":
		return func() any { return &s.ToId }
	case "workflow_id":
		return func() any { return &s.WorkflowId }
	default:
		panic("unknown field: " + field)
	}
}
func (s *WorkflowEdgeScanner) getSetter(field WorkflowEdgeField) func() ValueSetter[WorkflowEdgeField] {
	switch field.String() {
	case "from_id":
		return func() ValueSetter[WorkflowEdgeField] {
			return NewValueSetter[WorkflowEdgeField](WorkflowEdge.FromId, s.FromId)
		}
	case "to_id":
		return func() ValueSetter[WorkflowEdgeField] {
			return NewValueSetter[WorkflowEdgeField](WorkflowEdge.ToId, s.ToId)
		}
	case "workflow_id":
		return func() ValueSetter[WorkflowEdgeField] {
			return NewValueSetter[WorkflowEdgeField](WorkflowEdge.WorkflowId, s.WorkflowId)
		}
	default:
		panic("unknown field: " + field.String())
	}
}
func (s *WorkflowEdgeScanner) getValue(field WorkflowEdgeField) func() any {
	switch field.String() {
	case "from_id":
		return func() any { return s.FromId }
	case "to_id":
		return func() any { return s.ToId }
	case "workflow_id":
		return func() any { return s.WorkflowId }
	default:
		panic("unknown field: " + field.String())
	}
}

type (
	userTableImpl struct {
		*table[UserField, *UserScanner]
		Id interface {
			UserField
			CommonOperator[string, UserField]
			ScalarOperator[string, UserField]
			LikeOperator[string, UserField]
		}
		CreatedAt interface {
			UserField
			CommonOperator[time.Time, UserField]
			ScalarOperator[time.Time, UserField]
		}
		UpdatedAt interface {
			UserField
			CommonOperator[time.Time, UserField]
			ScalarOperator[time.Time, UserField]
		}
		DeletedAt interface {
			UserField
			CommonOperator[*time.Time, UserField]
			ScalarOperator[*time.Time, UserField]
			IsNullOperator[*time.Time, UserField]
		}
		Email interface {
			UserField
			CommonOperator[string, UserField]
			ScalarOperator[string, UserField]
			LikeOperator[string, UserField]
		}
		Admin interface {
			UserField
			CommonOperator[bool, UserField]
			ScalarOperator[bool, UserField]
		}
		PasswordHash interface {
			UserField
			CommonOperator[string, UserField]
			ScalarOperator[string, UserField]
			LikeOperator[string, UserField]
		}
	}
	refreshTokensTableImpl struct {
		*table[RefreshTokensField, *RefreshTokensScanner]
		UserId interface {
			RefreshTokensField
			CommonOperator[string, RefreshTokensField]
			ScalarOperator[string, RefreshTokensField]
			LikeOperator[string, RefreshTokensField]
		}
		Token interface {
			RefreshTokensField
			CommonOperator[string, RefreshTokensField]
			ScalarOperator[string, RefreshTokensField]
			LikeOperator[string, RefreshTokensField]
		}
	}
	kvinfoTableImpl struct {
		*table[KvinfoField, *KvinfoScanner]
		Id interface {
			KvinfoField
			CommonOperator[string, KvinfoField]
			ScalarOperator[string, KvinfoField]
			LikeOperator[string, KvinfoField]
		}
		CreatedAt interface {
			KvinfoField
			CommonOperator[time.Time, KvinfoField]
			ScalarOperator[time.Time, KvinfoField]
		}
		UpdatedAt interface {
			KvinfoField
			CommonOperator[time.Time, KvinfoField]
			ScalarOperator[time.Time, KvinfoField]
		}
		DeletedAt interface {
			KvinfoField
			CommonOperator[*time.Time, KvinfoField]
			ScalarOperator[*time.Time, KvinfoField]
			IsNullOperator[*time.Time, KvinfoField]
		}
		Key interface {
			KvinfoField
			CommonOperator[string, KvinfoField]
			ScalarOperator[string, KvinfoField]
			LikeOperator[string, KvinfoField]
		}
		Description interface {
			KvinfoField
			CommonOperator[string, KvinfoField]
			ScalarOperator[string, KvinfoField]
			LikeOperator[string, KvinfoField]
		}
		DefaultValue interface {
			KvinfoField
			CommonOperator[*string, KvinfoField]
			ScalarOperator[*string, KvinfoField]
			LikeOperator[*string, KvinfoField]
			IsNullOperator[*string, KvinfoField]
		}
		IsRequired interface {
			KvinfoField
			CommonOperator[bool, KvinfoField]
			ScalarOperator[bool, KvinfoField]
		}
		Immutable interface {
			KvinfoField
			CommonOperator[bool, KvinfoField]
			ScalarOperator[bool, KvinfoField]
		}
		SystemGenerated interface {
			KvinfoField
			CommonOperator[bool, KvinfoField]
			ScalarOperator[bool, KvinfoField]
		}
	}
	templateTableImpl struct {
		*table[TemplateField, *TemplateScanner]
		Id interface {
			TemplateField
			CommonOperator[string, TemplateField]
			ScalarOperator[string, TemplateField]
			LikeOperator[string, TemplateField]
		}
		CreatedAt interface {
			TemplateField
			CommonOperator[time.Time, TemplateField]
			ScalarOperator[time.Time, TemplateField]
		}
		UpdatedAt interface {
			TemplateField
			CommonOperator[time.Time, TemplateField]
			ScalarOperator[time.Time, TemplateField]
		}
		DeletedAt interface {
			TemplateField
			CommonOperator[*time.Time, TemplateField]
			ScalarOperator[*time.Time, TemplateField]
			IsNullOperator[*time.Time, TemplateField]
		}
		Name interface {
			TemplateField
			CommonOperator[string, TemplateField]
			ScalarOperator[string, TemplateField]
			LikeOperator[string, TemplateField]
		}
		AuthorId interface {
			TemplateField
			CommonOperator[string, TemplateField]
			ScalarOperator[string, TemplateField]
			LikeOperator[string, TemplateField]
		}
		IsDefault interface {
			TemplateField
			CommonOperator[bool, TemplateField]
			ScalarOperator[bool, TemplateField]
		}
		Tags interface {
			TemplateField
			CommonOperator[[]string, TemplateField]
			ScalarOperator[[]string, TemplateField]
			LikeOperator[[]string, TemplateField]
		}
	}
	runRecordTableImpl struct {
		*table[RunRecordField, *RunRecordScanner]
		Id interface {
			RunRecordField
			CommonOperator[string, RunRecordField]
			ScalarOperator[string, RunRecordField]
			LikeOperator[string, RunRecordField]
		}
		AuthorId interface {
			RunRecordField
			CommonOperator[string, RunRecordField]
			ScalarOperator[string, RunRecordField]
			LikeOperator[string, RunRecordField]
		}
		CreatedAt interface {
			RunRecordField
			CommonOperator[time.Time, RunRecordField]
			ScalarOperator[time.Time, RunRecordField]
		}
		UpdatedAt interface {
			RunRecordField
			CommonOperator[time.Time, RunRecordField]
			ScalarOperator[time.Time, RunRecordField]
		}
		DeletedAt interface {
			RunRecordField
			CommonOperator[*time.Time, RunRecordField]
			ScalarOperator[*time.Time, RunRecordField]
			IsNullOperator[*time.Time, RunRecordField]
		}
		Status interface {
			RunRecordField
			CommonOperator[int32, RunRecordField]
			ScalarOperator[int32, RunRecordField]
		}
		RunInfo interface {
			RunRecordField
			CommonOperator[[]byte, RunRecordField]
		}
		Tps interface {
			RunRecordField
			CommonOperator[[]byte, RunRecordField]
		}
		GrafanaDashboardUrl interface {
			RunRecordField
			CommonOperator[string, RunRecordField]
			ScalarOperator[string, RunRecordField]
			LikeOperator[string, RunRecordField]
		}
		WorkflowId interface {
			RunRecordField
			CommonOperator[*string, RunRecordField]
			ScalarOperator[*string, RunRecordField]
			LikeOperator[*string, RunRecordField]
			IsNullOperator[*string, RunRecordField]
		}
		CloudRunParams interface {
			RunRecordField
			CommonOperator[pgtype.JSONB, RunRecordField]
			IsNullOperator[pgtype.JSONB, RunRecordField]
		}
	}
	runRecordStepTableImpl struct {
		*table[RunRecordStepField, *RunRecordStepScanner]
		Id interface {
			RunRecordStepField
			CommonOperator[string, RunRecordStepField]
			ScalarOperator[string, RunRecordStepField]
			LikeOperator[string, RunRecordStepField]
		}
		CreatedAt interface {
			RunRecordStepField
			CommonOperator[time.Time, RunRecordStepField]
			ScalarOperator[time.Time, RunRecordStepField]
		}
		UpdatedAt interface {
			RunRecordStepField
			CommonOperator[time.Time, RunRecordStepField]
			ScalarOperator[time.Time, RunRecordStepField]
		}
		DeletedAt interface {
			RunRecordStepField
			CommonOperator[*time.Time, RunRecordStepField]
			ScalarOperator[*time.Time, RunRecordStepField]
			IsNullOperator[*time.Time, RunRecordStepField]
		}
		RunId interface {
			RunRecordStepField
			CommonOperator[string, RunRecordStepField]
			ScalarOperator[string, RunRecordStepField]
			LikeOperator[string, RunRecordStepField]
		}
		Status interface {
			RunRecordStepField
			CommonOperator[int32, RunRecordStepField]
			ScalarOperator[int32, RunRecordStepField]
		}
		StepInfo interface {
			RunRecordStepField
			CommonOperator[[]byte, RunRecordStepField]
		}
	}
	workflowTableImpl struct {
		*table[WorkflowField, *WorkflowScanner]
		Id interface {
			WorkflowField
			CommonOperator[string, WorkflowField]
			ScalarOperator[string, WorkflowField]
			LikeOperator[string, WorkflowField]
		}
		CreatedAt interface {
			WorkflowField
			CommonOperator[time.Time, WorkflowField]
			ScalarOperator[time.Time, WorkflowField]
		}
		UpdatedAt interface {
			WorkflowField
			CommonOperator[time.Time, WorkflowField]
			ScalarOperator[time.Time, WorkflowField]
		}
		DeletedAt interface {
			WorkflowField
			CommonOperator[*time.Time, WorkflowField]
			ScalarOperator[*time.Time, WorkflowField]
			IsNullOperator[*time.Time, WorkflowField]
		}
	}
	workflowTaskTableImpl struct {
		*table[WorkflowTaskField, *WorkflowTaskScanner]
		Id interface {
			WorkflowTaskField
			CommonOperator[string, WorkflowTaskField]
			ScalarOperator[string, WorkflowTaskField]
			LikeOperator[string, WorkflowTaskField]
		}
		CreatedAt interface {
			WorkflowTaskField
			CommonOperator[time.Time, WorkflowTaskField]
			ScalarOperator[time.Time, WorkflowTaskField]
		}
		UpdatedAt interface {
			WorkflowTaskField
			CommonOperator[time.Time, WorkflowTaskField]
			ScalarOperator[time.Time, WorkflowTaskField]
		}
		DeletedAt interface {
			WorkflowTaskField
			CommonOperator[*time.Time, WorkflowTaskField]
			ScalarOperator[*time.Time, WorkflowTaskField]
			IsNullOperator[*time.Time, WorkflowTaskField]
		}
		TaskType interface {
			WorkflowTaskField
			CommonOperator[int32, WorkflowTaskField]
			ScalarOperator[int32, WorkflowTaskField]
		}
		Status interface {
			WorkflowTaskField
			CommonOperator[int32, WorkflowTaskField]
			ScalarOperator[int32, WorkflowTaskField]
		}
		WorkflowId interface {
			WorkflowTaskField
			CommonOperator[string, WorkflowTaskField]
			ScalarOperator[string, WorkflowTaskField]
			LikeOperator[string, WorkflowTaskField]
		}
		CleanedUp interface {
			WorkflowTaskField
			CommonOperator[bool, WorkflowTaskField]
			ScalarOperator[bool, WorkflowTaskField]
		}
		OnWorker interface {
			WorkflowTaskField
			CommonOperator[string, WorkflowTaskField]
			ScalarOperator[string, WorkflowTaskField]
			LikeOperator[string, WorkflowTaskField]
		}
		RetryState interface {
			WorkflowTaskField
			CommonOperator[[]byte, WorkflowTaskField]
		}
		Logs interface {
			WorkflowTaskField
			CommonOperator[[][]byte, WorkflowTaskField]
		}
		RetrySettings interface {
			WorkflowTaskField
			CommonOperator[[]byte, WorkflowTaskField]
		}
		Input interface {
			WorkflowTaskField
			CommonOperator[[]byte, WorkflowTaskField]
		}
		Output interface {
			WorkflowTaskField
			CommonOperator[[]byte, WorkflowTaskField]
		}
		Metadata interface {
			WorkflowTaskField
			CommonOperator[[]byte, WorkflowTaskField]
		}
	}
	workflowEdgeTableImpl struct {
		*table[WorkflowEdgeField, *WorkflowEdgeScanner]
		FromId interface {
			WorkflowEdgeField
			CommonOperator[string, WorkflowEdgeField]
			ScalarOperator[string, WorkflowEdgeField]
			LikeOperator[string, WorkflowEdgeField]
		}
		ToId interface {
			WorkflowEdgeField
			CommonOperator[string, WorkflowEdgeField]
			ScalarOperator[string, WorkflowEdgeField]
			LikeOperator[string, WorkflowEdgeField]
		}
		WorkflowId interface {
			WorkflowEdgeField
			CommonOperator[string, WorkflowEdgeField]
			ScalarOperator[string, WorkflowEdgeField]
			LikeOperator[string, WorkflowEdgeField]
		}
	}
)

func newUserTableImpl() *userTableImpl {
	id := &useridFieldImpl{column: newColumn[string, UserField](fieldAliasImpl("id"))}
	createdAt := &usercreatedAtFieldImpl{column: newColumn[time.Time, UserField](fieldAliasImpl("created_at"))}
	updatedAt := &userupdatedAtFieldImpl{column: newColumn[time.Time, UserField](fieldAliasImpl("updated_at"))}
	deletedAt := &userdeletedAtFieldImpl{column: newColumn[*time.Time, UserField](fieldAliasImpl("deleted_at"))}
	email := &useremailFieldImpl{column: newColumn[string, UserField](fieldAliasImpl("email"))}
	admin := &useradminFieldImpl{column: newColumn[bool, UserField](fieldAliasImpl("admin"))}
	passwordHash := &userpasswordHashFieldImpl{column: newColumn[string, UserField](fieldAliasImpl("password_hash"))}
	return &userTableImpl{
		table: newTable[UserField, *UserScanner](
			"users",
			newUserScanner,
			id,
			createdAt,
			updatedAt,
			deletedAt,
			email,
			admin,
			passwordHash,
		),
		Id:           id,
		CreatedAt:    createdAt,
		UpdatedAt:    updatedAt,
		DeletedAt:    deletedAt,
		Email:        email,
		Admin:        admin,
		PasswordHash: passwordHash,
	}
}
func newRefreshTokensTableImpl() *refreshTokensTableImpl {
	userId := &refreshTokensuserIdFieldImpl{column: newColumn[string, RefreshTokensField](fieldAliasImpl("user_id"))}
	token := &refreshTokenstokenFieldImpl{column: newColumn[string, RefreshTokensField](fieldAliasImpl("token"))}
	return &refreshTokensTableImpl{
		table: newTable[RefreshTokensField, *RefreshTokensScanner](
			"refresh_tokens",
			newRefreshTokensScanner,
			userId,
			token,
		),
		UserId: userId,
		Token:  token,
	}
}
func newKvinfoTableImpl() *kvinfoTableImpl {
	id := &kvinfoidFieldImpl{column: newColumn[string, KvinfoField](fieldAliasImpl("id"))}
	createdAt := &kvinfocreatedAtFieldImpl{column: newColumn[time.Time, KvinfoField](fieldAliasImpl("created_at"))}
	updatedAt := &kvinfoupdatedAtFieldImpl{column: newColumn[time.Time, KvinfoField](fieldAliasImpl("updated_at"))}
	deletedAt := &kvinfodeletedAtFieldImpl{column: newColumn[*time.Time, KvinfoField](fieldAliasImpl("deleted_at"))}
	key := &kvinfokeyFieldImpl{column: newColumn[string, KvinfoField](fieldAliasImpl("key"))}
	description := &kvinfodescriptionFieldImpl{column: newColumn[string, KvinfoField](fieldAliasImpl("description"))}
	defaultValue := &kvinfodefaultValueFieldImpl{column: newColumn[*string, KvinfoField](fieldAliasImpl("default_value"))}
	isRequired := &kvinfoisRequiredFieldImpl{column: newColumn[bool, KvinfoField](fieldAliasImpl("is_required"))}
	immutable := &kvinfoimmutableFieldImpl{column: newColumn[bool, KvinfoField](fieldAliasImpl("immutable"))}
	systemGenerated := &kvinfosystemGeneratedFieldImpl{column: newColumn[bool, KvinfoField](fieldAliasImpl("system_generated"))}
	return &kvinfoTableImpl{
		table: newTable[KvinfoField, *KvinfoScanner](
			"system_kv_info",
			newKvinfoScanner,
			id,
			createdAt,
			updatedAt,
			deletedAt,
			key,
			description,
			defaultValue,
			isRequired,
			immutable,
			systemGenerated,
		),
		Id:              id,
		CreatedAt:       createdAt,
		UpdatedAt:       updatedAt,
		DeletedAt:       deletedAt,
		Key:             key,
		Description:     description,
		DefaultValue:    defaultValue,
		IsRequired:      isRequired,
		Immutable:       immutable,
		SystemGenerated: systemGenerated,
	}
}
func newTemplateTableImpl() *templateTableImpl {
	id := &templateidFieldImpl{column: newColumn[string, TemplateField](fieldAliasImpl("id"))}
	createdAt := &templatecreatedAtFieldImpl{column: newColumn[time.Time, TemplateField](fieldAliasImpl("created_at"))}
	updatedAt := &templateupdatedAtFieldImpl{column: newColumn[time.Time, TemplateField](fieldAliasImpl("updated_at"))}
	deletedAt := &templatedeletedAtFieldImpl{column: newColumn[*time.Time, TemplateField](fieldAliasImpl("deleted_at"))}
	name := &templatenameFieldImpl{column: newColumn[string, TemplateField](fieldAliasImpl("name"))}
	authorId := &templateauthorIdFieldImpl{column: newColumn[string, TemplateField](fieldAliasImpl("author_id"))}
	isDefault := &templateisDefaultFieldImpl{column: newColumn[bool, TemplateField](fieldAliasImpl("is_default"))}
	tags := &templatetagsFieldImpl{column: newColumn[[]string, TemplateField](fieldAliasImpl("tags"))}
	return &templateTableImpl{
		table: newTable[TemplateField, *TemplateScanner](
			"templates",
			newTemplateScanner,
			id,
			createdAt,
			updatedAt,
			deletedAt,
			name,
			authorId,
			isDefault,
			tags,
		),
		Id:        id,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
		DeletedAt: deletedAt,
		Name:      name,
		AuthorId:  authorId,
		IsDefault: isDefault,
		Tags:      tags,
	}
}
func newRunRecordTableImpl() *runRecordTableImpl {
	id := &runRecordidFieldImpl{column: newColumn[string, RunRecordField](fieldAliasImpl("id"))}
	authorId := &runRecordauthorIdFieldImpl{column: newColumn[string, RunRecordField](fieldAliasImpl("author_id"))}
	createdAt := &runRecordcreatedAtFieldImpl{column: newColumn[time.Time, RunRecordField](fieldAliasImpl("created_at"))}
	updatedAt := &runRecordupdatedAtFieldImpl{column: newColumn[time.Time, RunRecordField](fieldAliasImpl("updated_at"))}
	deletedAt := &runRecorddeletedAtFieldImpl{column: newColumn[*time.Time, RunRecordField](fieldAliasImpl("deleted_at"))}
	status := &runRecordstatusFieldImpl{column: newColumn[int32, RunRecordField](fieldAliasImpl("status"))}
	runInfo := &runRecordrunInfoFieldImpl{column: newColumn[[]byte, RunRecordField](fieldAliasImpl("run_info"))}
	tps := &runRecordtpsFieldImpl{column: newColumn[[]byte, RunRecordField](fieldAliasImpl("tps"))}
	grafanaDashboardUrl := &runRecordgrafanaDashboardUrlFieldImpl{column: newColumn[string, RunRecordField](fieldAliasImpl("grafana_dashboard_url"))}
	workflowId := &runRecordworkflowIdFieldImpl{column: newColumn[*string, RunRecordField](fieldAliasImpl("workflow_id"))}
	cloudRunParams := &runRecordcloudRunParamsFieldImpl{column: newColumn[pgtype.JSONB, RunRecordField](fieldAliasImpl("cloud_run_params"))}
	return &runRecordTableImpl{
		table: newTable[RunRecordField, *RunRecordScanner](
			"run_records",
			newRunRecordScanner,
			id,
			authorId,
			createdAt,
			updatedAt,
			deletedAt,
			status,
			runInfo,
			tps,
			grafanaDashboardUrl,
			workflowId,
			cloudRunParams,
		),
		Id:                  id,
		AuthorId:            authorId,
		CreatedAt:           createdAt,
		UpdatedAt:           updatedAt,
		DeletedAt:           deletedAt,
		Status:              status,
		RunInfo:             runInfo,
		Tps:                 tps,
		GrafanaDashboardUrl: grafanaDashboardUrl,
		WorkflowId:          workflowId,
		CloudRunParams:      cloudRunParams,
	}
}
func newRunRecordStepTableImpl() *runRecordStepTableImpl {
	id := &runRecordStepidFieldImpl{column: newColumn[string, RunRecordStepField](fieldAliasImpl("id"))}
	createdAt := &runRecordStepcreatedAtFieldImpl{column: newColumn[time.Time, RunRecordStepField](fieldAliasImpl("created_at"))}
	updatedAt := &runRecordStepupdatedAtFieldImpl{column: newColumn[time.Time, RunRecordStepField](fieldAliasImpl("updated_at"))}
	deletedAt := &runRecordStepdeletedAtFieldImpl{column: newColumn[*time.Time, RunRecordStepField](fieldAliasImpl("deleted_at"))}
	runId := &runRecordSteprunIdFieldImpl{column: newColumn[string, RunRecordStepField](fieldAliasImpl("run_id"))}
	status := &runRecordStepstatusFieldImpl{column: newColumn[int32, RunRecordStepField](fieldAliasImpl("status"))}
	stepInfo := &runRecordStepstepInfoFieldImpl{column: newColumn[[]byte, RunRecordStepField](fieldAliasImpl("step_info"))}
	return &runRecordStepTableImpl{
		table: newTable[RunRecordStepField, *RunRecordStepScanner](
			"run_record_steps",
			newRunRecordStepScanner,
			id,
			createdAt,
			updatedAt,
			deletedAt,
			runId,
			status,
			stepInfo,
		),
		Id:        id,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
		DeletedAt: deletedAt,
		RunId:     runId,
		Status:    status,
		StepInfo:  stepInfo,
	}
}
func newWorkflowTableImpl() *workflowTableImpl {
	id := &workflowidFieldImpl{column: newColumn[string, WorkflowField](fieldAliasImpl("id"))}
	createdAt := &workflowcreatedAtFieldImpl{column: newColumn[time.Time, WorkflowField](fieldAliasImpl("created_at"))}
	updatedAt := &workflowupdatedAtFieldImpl{column: newColumn[time.Time, WorkflowField](fieldAliasImpl("updated_at"))}
	deletedAt := &workflowdeletedAtFieldImpl{column: newColumn[*time.Time, WorkflowField](fieldAliasImpl("deleted_at"))}
	return &workflowTableImpl{
		table: newTable[WorkflowField, *WorkflowScanner](
			"workflows",
			newWorkflowScanner,
			id,
			createdAt,
			updatedAt,
			deletedAt,
		),
		Id:        id,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
		DeletedAt: deletedAt,
	}
}
func newWorkflowTaskTableImpl() *workflowTaskTableImpl {
	id := &workflowTaskidFieldImpl{column: newColumn[string, WorkflowTaskField](fieldAliasImpl("id"))}
	createdAt := &workflowTaskcreatedAtFieldImpl{column: newColumn[time.Time, WorkflowTaskField](fieldAliasImpl("created_at"))}
	updatedAt := &workflowTaskupdatedAtFieldImpl{column: newColumn[time.Time, WorkflowTaskField](fieldAliasImpl("updated_at"))}
	deletedAt := &workflowTaskdeletedAtFieldImpl{column: newColumn[*time.Time, WorkflowTaskField](fieldAliasImpl("deleted_at"))}
	taskType := &workflowTasktaskTypeFieldImpl{column: newColumn[int32, WorkflowTaskField](fieldAliasImpl("task_type"))}
	status := &workflowTaskstatusFieldImpl{column: newColumn[int32, WorkflowTaskField](fieldAliasImpl("status"))}
	workflowId := &workflowTaskworkflowIdFieldImpl{column: newColumn[string, WorkflowTaskField](fieldAliasImpl("workflow_id"))}
	cleanedUp := &workflowTaskcleanedUpFieldImpl{column: newColumn[bool, WorkflowTaskField](fieldAliasImpl("cleaned_up"))}
	onWorker := &workflowTaskonWorkerFieldImpl{column: newColumn[string, WorkflowTaskField](fieldAliasImpl("on_worker"))}
	retryState := &workflowTaskretryStateFieldImpl{column: newColumn[[]byte, WorkflowTaskField](fieldAliasImpl("retry_state"))}
	logs := &workflowTasklogsFieldImpl{column: newColumn[[][]byte, WorkflowTaskField](fieldAliasImpl("logs"))}
	retrySettings := &workflowTaskretrySettingsFieldImpl{column: newColumn[[]byte, WorkflowTaskField](fieldAliasImpl("retry_settings"))}
	input := &workflowTaskinputFieldImpl{column: newColumn[[]byte, WorkflowTaskField](fieldAliasImpl("input"))}
	output := &workflowTaskoutputFieldImpl{column: newColumn[[]byte, WorkflowTaskField](fieldAliasImpl("output"))}
	metadata := &workflowTaskmetadataFieldImpl{column: newColumn[[]byte, WorkflowTaskField](fieldAliasImpl("metadata"))}
	return &workflowTaskTableImpl{
		table: newTable[WorkflowTaskField, *WorkflowTaskScanner](
			"workflow_tasks",
			newWorkflowTaskScanner,
			id,
			createdAt,
			updatedAt,
			deletedAt,
			taskType,
			status,
			workflowId,
			cleanedUp,
			onWorker,
			retryState,
			logs,
			retrySettings,
			input,
			output,
			metadata,
		),
		Id:            id,
		CreatedAt:     createdAt,
		UpdatedAt:     updatedAt,
		DeletedAt:     deletedAt,
		TaskType:      taskType,
		Status:        status,
		WorkflowId:    workflowId,
		CleanedUp:     cleanedUp,
		OnWorker:      onWorker,
		RetryState:    retryState,
		Logs:          logs,
		RetrySettings: retrySettings,
		Input:         input,
		Output:        output,
		Metadata:      metadata,
	}
}
func newWorkflowEdgeTableImpl() *workflowEdgeTableImpl {
	fromId := &workflowEdgefromIdFieldImpl{column: newColumn[string, WorkflowEdgeField](fieldAliasImpl("from_id"))}
	toId := &workflowEdgetoIdFieldImpl{column: newColumn[string, WorkflowEdgeField](fieldAliasImpl("to_id"))}
	workflowId := &workflowEdgeworkflowIdFieldImpl{column: newColumn[string, WorkflowEdgeField](fieldAliasImpl("workflow_id"))}
	return &workflowEdgeTableImpl{
		table: newTable[WorkflowEdgeField, *WorkflowEdgeScanner](
			"workflow_edges",
			newWorkflowEdgeScanner,
			fromId,
			toId,
			workflowId,
		),
		FromId:     fromId,
		ToId:       toId,
		WorkflowId: workflowId,
	}
}

type (
	UserRepository                = ProtoRepository[UserField, *UserScanner, *panel.User]
	UserRepositoryOption          = ProtoCallOption[UserField, *UserScanner, *panel.User]
	RefreshTokensRepository       = ProtoRepository[RefreshTokensField, *RefreshTokensScanner, *panel.RefreshTokens]
	RefreshTokensRepositoryOption = ProtoCallOption[RefreshTokensField, *RefreshTokensScanner, *panel.RefreshTokens]
	KvinfoRepository              = ProtoRepository[KvinfoField, *KvinfoScanner, *panel.KVInfo]
	KvinfoRepositoryOption        = ProtoCallOption[KvinfoField, *KvinfoScanner, *panel.KVInfo]
	TemplateRepository            = ProtoRepository[TemplateField, *TemplateScanner, *panel.Template]
	TemplateRepositoryOption      = ProtoCallOption[TemplateField, *TemplateScanner, *panel.Template]
	RunRecordRepository           = ProtoRepository[RunRecordField, *RunRecordScanner, *panel.RunRecord]
	RunRecordRepositoryOption     = ProtoCallOption[RunRecordField, *RunRecordScanner, *panel.RunRecord]
	RunRecordStepRepository       = ProtoRepository[RunRecordStepField, *RunRecordStepScanner, *panel.RunRecordStep]
	RunRecordStepRepositoryOption = ProtoCallOption[RunRecordStepField, *RunRecordStepScanner, *panel.RunRecordStep]
	WorkflowRepository            = ProtoRepository[WorkflowField, *WorkflowScanner, *panel.Workflow]
	WorkflowRepositoryOption      = ProtoCallOption[WorkflowField, *WorkflowScanner, *panel.Workflow]
	WorkflowTaskRepository        = ProtoRepository[WorkflowTaskField, *WorkflowTaskScanner, *panel.WorkflowTask]
	WorkflowTaskRepositoryOption  = ProtoCallOption[WorkflowTaskField, *WorkflowTaskScanner, *panel.WorkflowTask]
	WorkflowEdgeRepository        = ProtoRepository[WorkflowEdgeField, *WorkflowEdgeScanner, *panel.WorkflowEdge]
	WorkflowEdgeRepositoryOption  = ProtoCallOption[WorkflowEdgeField, *WorkflowEdgeScanner, *panel.WorkflowEdge]
)
type (
	upcastUserOptions struct {
		PasswordHash string
	}
	upcastUserOption func(*upcastUserOptions)
)

func WithUserPasswordHash(value string) upcastUserOption {
	return func(options *upcastUserOptions) {
		options.PasswordHash = value
	}
}
func UserToScanner(
	downcastId TypeCaster[*panel.Ulid, string],
	opts ...upcastUserOption,
) TypeCaster[*panel.User, *UserScanner] {
	return func(entity *panel.User) *UserScanner {
		if entity == nil {
			return nil
		}
		scanner := &UserScanner{
			Id:    downcastId(entity.Id),
			Email: entity.Email,
			Admin: entity.Admin,
		}
		scanner.CreatedAt = TimestampToTime(entity.GetTiming().GetCreatedAt())
		scanner.UpdatedAt = TimestampToTime(entity.GetTiming().GetUpdatedAt())
		scanner.DeletedAt = TimestampToPtrTime(entity.GetTiming().GetDeletedAt())
		options := &upcastUserOptions{}
		for _, opt := range opts {
			opt(options)
		}
		scanner.PasswordHash = options.PasswordHash
		return scanner
	}
}
func ScannerToUser(
	upcastId TypeCaster[string, *panel.Ulid],
) TypeCaster[*UserScanner, *panel.User] {
	return func(model *UserScanner) *panel.User {
		if model == nil {
			return nil
		}
		entity := &panel.User{
			Id:    upcastId(model.Id),
			Email: model.Email,
			Admin: model.Admin,
		}
		entity.Timing = &panel.Timing{
			CreatedAt: TimestampFromTime(model.CreatedAt),
			UpdatedAt: TimestampFromTime(model.UpdatedAt),
			DeletedAt: TimestampFromPtrTime(model.DeletedAt),
		}

		return entity
	}
}
func NewUserRepository(
	dbGetter DbGetter,
	upcastId TypeCaster[string, *panel.Ulid],
	downcastId TypeCaster[*panel.Ulid, string],
	defaultOpts ...UserRepositoryOption,
) UserRepository {
	return newGenericRepository(
		newGenericScannerRepository(User.table, dbGetter),
		UserToScanner(downcastId),
		ScannerToUser(upcastId),
		defaultOpts...,
	)
}
func RefreshTokensToScanner(
	downcastUserId TypeCaster[*panel.Ulid, string],
) TypeCaster[*panel.RefreshTokens, *RefreshTokensScanner] {
	return func(entity *panel.RefreshTokens) *RefreshTokensScanner {
		if entity == nil {
			return nil
		}
		scanner := &RefreshTokensScanner{
			UserId: downcastUserId(entity.UserId),
			Token:  entity.Token,
		}
		return scanner
	}
}
func ScannerToRefreshTokens(
	upcastUserId TypeCaster[string, *panel.Ulid],
) TypeCaster[*RefreshTokensScanner, *panel.RefreshTokens] {
	return func(model *RefreshTokensScanner) *panel.RefreshTokens {
		if model == nil {
			return nil
		}
		entity := &panel.RefreshTokens{
			UserId: upcastUserId(model.UserId),
			Token:  model.Token,
		}

		return entity
	}
}
func NewRefreshTokensRepository(
	dbGetter DbGetter,
	upcastUserId TypeCaster[string, *panel.Ulid],
	downcastUserId TypeCaster[*panel.Ulid, string],
	defaultOpts ...RefreshTokensRepositoryOption,
) RefreshTokensRepository {
	return newGenericRepository(
		newGenericScannerRepository(RefreshTokens.table, dbGetter),
		RefreshTokensToScanner(downcastUserId),
		ScannerToRefreshTokens(upcastUserId),
		defaultOpts...,
	)
}
func KVInfoToScanner(
	downcastId TypeCaster[*panel.Ulid, string],
) TypeCaster[*panel.KVInfo, *KvinfoScanner] {
	return func(entity *panel.KVInfo) *KvinfoScanner {
		if entity == nil {
			return nil
		}
		scanner := &KvinfoScanner{
			Id:  downcastId(entity.Id),
			Key: entity.Key,
		}
		scanner.Description = entity.GetInfo().GetDescription()
		scanner.DefaultValue = entity.GetInfo().GetDefaultValue()
		scanner.IsRequired = entity.GetInfo().GetIsRequired()
		scanner.Immutable = entity.GetInfo().GetImmutable()
		scanner.SystemGenerated = entity.GetInfo().GetSystemGenerated()
		scanner.CreatedAt = TimestampToTime(entity.GetTiming().GetCreatedAt())
		scanner.UpdatedAt = TimestampToTime(entity.GetTiming().GetUpdatedAt())
		scanner.DeletedAt = TimestampToPtrTime(entity.GetTiming().GetDeletedAt())
		return scanner
	}
}
func ScannerToKVInfo(
	upcastId TypeCaster[string, *panel.Ulid],
) TypeCaster[*KvinfoScanner, *panel.KVInfo] {
	return func(model *KvinfoScanner) *panel.KVInfo {
		if model == nil {
			return nil
		}
		entity := &panel.KVInfo{
			Id:  upcastId(model.Id),
			Key: model.Key,
		}
		entity.Info = &panel.KV_Info{
			Description:     model.Description,
			DefaultValue:    model.DefaultValue,
			IsRequired:      model.IsRequired,
			Immutable:       model.Immutable,
			SystemGenerated: model.SystemGenerated,
		}
		entity.Timing = &panel.Timing{
			CreatedAt: TimestampFromTime(model.CreatedAt),
			UpdatedAt: TimestampFromTime(model.UpdatedAt),
			DeletedAt: TimestampFromPtrTime(model.DeletedAt),
		}

		return entity
	}
}
func NewKvinfoRepository(
	dbGetter DbGetter,
	upcastId TypeCaster[string, *panel.Ulid],
	downcastId TypeCaster[*panel.Ulid, string],
	defaultOpts ...KvinfoRepositoryOption,
) KvinfoRepository {
	return newGenericRepository(
		newGenericScannerRepository(Kvinfo.table, dbGetter),
		KVInfoToScanner(downcastId),
		ScannerToKVInfo(upcastId),
		defaultOpts...,
	)
}
func TemplateToScanner(
	downcastId TypeCaster[*panel.Ulid, string],
	downcastAuthorId TypeCaster[*panel.Ulid, string],
	downcastTags TypeCaster[[]*panel.Tag, []string],
) TypeCaster[*panel.Template, *TemplateScanner] {
	return func(entity *panel.Template) *TemplateScanner {
		if entity == nil {
			return nil
		}
		scanner := &TemplateScanner{
			Id:        downcastId(entity.Id),
			Name:      entity.Name,
			AuthorId:  downcastAuthorId(entity.AuthorId),
			IsDefault: entity.IsDefault,
			Tags:      downcastTags(entity.Tags),
		}
		scanner.CreatedAt = TimestampToTime(entity.GetTiming().GetCreatedAt())
		scanner.UpdatedAt = TimestampToTime(entity.GetTiming().GetUpdatedAt())
		scanner.DeletedAt = TimestampToPtrTime(entity.GetTiming().GetDeletedAt())
		return scanner
	}
}
func ScannerToTemplate(
	upcastId TypeCaster[string, *panel.Ulid],
	upcastAuthorId TypeCaster[string, *panel.Ulid],
	upcastTags TypeCaster[[]string, []*panel.Tag],
) TypeCaster[*TemplateScanner, *panel.Template] {
	return func(model *TemplateScanner) *panel.Template {
		if model == nil {
			return nil
		}
		entity := &panel.Template{
			Id:        upcastId(model.Id),
			Name:      model.Name,
			AuthorId:  upcastAuthorId(model.AuthorId),
			IsDefault: model.IsDefault,
			Tags:      upcastTags(model.Tags),
		}
		entity.Timing = &panel.Timing{
			CreatedAt: TimestampFromTime(model.CreatedAt),
			UpdatedAt: TimestampFromTime(model.UpdatedAt),
			DeletedAt: TimestampFromPtrTime(model.DeletedAt),
		}

		return entity
	}
}
func NewTemplateRepository(
	dbGetter DbGetter,
	upcastId TypeCaster[string, *panel.Ulid],
	downcastId TypeCaster[*panel.Ulid, string],
	upcastAuthorId TypeCaster[string, *panel.Ulid],
	downcastAuthorId TypeCaster[*panel.Ulid, string],
	upcastTags TypeCaster[[]string, []*panel.Tag],
	downcastTags TypeCaster[[]*panel.Tag, []string],
	defaultOpts ...TemplateRepositoryOption,
) TemplateRepository {
	return newGenericRepository(
		newGenericScannerRepository(Template.table, dbGetter),
		TemplateToScanner(downcastId, downcastAuthorId, downcastTags),
		ScannerToTemplate(upcastId, upcastAuthorId, upcastTags),
		defaultOpts...,
	)
}
func RunRecordToScanner(
	downcastId TypeCaster[*panel.Ulid, string],
	downcastAuthorId TypeCaster[*panel.Ulid, string],
	downcastWorkflowId TypeCaster[*panel.Ulid, *string],
) TypeCaster[*panel.RunRecord, *RunRecordScanner] {
	return func(entity *panel.RunRecord) *RunRecordScanner {
		if entity == nil {
			return nil
		}
		scanner := &RunRecordScanner{
			Id:                  downcastId(entity.Id),
			AuthorId:            downcastAuthorId(entity.AuthorId),
			Status:              EnumToInt32[stroppy.Status](entity.Status),
			RunInfo:             MessageToSliceByte[*stroppy.StroppyRun](entity.RunInfo),
			Tps:                 MessageToSliceByte[*panel.Tps](entity.Tps),
			GrafanaDashboardUrl: entity.GrafanaDashboardUrl,
			WorkflowId:          downcastWorkflowId(entity.WorkflowId),
			CloudRunParams:      MessageToJsonb[*panel.CloudRunParams](entity.CloudRunParams),
		}
		scanner.CreatedAt = TimestampToTime(entity.GetTiming().GetCreatedAt())
		scanner.UpdatedAt = TimestampToTime(entity.GetTiming().GetUpdatedAt())
		scanner.DeletedAt = TimestampToPtrTime(entity.GetTiming().GetDeletedAt())
		return scanner
	}
}
func ScannerToRunRecord(
	upcastId TypeCaster[string, *panel.Ulid],
	upcastAuthorId TypeCaster[string, *panel.Ulid],
	upcastWorkflowId TypeCaster[*string, *panel.Ulid],
) TypeCaster[*RunRecordScanner, *panel.RunRecord] {
	return func(model *RunRecordScanner) *panel.RunRecord {
		if model == nil {
			return nil
		}
		entity := &panel.RunRecord{
			Id:                  upcastId(model.Id),
			AuthorId:            upcastAuthorId(model.AuthorId),
			Status:              EnumFromInt32[stroppy.Status](model.Status),
			RunInfo:             MessageFromSliceByte[*stroppy.StroppyRun](model.RunInfo),
			Tps:                 MessageFromSliceByte[*panel.Tps](model.Tps),
			GrafanaDashboardUrl: model.GrafanaDashboardUrl,
			WorkflowId:          upcastWorkflowId(model.WorkflowId),
			CloudRunParams:      MessageFromJsonb[*panel.CloudRunParams](model.CloudRunParams),
		}
		entity.Timing = &panel.Timing{
			CreatedAt: TimestampFromTime(model.CreatedAt),
			UpdatedAt: TimestampFromTime(model.UpdatedAt),
			DeletedAt: TimestampFromPtrTime(model.DeletedAt),
		}

		return entity
	}
}
func NewRunRecordRepository(
	dbGetter DbGetter,
	upcastId TypeCaster[string, *panel.Ulid],
	downcastId TypeCaster[*panel.Ulid, string],
	upcastAuthorId TypeCaster[string, *panel.Ulid],
	downcastAuthorId TypeCaster[*panel.Ulid, string],
	upcastWorkflowId TypeCaster[*string, *panel.Ulid],
	downcastWorkflowId TypeCaster[*panel.Ulid, *string],
	defaultOpts ...RunRecordRepositoryOption,
) RunRecordRepository {
	return newGenericRepository(
		newGenericScannerRepository(RunRecord.table, dbGetter),
		RunRecordToScanner(downcastId, downcastAuthorId, downcastWorkflowId),
		ScannerToRunRecord(upcastId, upcastAuthorId, upcastWorkflowId),
		defaultOpts...,
	)
}
func RunRecordStepToScanner(
	downcastId TypeCaster[*panel.Ulid, string],
	downcastRunId TypeCaster[*panel.Ulid, string],
) TypeCaster[*panel.RunRecordStep, *RunRecordStepScanner] {
	return func(entity *panel.RunRecordStep) *RunRecordStepScanner {
		if entity == nil {
			return nil
		}
		scanner := &RunRecordStepScanner{
			Id:       downcastId(entity.Id),
			RunId:    downcastRunId(entity.RunId),
			Status:   EnumToInt32[stroppy.Status](entity.Status),
			StepInfo: MessageToSliceByte[*stroppy.StroppyStepRun](entity.StepInfo),
		}
		scanner.CreatedAt = TimestampToTime(entity.GetTiming().GetCreatedAt())
		scanner.UpdatedAt = TimestampToTime(entity.GetTiming().GetUpdatedAt())
		scanner.DeletedAt = TimestampToPtrTime(entity.GetTiming().GetDeletedAt())
		return scanner
	}
}
func ScannerToRunRecordStep(
	upcastId TypeCaster[string, *panel.Ulid],
	upcastRunId TypeCaster[string, *panel.Ulid],
) TypeCaster[*RunRecordStepScanner, *panel.RunRecordStep] {
	return func(model *RunRecordStepScanner) *panel.RunRecordStep {
		if model == nil {
			return nil
		}
		entity := &panel.RunRecordStep{
			Id:       upcastId(model.Id),
			RunId:    upcastRunId(model.RunId),
			Status:   EnumFromInt32[stroppy.Status](model.Status),
			StepInfo: MessageFromSliceByte[*stroppy.StroppyStepRun](model.StepInfo),
		}
		entity.Timing = &panel.Timing{
			CreatedAt: TimestampFromTime(model.CreatedAt),
			UpdatedAt: TimestampFromTime(model.UpdatedAt),
			DeletedAt: TimestampFromPtrTime(model.DeletedAt),
		}

		return entity
	}
}
func NewRunRecordStepRepository(
	dbGetter DbGetter,
	upcastId TypeCaster[string, *panel.Ulid],
	downcastId TypeCaster[*panel.Ulid, string],
	upcastRunId TypeCaster[string, *panel.Ulid],
	downcastRunId TypeCaster[*panel.Ulid, string],
	defaultOpts ...RunRecordStepRepositoryOption,
) RunRecordStepRepository {
	return newGenericRepository(
		newGenericScannerRepository(RunRecordStep.table, dbGetter),
		RunRecordStepToScanner(downcastId, downcastRunId),
		ScannerToRunRecordStep(upcastId, upcastRunId),
		defaultOpts...,
	)
}
func WorkflowToScanner(
	downcastId TypeCaster[*panel.Ulid, string],
) TypeCaster[*panel.Workflow, *WorkflowScanner] {
	return func(entity *panel.Workflow) *WorkflowScanner {
		if entity == nil {
			return nil
		}
		scanner := &WorkflowScanner{
			Id: downcastId(entity.Id),
		}
		scanner.CreatedAt = TimestampToTime(entity.GetTiming().GetCreatedAt())
		scanner.UpdatedAt = TimestampToTime(entity.GetTiming().GetUpdatedAt())
		scanner.DeletedAt = TimestampToPtrTime(entity.GetTiming().GetDeletedAt())
		return scanner
	}
}
func ScannerToWorkflow(
	upcastId TypeCaster[string, *panel.Ulid],
) TypeCaster[*WorkflowScanner, *panel.Workflow] {
	return func(model *WorkflowScanner) *panel.Workflow {
		if model == nil {
			return nil
		}
		entity := &panel.Workflow{
			Id: upcastId(model.Id),
		}
		entity.Timing = &panel.Timing{
			CreatedAt: TimestampFromTime(model.CreatedAt),
			UpdatedAt: TimestampFromTime(model.UpdatedAt),
			DeletedAt: TimestampFromPtrTime(model.DeletedAt),
		}

		return entity
	}
}
func NewWorkflowRepository(
	dbGetter DbGetter,
	upcastId TypeCaster[string, *panel.Ulid],
	downcastId TypeCaster[*panel.Ulid, string],
	defaultOpts ...WorkflowRepositoryOption,
) WorkflowRepository {
	return newGenericRepository(
		newGenericScannerRepository(Workflow.table, dbGetter),
		WorkflowToScanner(downcastId),
		ScannerToWorkflow(upcastId),
		defaultOpts...,
	)
}
func WorkflowTaskToScanner() TypeCaster[*panel.WorkflowTask, *WorkflowTaskScanner] {
	return func(entity *panel.WorkflowTask) *WorkflowTaskScanner {
		if entity == nil {
			return nil
		}
		scanner := &WorkflowTaskScanner{
			Id:            entity.Id,
			TaskType:      EnumToInt32[panel.WorkflowTask_Type](entity.TaskType),
			Status:        EnumToInt32[panel.WorkflowTask_Status](entity.Status),
			WorkflowId:    entity.WorkflowId,
			CleanedUp:     entity.CleanedUp,
			OnWorker:      entity.OnWorker,
			RetryState:    MessageToSliceByte[*panel.Retry_State](entity.RetryState),
			Logs:          MessageToSliceByteSlice[*panel.LogRecord](entity.Logs),
			RetrySettings: MessageToSliceByte[*panel.Retry](entity.RetrySettings),
			Input:         MessageToSliceByte[*anypb.Any](entity.Input),
			Output:        MessageToSliceByte[*anypb.Any](entity.Output),
			Metadata:      MessageToSliceByte[*panel.Metadata](entity.Metadata),
		}
		scanner.CreatedAt = TimestampToTime(entity.GetTiming().GetCreatedAt())
		scanner.UpdatedAt = TimestampToTime(entity.GetTiming().GetUpdatedAt())
		scanner.DeletedAt = TimestampToPtrTime(entity.GetTiming().GetDeletedAt())
		return scanner
	}
}
func ScannerToWorkflowTask() TypeCaster[*WorkflowTaskScanner, *panel.WorkflowTask] {
	return func(model *WorkflowTaskScanner) *panel.WorkflowTask {
		if model == nil {
			return nil
		}
		entity := &panel.WorkflowTask{
			Id:            model.Id,
			TaskType:      EnumFromInt32[panel.WorkflowTask_Type](model.TaskType),
			Status:        EnumFromInt32[panel.WorkflowTask_Status](model.Status),
			WorkflowId:    model.WorkflowId,
			CleanedUp:     model.CleanedUp,
			OnWorker:      model.OnWorker,
			RetryState:    MessageFromSliceByte[*panel.Retry_State](model.RetryState),
			Logs:          MessageFromSliceByteSlice[*panel.LogRecord](model.Logs),
			RetrySettings: MessageFromSliceByte[*panel.Retry](model.RetrySettings),
			Input:         MessageFromSliceByte[*anypb.Any](model.Input),
			Output:        MessageFromSliceByte[*anypb.Any](model.Output),
			Metadata:      MessageFromSliceByte[*panel.Metadata](model.Metadata),
		}
		entity.Timing = &panel.Timing{
			CreatedAt: TimestampFromTime(model.CreatedAt),
			UpdatedAt: TimestampFromTime(model.UpdatedAt),
			DeletedAt: TimestampFromPtrTime(model.DeletedAt),
		}

		return entity
	}
}
func NewWorkflowTaskRepository(
	dbGetter DbGetter,
	defaultOpts ...WorkflowTaskRepositoryOption,
) WorkflowTaskRepository {
	return newGenericRepository(
		newGenericScannerRepository(WorkflowTask.table, dbGetter),
		WorkflowTaskToScanner(),
		ScannerToWorkflowTask(),
		defaultOpts...,
	)
}

type (
	upcastWorkflowEdgeOptions struct {
		WorkflowId string
	}
	upcastWorkflowEdgeOption func(*upcastWorkflowEdgeOptions)
)

func WithWorkflowEdgeWorkflowId(value string) upcastWorkflowEdgeOption {
	return func(options *upcastWorkflowEdgeOptions) {
		options.WorkflowId = value
	}
}
func WorkflowEdgeToScanner(
	downcastId TypeCaster[*panel.Ulid, string],
	opts ...upcastWorkflowEdgeOption,
) TypeCaster[*panel.WorkflowEdge, *WorkflowEdgeScanner] {
	return func(entity *panel.WorkflowEdge) *WorkflowEdgeScanner {
		if entity == nil {
			return nil
		}
		scanner := &WorkflowEdgeScanner{
			FromId: entity.FromId,
			ToId:   entity.ToId,
		}
		options := &upcastWorkflowEdgeOptions{}
		for _, opt := range opts {
			opt(options)
		}
		scanner.WorkflowId = options.WorkflowId
		return scanner
	}
}
func ScannerToWorkflowEdge(
	upcastId TypeCaster[string, *panel.Ulid],
) TypeCaster[*WorkflowEdgeScanner, *panel.WorkflowEdge] {
	return func(model *WorkflowEdgeScanner) *panel.WorkflowEdge {
		if model == nil {
			return nil
		}
		entity := &panel.WorkflowEdge{
			FromId: model.FromId,
			ToId:   model.ToId,
		}

		return entity
	}
}
func NewWorkflowEdgeRepository(
	dbGetter DbGetter,
	upcastId TypeCaster[string, *panel.Ulid],
	downcastId TypeCaster[*panel.Ulid, string],
	defaultOpts ...WorkflowEdgeRepositoryOption,
) WorkflowEdgeRepository {
	return newGenericRepository(
		newGenericScannerRepository(WorkflowEdge.table, dbGetter),
		WorkflowEdgeToScanner(downcastId),
		ScannerToWorkflowEdge(upcastId),
		defaultOpts...,
	)
}
