// @generated by protoc-gen-es v2.10.1 with parameter "json_types=true,valid_types=legacy_required+protovalidate_required,target=ts,import_extension=ts"
// @generated from file crossplane/deployment.proto (package crossplane, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ResourceDag, ResourceDagJson } from "./resource_pb.ts";
import { file_crossplane_resource } from "./resource_pb.ts";
import type { SupportedCloud, SupportedCloudJson } from "./types_pb.ts";
import { file_crossplane_types } from "./types_pb.ts";
import type { YandexCloud_VmStrategy, YandexCloud_VmStrategyJson } from "./yandex_pb.ts";
import { file_crossplane_yandex } from "./yandex_pb.ts";
import { file_validate_validate } from "../validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file crossplane/deployment.proto.
 */
export const file_crossplane_deployment: GenFile = /*@__PURE__*/
  fileDesc("Chtjcm9zc3BsYW5lL2RlcGxveW1lbnQucHJvdG8SCmNyb3NzcGxhbmUiOgoLTWFjaGluZUluZm8SDQoFY29yZXMYASABKA0SDgoGbWVtb3J5GAIgASgNEgwKBGRpc2sYAyABKA0ikAQKCkRlcGxveW1lbnQSEwoCaWQYASABKAlCB/pCBHICEAESPQoPc3VwcG9ydGVkX2Nsb3VkGAIgASgOMhouY3Jvc3NwbGFuZS5TdXBwb3J0ZWRDbG91ZEII+kIFggECEAESNwoMcmVzb3VyY2VfZGFnGAMgASgLMhcuY3Jvc3NwbGFuZS5SZXNvdXJjZURhZ0II+kIFigECEAESMQoCdm0YZCABKAsyGS5jcm9zc3BsYW5lLkRlcGxveW1lbnQuVm1CCPpCBYoBAhABSAASOwoHY2x1c3RlchhlIAEoCzIeLmNyb3NzcGxhbmUuRGVwbG95bWVudC5DbHVzdGVyQgj6QgWKAQIQAUgAGrkBCgJWbRITCgtpbnRlcm5hbF9pcBgEIAEoCRIRCglwdWJsaWNfaXAYBSABKAgSNwoMbWFjaGluZV9pbmZvGAEgASgLMhcuY3Jvc3NwbGFuZS5NYWNoaW5lSW5mb0II+kIFigECEAESRgoYeWFuZGV4X2Nsb3VkX3ZtX3N0cmF0ZWd5GGQgASgLMiIuY3Jvc3NwbGFuZS5ZYW5kZXhDbG91ZC5WbVN0cmF0ZWd5SABCCgoIc3RyYXRlZ3kaOwoHQ2x1c3RlchIwCgN2bXMYAiADKAsyGS5jcm9zc3BsYW5lLkRlcGxveW1lbnQuVm1CCPpCBZIBAggBQgwKCmRlcGxveW1lbnRCQFo+Z2l0aHViLmNvbS9zdHJvcHB5LWlvL3N0cm9wcHktY2xvdWQtcGFuZWwvaW50ZXJuYWwvcHJvdG8vcGFuZWxiBnByb3RvMw", [file_crossplane_resource, file_crossplane_types, file_crossplane_yandex, file_validate_validate]);

/**
 * @generated from message crossplane.MachineInfo
 */
export type MachineInfo = Message<"crossplane.MachineInfo"> & {
  /**
   * in cores
   *
   * @generated from field: uint32 cores = 1;
   */
  cores: number;

  /**
   * in GB
   *
   * @generated from field: uint32 memory = 2;
   */
  memory: number;

  /**
   * in GB
   *
   * @generated from field: uint32 disk = 3;
   */
  disk: number;
};

/**
 * @generated from message crossplane.MachineInfo
 */
export type MachineInfoJson = {
  /**
   * in cores
   *
   * @generated from field: uint32 cores = 1;
   */
  cores?: number;

  /**
   * in GB
   *
   * @generated from field: uint32 memory = 2;
   */
  memory?: number;

  /**
   * in GB
   *
   * @generated from field: uint32 disk = 3;
   */
  disk?: number;
};

export type MachineInfoValid = MachineInfo;

/**
 * Describes the message crossplane.MachineInfo.
 * Use `create(MachineInfoSchema)` to create a new message.
 */
export const MachineInfoSchema: GenMessage<MachineInfo, {jsonType: MachineInfoJson, validType: MachineInfoValid}> = /*@__PURE__*/
  messageDesc(file_crossplane_deployment, 0);

/**
 * @generated from message crossplane.Deployment
 */
export type Deployment = Message<"crossplane.Deployment"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: crossplane.SupportedCloud supported_cloud = 2;
   */
  supportedCloud: SupportedCloud;

  /**
   * @generated from field: crossplane.ResourceDag resource_dag = 3;
   */
  resourceDag?: ResourceDag;

  /**
   * @generated from oneof crossplane.Deployment.deployment
   */
  deployment: {
    /**
     * @generated from field: crossplane.Deployment.Vm vm = 100;
     */
    value: Deployment_Vm;
    case: "vm";
  } | {
    /**
     * @generated from field: crossplane.Deployment.Cluster cluster = 101;
     */
    value: Deployment_Cluster;
    case: "cluster";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message crossplane.Deployment
 */
export type DeploymentJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: crossplane.SupportedCloud supported_cloud = 2;
   */
  supportedCloud?: SupportedCloudJson;

  /**
   * @generated from field: crossplane.ResourceDag resource_dag = 3;
   */
  resourceDag?: ResourceDagJson;

  /**
   * @generated from field: crossplane.Deployment.Vm vm = 100;
   */
  vm?: Deployment_VmJson;

  /**
   * @generated from field: crossplane.Deployment.Cluster cluster = 101;
   */
  cluster?: Deployment_ClusterJson;
};

export type DeploymentValid = Deployment;

/**
 * Describes the message crossplane.Deployment.
 * Use `create(DeploymentSchema)` to create a new message.
 */
export const DeploymentSchema: GenMessage<Deployment, {jsonType: DeploymentJson, validType: DeploymentValid}> = /*@__PURE__*/
  messageDesc(file_crossplane_deployment, 1);

/**
 * @generated from message crossplane.Deployment.Vm
 */
export type Deployment_Vm = Message<"crossplane.Deployment.Vm"> & {
  /**
   * @generated from field: string internal_ip = 4;
   */
  internalIp: string;

  /**
   * @generated from field: bool public_ip = 5;
   */
  publicIp: boolean;

  /**
   * @generated from field: crossplane.MachineInfo machine_info = 1;
   */
  machineInfo?: MachineInfo;

  /**
   * @generated from oneof crossplane.Deployment.Vm.strategy
   */
  strategy: {
    /**
     * @generated from field: crossplane.YandexCloud.VmStrategy yandex_cloud_vm_strategy = 100;
     */
    value: YandexCloud_VmStrategy;
    case: "yandexCloudVmStrategy";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message crossplane.Deployment.Vm
 */
export type Deployment_VmJson = {
  /**
   * @generated from field: string internal_ip = 4;
   */
  internalIp?: string;

  /**
   * @generated from field: bool public_ip = 5;
   */
  publicIp?: boolean;

  /**
   * @generated from field: crossplane.MachineInfo machine_info = 1;
   */
  machineInfo?: MachineInfoJson;

  /**
   * @generated from field: crossplane.YandexCloud.VmStrategy yandex_cloud_vm_strategy = 100;
   */
  yandexCloudVmStrategy?: YandexCloud_VmStrategyJson;
};

export type Deployment_VmValid = Deployment_Vm;

/**
 * Describes the message crossplane.Deployment.Vm.
 * Use `create(Deployment_VmSchema)` to create a new message.
 */
export const Deployment_VmSchema: GenMessage<Deployment_Vm, {jsonType: Deployment_VmJson, validType: Deployment_VmValid}> = /*@__PURE__*/
  messageDesc(file_crossplane_deployment, 1, 0);

/**
 * @generated from message crossplane.Deployment.Cluster
 */
export type Deployment_Cluster = Message<"crossplane.Deployment.Cluster"> & {
  /**
   * @generated from field: repeated crossplane.Deployment.Vm vms = 2;
   */
  vms: Deployment_Vm[];
};

/**
 * @generated from message crossplane.Deployment.Cluster
 */
export type Deployment_ClusterJson = {
  /**
   * @generated from field: repeated crossplane.Deployment.Vm vms = 2;
   */
  vms?: Deployment_VmJson[];
};

export type Deployment_ClusterValid = Deployment_Cluster;

/**
 * Describes the message crossplane.Deployment.Cluster.
 * Use `create(Deployment_ClusterSchema)` to create a new message.
 */
export const Deployment_ClusterSchema: GenMessage<Deployment_Cluster, {jsonType: Deployment_ClusterJson, validType: Deployment_ClusterValid}> = /*@__PURE__*/
  messageDesc(file_crossplane_deployment, 1, 1);

