// @generated by protoc-gen-es v2.10.0 with parameter "valid_types=legacy_required+protovalidate_required,target=ts,import_extension=ts,json_types=true"
// @generated from file crossplane/resource.proto (package crossplane, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata, MetadataJson, Ref, RefJson } from "./types_pb.ts";
import { file_crossplane_types } from "./types_pb.ts";
import type { YandexCloud_Network, YandexCloud_NetworkJson, YandexCloud_Subnet, YandexCloud_SubnetJson, YandexCloud_Vm, YandexCloud_VmJson } from "./yandex_pb.ts";
import { file_crossplane_yandex } from "./yandex_pb.ts";
import { file_protopgx_pgx } from "../protopgx/pgx_pb.ts";
import { file_validate_validate } from "../validate/validate_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file crossplane/resource.proto.
 */
export const file_crossplane_resource: GenFile = /*@__PURE__*/
  fileDesc("Chljcm9zc3BsYW5lL3Jlc291cmNlLnByb3RvEgpjcm9zc3BsYW5lIs0FCgtSZXNvdXJjZURlZhIdCgthcGlfdmVyc2lvbhgCIAEoCUII+kIFigECEAESFgoEa2luZBgBIAEoCUII+kIFigECEAESJgoIbWV0YWRhdGEYAyABKAsyFC5jcm9zc3BsYW5lLk1ldGFkYXRhEjQKBHNwZWMYBCABKAsyHC5jcm9zc3BsYW5lLlJlc291cmNlRGVmLlNwZWNCCPpCBYoBAhABGqgECgRTcGVjEkEKHndyaXRlX2Nvbm5lY3Rpb25fc2VjcmV0X3RvX3JlZhgBIAEoCzIPLmNyb3NzcGxhbmUuUmVmQgj6QgWKAQIQARIhCg9kZWxldGlvbl9wb2xpY3kYAiABKAlCCPpCBYIBAhABElAKE3Byb3ZpZGVyX2NvbmZpZ19yZWYYAyADKAsyMy5jcm9zc3BsYW5lLlJlc291cmNlRGVmLlNwZWMuUHJvdmlkZXJDb25maWdSZWZFbnRyeRI/Cg95YW5kZXhfY2xvdWRfdm0YZCABKAsyGi5jcm9zc3BsYW5lLllhbmRleENsb3VkLlZtQgj6QgWKAQIQAUgAEkkKFHlhbmRleF9jbG91ZF9uZXR3b3JrGGUgASgLMh8uY3Jvc3NwbGFuZS5ZYW5kZXhDbG91ZC5OZXR3b3JrQgj6QgWKAQIQAUgAEkcKE3lhbmRleF9jbG91ZF9zdWJuZXQYZiABKAsyHi5jcm9zc3BsYW5lLllhbmRleENsb3VkLlN1Ym5ldEII+kIFigECEAFIABo4ChZQcm92aWRlckNvbmZpZ1JlZkVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiSQoORGVsZXRpb25Qb2xpY3kSHwobREVMRVRJT05fUE9MSUNZX1VOU1BFQ0lGSUVEEAASCgoGREVMRVRFEAESCgoGT1JQSEFOEAJCDgoMZm9yX3Byb3ZpZGVyItMBChJSZXNvdXJjZVdpdGhTdGF0dXMSKwoDcmVmGAEgASgLMg8uY3Jvc3NwbGFuZS5SZWZCDco+AkgB+kIFigECEAESPAoMcmVzb3VyY2VfZGVmGAIgASgLMhcuY3Jvc3NwbGFuZS5SZXNvdXJjZURlZkINyj4CSAH6QgWKAQIQARIeCg1yZXNvdXJjZV95YW1sGAMgASgJQgf6QgRyAhABEg4KBnN5bmNlZBgEIAEoCBINCgVyZWFkeRgFIAEoCBITCgtleHRlcm5hbF9pZBgGIAEoCUJFWkNnaXRodWIuY29tL3N0cm9wcHktaW8vc3Ryb3BweS1jbG91ZC1wYW5lbC9pbnRlcm5hbC9wcm90by9jcm9zc3BsYW5lYgZwcm90bzM", [file_crossplane_types, file_crossplane_yandex, file_protopgx_pgx, file_validate_validate]);

/**
 * @generated from message crossplane.ResourceDef
 */
export type ResourceDef = Message<"crossplane.ResourceDef"> & {
  /**
   * @generated from field: string api_version = 2;
   */
  apiVersion: string;

  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: crossplane.Metadata metadata = 3;
   */
  metadata?: Metadata;

  /**
   * @generated from field: crossplane.ResourceDef.Spec spec = 4;
   */
  spec?: ResourceDef_Spec;
};

/**
 * @generated from message crossplane.ResourceDef
 */
export type ResourceDefJson = {
  /**
   * @generated from field: string api_version = 2;
   */
  apiVersion?: string;

  /**
   * @generated from field: string kind = 1;
   */
  kind?: string;

  /**
   * @generated from field: crossplane.Metadata metadata = 3;
   */
  metadata?: MetadataJson;

  /**
   * @generated from field: crossplane.ResourceDef.Spec spec = 4;
   */
  spec?: ResourceDef_SpecJson;
};

export type ResourceDefValid = ResourceDef;

/**
 * Describes the message crossplane.ResourceDef.
 * Use `create(ResourceDefSchema)` to create a new message.
 */
export const ResourceDefSchema: GenMessage<ResourceDef, {jsonType: ResourceDefJson, validType: ResourceDefValid}> = /*@__PURE__*/
  messageDesc(file_crossplane_resource, 0);

/**
 * @generated from message crossplane.ResourceDef.Spec
 */
export type ResourceDef_Spec = Message<"crossplane.ResourceDef.Spec"> & {
  /**
   * @generated from field: crossplane.Ref write_connection_secret_to_ref = 1;
   */
  writeConnectionSecretToRef?: Ref;

  /**
   * converted from DeletionPolicy
   *
   * @generated from field: string deletion_policy = 2;
   */
  deletionPolicy: string;

  /**
   * @generated from field: map<string, string> provider_config_ref = 3;
   */
  providerConfigRef: { [key: string]: string };

  /**
   * @generated from oneof crossplane.ResourceDef.Spec.for_provider
   */
  forProvider: {
    /**
     * @generated from field: crossplane.YandexCloud.Vm yandex_cloud_vm = 100;
     */
    value: YandexCloud_Vm;
    case: "yandexCloudVm";
  } | {
    /**
     * @generated from field: crossplane.YandexCloud.Network yandex_cloud_network = 101;
     */
    value: YandexCloud_Network;
    case: "yandexCloudNetwork";
  } | {
    /**
     * @generated from field: crossplane.YandexCloud.Subnet yandex_cloud_subnet = 102;
     */
    value: YandexCloud_Subnet;
    case: "yandexCloudSubnet";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message crossplane.ResourceDef.Spec
 */
export type ResourceDef_SpecJson = {
  /**
   * @generated from field: crossplane.Ref write_connection_secret_to_ref = 1;
   */
  writeConnectionSecretToRef?: RefJson;

  /**
   * converted from DeletionPolicy
   *
   * @generated from field: string deletion_policy = 2;
   */
  deletionPolicy?: string;

  /**
   * @generated from field: map<string, string> provider_config_ref = 3;
   */
  providerConfigRef?: { [key: string]: string };

  /**
   * @generated from field: crossplane.YandexCloud.Vm yandex_cloud_vm = 100;
   */
  yandexCloudVm?: YandexCloud_VmJson;

  /**
   * @generated from field: crossplane.YandexCloud.Network yandex_cloud_network = 101;
   */
  yandexCloudNetwork?: YandexCloud_NetworkJson;

  /**
   * @generated from field: crossplane.YandexCloud.Subnet yandex_cloud_subnet = 102;
   */
  yandexCloudSubnet?: YandexCloud_SubnetJson;
};

export type ResourceDef_SpecValid = ResourceDef_Spec;

/**
 * Describes the message crossplane.ResourceDef.Spec.
 * Use `create(ResourceDef_SpecSchema)` to create a new message.
 */
export const ResourceDef_SpecSchema: GenMessage<ResourceDef_Spec, {jsonType: ResourceDef_SpecJson, validType: ResourceDef_SpecValid}> = /*@__PURE__*/
  messageDesc(file_crossplane_resource, 0, 0);

/**
 * @generated from enum crossplane.ResourceDef.Spec.DeletionPolicy
 */
export enum ResourceDef_Spec_DeletionPolicy {
  /**
   * @generated from enum value: DELETION_POLICY_UNSPECIFIED = 0;
   */
  DELETION_POLICY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: DELETE = 1;
   */
  DELETE = 1,

  /**
   * @generated from enum value: ORPHAN = 2;
   */
  ORPHAN = 2,
}

/**
 * @generated from enum crossplane.ResourceDef.Spec.DeletionPolicy
 */
export type ResourceDef_Spec_DeletionPolicyJson = "DELETION_POLICY_UNSPECIFIED" | "DELETE" | "ORPHAN";

/**
 * Describes the enum crossplane.ResourceDef.Spec.DeletionPolicy.
 */
export const ResourceDef_Spec_DeletionPolicySchema: GenEnum<ResourceDef_Spec_DeletionPolicy, ResourceDef_Spec_DeletionPolicyJson> = /*@__PURE__*/
  enumDesc(file_crossplane_resource, 0, 0, 0);

/**
 * @generated from message crossplane.ResourceWithStatus
 */
export type ResourceWithStatus = Message<"crossplane.ResourceWithStatus"> & {
  /**
   * @generated from field: crossplane.Ref ref = 1;
   */
  ref?: Ref;

  /**
   * @generated from field: crossplane.ResourceDef resource_def = 2;
   */
  resourceDef?: ResourceDef;

  /**
   * @generated from field: string resource_yaml = 3;
   */
  resourceYaml: string;

  /**
   * @generated from field: bool synced = 4;
   */
  synced: boolean;

  /**
   * @generated from field: bool ready = 5;
   */
  ready: boolean;

  /**
   *    map<string, string> additional_fields = 8 [(sql.sql_field).serialized_message = true]; // leave here for future use
   *
   * @generated from field: string external_id = 6;
   */
  externalId: string;
};

/**
 * @generated from message crossplane.ResourceWithStatus
 */
export type ResourceWithStatusJson = {
  /**
   * @generated from field: crossplane.Ref ref = 1;
   */
  ref?: RefJson;

  /**
   * @generated from field: crossplane.ResourceDef resource_def = 2;
   */
  resourceDef?: ResourceDefJson;

  /**
   * @generated from field: string resource_yaml = 3;
   */
  resourceYaml?: string;

  /**
   * @generated from field: bool synced = 4;
   */
  synced?: boolean;

  /**
   * @generated from field: bool ready = 5;
   */
  ready?: boolean;

  /**
   *    map<string, string> additional_fields = 8 [(sql.sql_field).serialized_message = true]; // leave here for future use
   *
   * @generated from field: string external_id = 6;
   */
  externalId?: string;
};

export type ResourceWithStatusValid = ResourceWithStatus;

/**
 * Describes the message crossplane.ResourceWithStatus.
 * Use `create(ResourceWithStatusSchema)` to create a new message.
 */
export const ResourceWithStatusSchema: GenMessage<ResourceWithStatus, {jsonType: ResourceWithStatusJson, validType: ResourceWithStatusValid}> = /*@__PURE__*/
  messageDesc(file_crossplane_resource, 1);

