package main

import (
	"encoding/json"
	"reflect"
	"strings"
	"testing"
)

// sampleBasic — minimal pipe-separated answer with a header and two rows.
const sampleBasic = `l_returnflag|l_linestatus|sum_qty
A|F|37734107.00
N|F|991417.00
R|F|37719753.00
`

// samplePreamble — header preceded by a few lines of noise (as emitted
// by some dbms answer dumps) plus a trailing "(3 rows)" footer that
// must be dropped.
const samplePreamble = `# generated by some_tool v1.2.3
 query id: 7
-----+-----+-----
c_custkey|c_name|revenue
1|Customer#000000001|1234.56
2|Customer#000000002|2345.67
3|Customer#000000003|3456.78
(3 rows)
`

// sampleTrailingBlanks — extra trailing blank lines are fine.
const sampleTrailingBlanks = `a|b
1|2



`

func TestParseAnswerFile_Basic(t *testing.T) {
	a, err := parseAnswerFile(strings.NewReader(sampleBasic))
	if err != nil {
		t.Fatalf("parseAnswerFile: %v", err)
	}

	want := &answer{
		Columns: []string{"l_returnflag", "l_linestatus", "sum_qty"},
		Rows: [][]string{
			{"A", "F", "37734107.00"},
			{"N", "F", "991417.00"},
			{"R", "F", "37719753.00"},
		},
	}
	if !reflect.DeepEqual(a, want) {
		t.Errorf("got %+v\nwant %+v", a, want)
	}
}

func TestParseAnswerFile_PreambleAndFooter(t *testing.T) {
	a, err := parseAnswerFile(strings.NewReader(samplePreamble))
	if err != nil {
		t.Fatalf("parseAnswerFile: %v", err)
	}

	if !reflect.DeepEqual(a.Columns, []string{"c_custkey", "c_name", "revenue"}) {
		t.Errorf("columns: %v", a.Columns)
	}

	if len(a.Rows) != 3 {
		t.Fatalf("rows: got %d, want 3", len(a.Rows))
	}

	if a.Rows[2][1] != "Customer#000000003" {
		t.Errorf("rows[2][1]: %q", a.Rows[2][1])
	}
}

func TestParseAnswerFile_TrailingBlanks(t *testing.T) {
	a, err := parseAnswerFile(strings.NewReader(sampleTrailingBlanks))
	if err != nil {
		t.Fatalf("parseAnswerFile: %v", err)
	}

	if len(a.Columns) != 2 || len(a.Rows) != 1 {
		t.Errorf("got cols=%v rows=%v", a.Columns, a.Rows)
	}
}

func TestParseAnswerFile_Malformed(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want string
	}{
		{
			name: "empty file",
			src:  "\n\n",
			want: "empty answer file",
		},
		{
			name: "varying column counts",
			src: `a|b|c
1|2
3|4|5
`,
			want: "cannot identify header",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parseAnswerFile(strings.NewReader(tc.src))
			if err == nil {
				t.Fatalf("want error containing %q, got nil", tc.want)
			}

			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q does not contain %q", err.Error(), tc.want)
			}
		})
	}
}

func TestRoundTripJSON(t *testing.T) {
	a, err := parseAnswerFile(strings.NewReader(sampleBasic))
	if err != nil {
		t.Fatalf("parseAnswerFile: %v", err)
	}

	d := &doc{
		Version: "1",
		Source:  "test",
		Answers: map[string]*answer{"q1": a},
	}

	blob, err := json.Marshal(d)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	var back doc
	if err := json.Unmarshal(blob, &back); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if !reflect.DeepEqual(d, &back) {
		t.Fatalf("round-trip mismatch:\n  orig: %+v\n  back: %+v", d, &back)
	}
}

func TestNormaliseStem(t *testing.T) {
	cases := []struct{ in, want string }{
		{"q1", "q1"},
		{"q01", "q1"},
		{"q007", "q7"},
		{"q10", "q10"},
		{"q22", "q22"},
		{"q1-sf1", "q1-sf1"},
		{"q01-sf1", "q1-sf1"},
	}
	for _, c := range cases {
		if got := normaliseStem(c.in); got != c.want {
			t.Errorf("normaliseStem(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}
