version: "2"
run:
  go: "1.24"
  relative-path-mode: gomod

output:
  formats:
    text:
      path: stdout
  sort-order:
    - linter
    - severity
    - file
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 20
      package-average: 0
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    funlen:
      lines: 200
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gocritic:
      disabled-checks:
        - dupImport
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    lll:
      line-length: 120
    misspell:
      locale: US
    nakedret:
      max-func-lines: 0
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - gocognit
        - lll
        - mnd
        - gochecknoglobals
        - err113
        - ireturn
      allow-unused: true
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    tagliatelle:
      case:
        rules:
          json: snake
    varnamelen:
      max-distance: 10
      min-name-length: 2
      check-receiver: false
      check-return: false
      check-type-param: false
      ignore-names:
        - err
        - tc
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - c echo.Context
        - t testing.T
        - f *foo.Bar
        - e error
        - i int
        - const C
        - T any
        - m map[string]int
        - lg *zap.Logger
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: ^//\s*go:generate\s
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - errorlint
        source: ^\s+if _, ok := err\.\([^.]+\.InternalError\); ok {
      - linters:
          - bodyclose
          - containedctx
          - dupl
          - err113
          - errcheck
          - forbidigo
          - forcetypeassert
          - funlen
          - gocognit
          - goconst
          - gocritic
          - gosec
          - ireturn
          - noctx
          - protogetter
          - varnamelen
          - wrapcheck
        path: _test\.go
      - linters:
          - gochecknoglobals
          - unused
        path: bind.go
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - revive
          - staticcheck
        text: in package name
    paths:
      - pb.go$
      - internal/repositories/models
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/stroppy-io/stroppy-core)
        - prefix(github.com/stroppy-io/stroppy)
        - localmodule
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - internal/repositories/models
      - third_party$
      - builtin$
      - examples$
