FROM golang:1.25-alpine3.22 AS builder

RUN apk add --no-cache make curl git

WORKDIR /app

COPY go.mod go.sum ./
COPY cmd/xk6/go.mod cmd/xk6/go.sum ./cmd/xk6/
COPY cmd/xk6air/go.mod cmd/xk6air/go.sum ./cmd/xk6air/
COPY Makefile ./

RUN go mod download

RUN make .install-xk6

COPY . .

RUN make build-xk6

FROM alpine:3.22 AS runner

COPY --from=builder /app/build/stroppy-k6 /k6
COPY --from=builder /app/internal/static/stroppy.pb.js /stroppy.pb.js

# OpenTelemetry configuration
ARG K6_OTEL_METRIC_PREFIX=k6_
ARG K6_OTEL_SERVICE_NAME=stroppy
ARG K6_OTEL_HEADERS=""
ARG K6_OTEL_GRPC_EXPORTER_INSECURE=false
ARG K6_OTEL_GRPC_EXPORTER_ENDPOINT=localhost:4317
ARG K6_OTEL_EXPORTER_TYPE=http
ARG K6_OTEL_HTTP_EXPORTER_INSECURE=false
ARG K6_OTEL_HTTP_EXPORTER_ENDPOINT=localhost:4318
ARG K6_OTEL_HTTP_EXPORTER_URL_PATH=/v1/metrics

ENV K6_OTEL_METRIC_PREFIX=${K6_OTEL_METRIC_PREFIX}
ENV K6_OTEL_SERVICE_NAME=${K6_OTEL_SERVICE_NAME}
ENV K6_OTEL_HEADERS=${K6_OTEL_HEADERS}
ENV K6_OTEL_GRPC_EXPORTER_INSECURE=${K6_OTEL_GRPC_EXPORTER_INSECURE}
ENV K6_OTEL_GRPC_EXPORTER_ENDPOINT=${K6_OTEL_GRPC_EXPORTER_ENDPOINT}
ENV K6_OTEL_EXPORTER_TYPE=${K6_OTEL_EXPORTER_TYPE}
ENV K6_OTEL_HTTP_EXPORTER_INSECURE=${K6_OTEL_HTTP_EXPORTER_INSECURE}
ENV K6_OTEL_HTTP_EXPORTER_ENDPOINT=${K6_OTEL_HTTP_EXPORTER_ENDPOINT}
ENV K6_OTEL_HTTP_EXPORTER_URL_PATH=${K6_OTEL_HTTP_EXPORTER_URL_PATH}

CMD [ "/k6", "run", "test.ts" ]
