import { Options } from "k6/options";
import { Teardown } from "k6/x/stroppy";
import { DriverX, Step, ENV, TxIsolationName, declareDriverSetup } from "./helpers.ts";
import {
  Alphabet,
  Attr,
  Dict,
  Draw,
  Expr,
  InsertMethod as DatagenInsertMethod,
  Rel,
  std,
  type DictBody,
} from "./datagen.ts";
import { parse_sql_with_sections } from "./parse_sql.js";
// Note: `import ... from "./distributions.json" with { type: "json" }`
// hangs k6's goja runtime at module-compile (v1.7.0). Load the same blob
// via `open()` instead — same content, instant startup. Wrapped in a
// tolerant parse so the probe phase (where `open()` is stubbed to "") sees
// an empty-but-structurally-valid payload; setup() replaces it lazily.
function readDistributions(): TpchDistributions {
  const raw = open("./distributions.json");
  if (!raw) return { version: "", source: "", distributions: {} };
  return JSON.parse(raw) as TpchDistributions;
}
const distributions: TpchDistributions = readDistributions();
import {
  tpchText,
  tpchPhone,
  tpchRetailPrice,
  tpchMfgrId,
  tpchMfgr,
  tpchBrand,
  tpchClerk,
  type TpchDistributions,
} from "./tpch_helpers.ts";
import {
  runAndCompareAllQueries,
  logSummary,
  type AnswersFile,
} from "./tpch_validate.ts";

// ============================================================================
// Data-gen simplifications (framework capability proof, not dbgen byte-parity):
//
//   1. Flat populations with row-index-derived keys.
//   2. part ↔ partsupp is expressed with deterministic row math so each
//      part has exactly four distinct suppkeys.
//   3. orders ↔ lineitem is flattened to avg-4 lines per order
//      (l_linenumber 1..4, deterministic). The spec's Uniform(1, 7) is
//      acceptable as a framework proof — the query shapes don't change.
//   4. n_name / n_regionkey are read from a pair of scalar dicts built
//      from distributions.nations; n_regionkey follows dbgen's mapping
//      verbatim so q5 / q7 / q8 keep their expected regional shape.
//   5. Addresses, phones, and comment strings are ASCII draws (enSpc /
//      enNumSpc / num alphabets). No grammar walk, no literal marker
//      injection — see tpchText() in tpch_helpers.ts for the rationale.
//   6. o_orderkey is dense: rowId() ∈ [1, #orders] (spec uses a sparse
//      mapping we don't need for query shape).
//   7. o_totalprice / l_extendedprice are uniform draws rather than the
//      spec's price×quantity×(1-discount)+tax formula. Q1 aggregates
//      still return numbers of the right shape.
//
// Because strings generated by tpchText are random ASCII, Q13's
// `o_comment NOT LIKE '%special%requests%'` and Q9's `p_name LIKE
// '%green%'` produce smaller match sets than the spec reference. The
// framework proof is what lands here; byte-exact dbgen parity is a
// later follow-up.
// ============================================================================

// --------------------------------------------------------------------------
// Configuration
// --------------------------------------------------------------------------

const POOL_SIZE = ENV("POOL_SIZE", 50, "Connection pool size");
const SCALE_FACTOR = Number(
  ENV("SCALE_FACTOR", "1", "TPC-H scale factor; 0.01 supported for smoke tests"),
);

if (!Number.isFinite(SCALE_FACTOR) || SCALE_FACTOR <= 0) {
  throw new Error(`SCALE_FACTOR must be a positive number, got ${SCALE_FACTOR}`);
}

/** Round SF-scaled cardinalities up to at least 1 row. */
function scaleRows(base: number): number {
  const n = Math.floor(base * SCALE_FACTOR);
  return n < 1 ? 1 : n;
}

// Spec §4.2.2 cardinalities.
const N_REGION = 5;
const N_NATION = 25;
const N_PART = scaleRows(200_000);
const N_SUPPLIER = scaleRows(10_000);
const N_CUSTOMER = scaleRows(150_000);
const N_ORDERS = scaleRows(1_500_000);
const N_CLERKS = scaleRows(1_000);
const PARTSUPPS_PER_PART = 4;
const N_PARTSUPP = N_PART * PARTSUPPS_PER_PART;
const LINES_PER_ORDER = 4; // spec mean; simplification from Uniform(1, 7)
const N_LINEITEM = N_ORDERS * LINES_PER_ORDER;

// Spec-frozen per-population seeds.
const SEED_REGION = 0x7EC101;
const SEED_NATION = 0x7EC102;
const SEED_PART = 0x7EC103;
const SEED_SUPPLIER = 0x7EC104;
const SEED_PARTSUPP = 0x7EC105;
const SEED_CUSTOMER = 0x7EC106;
const SEED_ORDERS = 0x7EC107;
const SEED_LINEITEM = 0x7EC108;

// Date windows: o_orderdate in [1992-01-01, 1998-12-31]; lineitem dates
// get a slightly wider band to cover the spec's o_orderdate + offset rule.
const DATE_ORDER_MIN = new Date(Date.UTC(1992, 0, 1));
const DATE_ORDER_MAX = new Date(Date.UTC(1998, 11, 31));
const DATE_LINE_MIN = new Date(Date.UTC(1992, 0, 1));
const DATE_LINE_MAX = new Date(Date.UTC(1999, 0, 31));

export const options: Options = {
  setupTimeout: String(Math.max(5, Math.ceil(SCALE_FACTOR * 15))) + "m",
};

// --------------------------------------------------------------------------
// Driver / SQL wiring
// --------------------------------------------------------------------------

const driverConfig = declareDriverSetup(0, {
  url: "postgres://postgres:postgres@localhost:5432",
  driverType: "postgres",
  defaultInsertMethod: "native",
  pool: { maxConns: POOL_SIZE, minConns: POOL_SIZE },
});

const _sqlByDriver: Record<string, string> = {
  postgres: "./pg.sql",
};
const SQL_FILE =
  ENV("SQL_FILE", ENV.auto, "SQL file path (defaults per driverType)") ??
  _sqlByDriver[driverConfig.driverType!] ??
  "./pg.sql";

const _isoByDriver: Record<string, TxIsolationName> = {
  postgres: "read_committed",
  mysql: "read_committed",
  picodata: "none",
  ydb: "serializable",
};
const TX_ISOLATION = (
  ENV("TX_ISOLATION", ENV.auto, "Override transaction isolation level") ??
  _isoByDriver[driverConfig.driverType!] ??
  "read_committed"
) as TxIsolationName;
void TX_ISOLATION; // queries are read-only; kept for symmetry with other workloads.

const driver = DriverX.create().setup(driverConfig);
const sql = parse_sql_with_sections(open(SQL_FILE));

// --------------------------------------------------------------------------
// Dict wiring — pulled from distributions.json
// --------------------------------------------------------------------------

/**
 * Build a scalar Dict from a distributions.json entry's `value` column.
 * Ignores weights — draws from these dicts are uniform.
 *
 * Tolerates an empty distributions map: the probe phase stubs `open()` to
 * return "", producing a payload with no dicts. In that case we emit a
 * single-entry placeholder dict; probe-time dict content is never read.
 */
function scalarDictFromJson(name: string): DictBody {
  const d = distributions.distributions[name];
  if (!d || d.rows.length === 0) {
    return Dict.values([""]);
  }
  const values = d.rows.map((r) => String(r.values[0]));
  return Dict.values(values);
}

const regionsDict = scalarDictFromJson("regions");
const nationsNameDict = scalarDictFromJson("nations");
// Nation→region mapping from dbgen's cumulative-weight walk over
// distributions.nations (spec §4.2.3). Stable constants kept inline so we
// don't reinterpret the signed weights inside distributions.json.
const nationRegionKeys: readonly number[] = [
  0, 1, 1, 1, 4, 0, 3, 3, 2, 2, 4, 4, 2, 4, 0, 0, 0, 1, 2, 3, 4, 2, 3, 3, 1,
];
if (nationRegionKeys.length !== N_NATION) {
  throw new Error(`tpch: nationRegionKeys length ${nationRegionKeys.length} != ${N_NATION}`);
}
const nationRegionDict = Dict.values(nationRegionKeys);
const mktSegmentDict = scalarDictFromJson("msegmnt");
const orderPriorityDict = scalarDictFromJson("o_oprio");
const containerDict = scalarDictFromJson("p_cntr");
const typesDict = scalarDictFromJson("p_types");
const shipInstructDict = scalarDictFromJson("instruct");
const shipModeDict = scalarDictFromJson("smode");
const returnFlagDict = scalarDictFromJson("rflag");
const colorsDict = scalarDictFromJson("colors");
const linestatusDict = Dict.values(["O", "F"]); // simplified l_linestatus

// --------------------------------------------------------------------------
// Shared sub-expressions
// --------------------------------------------------------------------------

/** Zero-padded 9-digit id — "%09d" — used by Supplier# / Customer# names. */
function fmt9(id: ReturnType<typeof Attr.rowId>) {
  return std.format(Expr.lit("%09d"), id);
}

// --------------------------------------------------------------------------
// Per-table InsertSpec builders
// --------------------------------------------------------------------------

function regionSpec() {
  return Rel.table("region", {
    size: N_REGION,
    seed: SEED_REGION,
    method: DatagenInsertMethod.NATIVE,
    attrs: {
      r_regionkey: Attr.rowIndex(),
      r_name: Attr.dictAt(regionsDict, Attr.rowIndex()),
      r_comment: tpchText(31, 115),
    },
  });
}

function nationSpec() {
  return Rel.table("nation", {
    size: N_NATION,
    seed: SEED_NATION,
    method: DatagenInsertMethod.NATIVE,
    attrs: {
      n_nationkey: Attr.rowIndex(),
      n_name: Attr.dictAt(nationsNameDict, Attr.rowIndex()),
      n_regionkey: Attr.dictAt(nationRegionDict, Attr.rowIndex()),
      n_comment: tpchText(31, 114),
    },
  });
}

function partSpec() {
  const mfgrId = tpchMfgrId();
  return Rel.table("part", {
    size: N_PART,
    seed: SEED_PART,
    method: DatagenInsertMethod.NATIVE,
    attrs: {
      p_partkey: Attr.rowId(),
      p_name: Draw.phrase({
        vocab: colorsDict,
        minWords: Expr.lit(5),
        maxWords: Expr.lit(5),
        separator: " ",
      }),
      p_mfgr: tpchMfgr(mfgrId),
      p_brand: tpchBrand(mfgrId),
      p_type: Draw.dict(typesDict),
      p_size: Draw.intUniform({ min: Expr.lit(1), max: Expr.lit(50) }),
      p_container: Draw.dict(containerDict),
      p_retailprice: tpchRetailPrice(Attr.rowId()),
      p_comment: tpchText(5, 22),
    },
  });
}

function supplierSpec() {
  return Rel.table("supplier", {
    size: N_SUPPLIER,
    seed: SEED_SUPPLIER,
    method: DatagenInsertMethod.NATIVE,
    attrs: {
      s_suppkey: Attr.rowId(),
      s_name: Expr.concat(Expr.lit("Supplier#"), fmt9(Attr.rowId())),
      s_address: Draw.ascii({
        min: Expr.lit(25),
        max: Expr.lit(40),
        alphabet: Alphabet.enNumSpc,
      }),
      s_nationkey: Draw.intUniform({ min: Expr.lit(0), max: Expr.lit(N_NATION - 1) }),
      s_phone: tpchPhone(
        Draw.intUniform({ min: Expr.lit(0), max: Expr.lit(N_NATION - 1) }),
      ),
      s_acctbal: Draw.decimal({ min: Expr.lit(-999.99), max: Expr.lit(9999.99), scale: 2 }),
      s_comment: tpchText(25, 100),
    },
  });
}

function partSuppSpec() {
  // Flat row-math layout:
  //   r ∈ [0, 4 * N_PART)
  //   ps_partkey = r / 4 + 1 ∈ [1, N_PART]
  //   ps_suppkey = wrap((partkey + stride * (r % 4)) mod N_SUPPLIER) + 1
  // Stride = floor(N_SUPPLIER / 4) gives four distinct suppkeys per part
  // while keeping the choice deterministic by row index (seek-safe).
  const stride = Math.max(1, Math.floor(N_SUPPLIER / 4));
  const partkey = Expr.add(Expr.div(Attr.rowIndex(), Expr.lit(PARTSUPPS_PER_PART)), Expr.lit(1));
  const offset = Expr.mod(Attr.rowIndex(), Expr.lit(PARTSUPPS_PER_PART));
  const suppkey = Expr.add(
    Expr.mod(
      Expr.add(partkey, Expr.mul(offset, Expr.lit(stride))),
      Expr.lit(N_SUPPLIER),
    ),
    Expr.lit(1),
  );
  return Rel.table("partsupp", {
    size: N_PARTSUPP,
    seed: SEED_PARTSUPP,
    method: DatagenInsertMethod.NATIVE,
    attrs: {
      ps_partkey: partkey,
      ps_suppkey: suppkey,
      ps_availqty: Draw.intUniform({ min: Expr.lit(1), max: Expr.lit(9999) }),
      ps_supplycost: Draw.decimal({ min: Expr.lit(1.0), max: Expr.lit(1000.0), scale: 2 }),
      ps_comment: tpchText(49, 198),
    },
  });
}

function customerSpec() {
  return Rel.table("customer", {
    size: N_CUSTOMER,
    seed: SEED_CUSTOMER,
    method: DatagenInsertMethod.NATIVE,
    attrs: {
      c_custkey: Attr.rowId(),
      c_name: Expr.concat(Expr.lit("Customer#"), fmt9(Attr.rowId())),
      c_address: Draw.ascii({
        min: Expr.lit(10),
        max: Expr.lit(40),
        alphabet: Alphabet.enNumSpc,
      }),
      c_nationkey: Draw.intUniform({ min: Expr.lit(0), max: Expr.lit(N_NATION - 1) }),
      c_phone: tpchPhone(
        Draw.intUniform({ min: Expr.lit(0), max: Expr.lit(N_NATION - 1) }),
      ),
      c_acctbal: Draw.decimal({ min: Expr.lit(-999.99), max: Expr.lit(9999.99), scale: 2 }),
      c_mktsegment: Draw.dict(mktSegmentDict),
      c_comment: tpchText(29, 116),
    },
  });
}

function ordersSpec() {
  return Rel.table("orders", {
    size: N_ORDERS,
    seed: SEED_ORDERS,
    method: DatagenInsertMethod.NATIVE,
    attrs: {
      o_orderkey: Attr.rowId(),
      o_custkey: Draw.intUniform({ min: Expr.lit(1), max: Expr.lit(N_CUSTOMER) }),
      // Simplified 'O'/'F' split; 'P' (partial) omitted. Q21 only filters 'F'.
      // Bernoulli evaluates to int64 {0,1}; Expr.if expects a bool cond,
      // so lift with an explicit equality check.
      o_orderstatus: Expr.if(
        Expr.eq(Draw.bernoulli({ p: 0.5 }), Expr.lit(1)),
        Expr.lit("F"),
        Expr.lit("O"),
      ),
      o_totalprice: Draw.decimal({ min: Expr.lit(100.0), max: Expr.lit(500000.0), scale: 2 }),
      o_orderdate: Draw.date({ minDate: DATE_ORDER_MIN, maxDate: DATE_ORDER_MAX }),
      o_orderpriority: Draw.dict(orderPriorityDict),
      o_clerk: tpchClerk(N_CLERKS),
      o_shippriority: Expr.lit(0),
      o_comment: tpchText(19, 78),
    },
  });
}

function lineitemSpec() {
  // Flat layout: r ∈ [0, 4 * N_ORDERS).
  //   l_orderkey   = r / 4 + 1 ∈ [1, N_ORDERS]
  //   l_linenumber = r % 4 + 1 ∈ [1, 4]
  const orderkey = Expr.add(Expr.div(Attr.rowIndex(), Expr.lit(LINES_PER_ORDER)), Expr.lit(1));
  const linenumber = Expr.add(Expr.mod(Attr.rowIndex(), Expr.lit(LINES_PER_ORDER)), Expr.lit(1));
  return Rel.table("lineitem", {
    size: N_LINEITEM,
    seed: SEED_LINEITEM,
    method: DatagenInsertMethod.NATIVE,
    attrs: {
      l_orderkey: orderkey,
      l_partkey: Draw.intUniform({ min: Expr.lit(1), max: Expr.lit(N_PART) }),
      l_suppkey: Draw.intUniform({ min: Expr.lit(1), max: Expr.lit(N_SUPPLIER) }),
      l_linenumber: linenumber,
      l_quantity: Draw.decimal({ min: Expr.lit(1.0), max: Expr.lit(50.0), scale: 0 }),
      l_extendedprice: Draw.decimal({ min: Expr.lit(100.0), max: Expr.lit(100000.0), scale: 2 }),
      l_discount: Draw.decimal({ min: Expr.lit(0.0), max: Expr.lit(0.1), scale: 2 }),
      l_tax: Draw.decimal({ min: Expr.lit(0.0), max: Expr.lit(0.08), scale: 2 }),
      l_returnflag: Draw.dict(returnFlagDict),
      l_linestatus: Draw.dict(linestatusDict),
      l_shipdate: Draw.date({ minDate: DATE_LINE_MIN, maxDate: DATE_LINE_MAX }),
      l_commitdate: Draw.date({ minDate: DATE_LINE_MIN, maxDate: DATE_LINE_MAX }),
      l_receiptdate: Draw.date({ minDate: DATE_LINE_MIN, maxDate: DATE_LINE_MAX }),
      l_shipinstruct: Draw.dict(shipInstructDict),
      l_shipmode: Draw.dict(shipModeDict),
      l_comment: tpchText(10, 43),
    },
  });
}

// --------------------------------------------------------------------------
// Query parameter defaults — TPC-H §2.4 pinned values.
// --------------------------------------------------------------------------

const queryParams: Record<string, Record<string, unknown>> = {
  q1: { delta: 90 },
  q2: { size: 15, type: "BRASS", region: "EUROPE" },
  q3: { segment: "BUILDING", date: "1995-03-15" },
  q4: { date: "1993-07-01" },
  q5: { region: "ASIA", date: "1994-01-01" },
  q6: { date: "1994-01-01", discount: 0.06, quantity: 24 },
  q7: { nation1: "FRANCE", nation2: "GERMANY" },
  q8: { region: "AMERICA", nation: "BRAZIL", type: "ECONOMY ANODIZED STEEL" },
  q9: { color: "green" },
  q10: { date: "1993-10-01" },
  q11: { nation: "GERMANY", fraction: 0.0001 / SCALE_FACTOR },
  q12: { shipmode1: "MAIL", shipmode2: "SHIP", date: "1994-01-01" },
  q13: { word1: "special", word2: "requests" },
  q14: { date: "1995-09-01" },
  q15: { date: "1996-01-01" },
  q16: {
    brand: "Brand#45",
    type_prefix: "MEDIUM POLISHED",
    s1: 49, s2: 14, s3: 23, s4: 45, s5: 19, s6: 3, s7: 36, s8: 9,
  },
  q17: { brand: "Brand#23", container: "MED BOX" },
  q18: { quantity: 300 },
  q19: { brand1: "Brand#12", brand2: "Brand#23", brand3: "Brand#34", q1: 1, q2: 10, q3: 20 },
  q20: { color: "forest", nation: "CANADA", date: "1994-01-01" },
  q21: { nation: "SAUDI ARABIA" },
  q22: { cc1: "13", cc2: "31", cc3: "23", cc4: "29", cc5: "30", cc6: "18", cc7: "17" },
};

// --------------------------------------------------------------------------
// k6 lifecycle
// --------------------------------------------------------------------------

export function setup(): void {
  Step("drop_schema", () => {
    sql("drop_schema").forEach((q) => driver.exec(q, {}));
  });

  Step("create_schema", () => {
    sql("create_schema").forEach((q) => driver.exec(q, {}));
  });

  Step("populate", () => {
    driver.insertSpec(regionSpec());
    driver.insertSpec(nationSpec());
    driver.insertSpec(partSpec());
    driver.insertSpec(supplierSpec());
    driver.insertSpec(partSuppSpec());
    driver.insertSpec(customerSpec());
    driver.insertSpec(ordersSpec());
    driver.insertSpec(lineitemSpec());
  });

  Step("set_logged", () => {
    sql("set_logged").forEach((q) => driver.exec(q, {}));
  });

  Step("create_indexes", () => {
    sql("create_indexes").forEach((q) => driver.exec(q, {}));
  });

  Step("queries", () => {
    // Run each query once with pinned defaults. Log timings; tolerate
    // missing bodies gracefully so incremental bring-up works.
    for (let i = 1; i <= 22; i++) {
      const name = "q" + String(i);
      const body = sql(name, "body");
      if (!body) {
        console.log(`[tpch] ${name}: skipped (no body in SQL file)`);
        continue;
      }
      const t0 = Date.now();
      try {
        driver.queryRows(body, queryParams[name] ?? {});
        console.log(`[tpch] ${name}: ok in ${Date.now() - t0}ms`);
      } catch (e) {
        console.log(`[tpch] ${name}: error ${(e as Error)?.message ?? e}`);
      }
    }
  });

  Step("validate_answers", () => {
    if (Math.abs(SCALE_FACTOR - 1) > 1e-9) {
      console.log(
        `[tpch_validate] skipped: answers_sf1 is SF=1 only, current SCALE_FACTOR=${SCALE_FACTOR}`,
      );
      return;
    }
    const queries: Record<string, import("./helpers.ts").SqlQuery | undefined> = {};
    for (let i = 1; i <= 22; i++) {
      const name = "q" + String(i);
      const body = sql(name, "body");
      if (body) queries[name] = body;
    }
    // Load the 2 MB answers blob only when we actually need it.
    const answers = JSON.parse(open("./answers_sf1.json")) as AnswersFile;
    const results = runAndCompareAllQueries(driver, queries, queryParams, answers);
    logSummary(results);
  });

  Step.begin("workload");
}

export default function (): void {
  // TPC-H has no per-iteration transaction workload; loading + querying
  // runs entirely from setup().
}

export function teardown(): void {
  Step.end("workload");
  Teardown();
}
