// @generated by protoc-gen-es v2.10.0 with parameter "target=ts,import_extension=ts,json_types=true,valid_types=legacy_required+protovalidate_required"
// @generated from file proto/stroppy/runtime.proto (package stroppy, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Duration, DurationJson } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Value, ValueJson } from "./common_pb.ts";
import { file_proto_stroppy_common } from "./common_pb.ts";
import type { ExecutorConfig, ExecutorConfigJson, ExporterConfig, ExporterConfigJson, GlobalConfig, GlobalConfigJson, Step, StepJson } from "./config_pb.ts";
import { file_proto_stroppy_config } from "./config_pb.ts";
import type { InsertMethod, InsertMethodJson, TxIsolationLevel, TxIsolationLevelJson, WorkloadDescriptor, WorkloadDescriptorJson, WorkloadUnitDescriptor, WorkloadUnitDescriptorJson } from "./descriptor_pb.ts";
import { file_proto_stroppy_descriptor } from "./descriptor_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/stroppy/runtime.proto.
 */
export const file_proto_stroppy_runtime: GenFile = /*@__PURE__*/
  fileDesc("Chtwcm90by9zdHJvcHB5L3J1bnRpbWUucHJvdG8SB3N0cm9wcHki6AEKC1N0ZXBDb250ZXh0EiUKBmNvbmZpZxgBIAEoCzIVLnN0cm9wcHkuR2xvYmFsQ29uZmlnEhsKBHN0ZXAYAiABKAsyDS5zdHJvcHB5LlN0ZXASKQoIZXhlY3V0b3IYAyABKAsyFy5zdHJvcHB5LkV4ZWN1dG9yQ29uZmlnEi4KCGV4cG9ydGVyGAQgASgLMhcuc3Ryb3BweS5FeHBvcnRlckNvbmZpZ0gAiAEBEi0KCHdvcmtsb2FkGAUgASgLMhsuc3Ryb3BweS5Xb3JrbG9hZERlc2NyaXB0b3JCCwoJX2V4cG9ydGVyInMKC1VuaXRDb250ZXh0EioKDHN0ZXBfY29udGV4dBgBIAEoCzIULnN0cm9wcHkuU3RlcENvbnRleHQSOAoPdW5pdF9kZXNjcmlwdG9yGAIgASgLMh8uc3Ryb3BweS5Xb3JrbG9hZFVuaXREZXNjcmlwdG9yIoMBCgtEcml2ZXJRdWVyeRIMCgRuYW1lGAEgASgJEg8KB3JlcXVlc3QYAiABKAkSHgoGcGFyYW1zGAMgAygLMg4uc3Ryb3BweS5WYWx1ZRIqCgZtZXRob2QYBCABKA4yFS5zdHJvcHB5Lkluc2VydE1ldGhvZEgAiAEBQgkKB19tZXRob2QibgoRRHJpdmVyVHJhbnNhY3Rpb24SJQoHcXVlcmllcxgBIAMoCzIULnN0cm9wcHkuRHJpdmVyUXVlcnkSMgoPaXNvbGF0aW9uX2xldmVsGAIgASgOMhkuc3Ryb3BweS5UeElzb2xhdGlvbkxldmVsIlEKD0RyaXZlclF1ZXJ5U3RhdBIMCgRuYW1lGAEgASgJEjAKDWV4ZWNfZHVyYXRpb24YAiABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24iqAEKFURyaXZlclRyYW5zYWN0aW9uU3RhdBIpCgdxdWVyaWVzGAEgAygLMhguc3Ryb3BweS5Ecml2ZXJRdWVyeVN0YXQSMAoNZXhlY19kdXJhdGlvbhgCIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhIyCg9pc29sYXRpb25fbGV2ZWwYAyABKA4yGS5zdHJvcHB5LlR4SXNvbGF0aW9uTGV2ZWxCOFo2Z2l0aHViLmNvbS9zdHJvcHB5LWlvL3N0cm9wcHkvcGtnL2NvbW1vbi9wcm90by9zdHJvcHB5YgZwcm90bzM", [file_google_protobuf_duration, file_proto_stroppy_common, file_proto_stroppy_config, file_proto_stroppy_descriptor]);

/**
 * *
 * StepContext provides contextual information to a benchmark step during
 * execution. It contains the run context and the step descriptor.
 *
 * @generated from message stroppy.StepContext
 */
export type StepContext = Message<"stroppy.StepContext"> & {
  /**
   * * Global configuration of the benchmark and its steps 
   *
   * @generated from field: stroppy.GlobalConfig config = 1;
   */
  config?: GlobalConfig;

  /**
   * * Current step 
   *
   * @generated from field: stroppy.Step step = 2;
   */
  step?: Step;

  /**
   * * Executor configuration 
   *
   * @generated from field: stroppy.ExecutorConfig executor = 3;
   */
  executor?: ExecutorConfig;

  /**
   * * Exporter configuration 
   *
   * @generated from field: optional stroppy.ExporterConfig exporter = 4;
   */
  exporter?: ExporterConfig;

  /**
   * * Current workload descriptor 
   *
   * @generated from field: stroppy.WorkloadDescriptor workload = 5;
   */
  workload?: WorkloadDescriptor;
};

/**
 * *
 * StepContext provides contextual information to a benchmark step during
 * execution. It contains the run context and the step descriptor.
 *
 * @generated from message stroppy.StepContext
 */
export type StepContextJson = {
  /**
   * * Global configuration of the benchmark and its steps 
   *
   * @generated from field: stroppy.GlobalConfig config = 1;
   */
  config?: GlobalConfigJson;

  /**
   * * Current step 
   *
   * @generated from field: stroppy.Step step = 2;
   */
  step?: StepJson;

  /**
   * * Executor configuration 
   *
   * @generated from field: stroppy.ExecutorConfig executor = 3;
   */
  executor?: ExecutorConfigJson;

  /**
   * * Exporter configuration 
   *
   * @generated from field: optional stroppy.ExporterConfig exporter = 4;
   */
  exporter?: ExporterConfigJson;

  /**
   * * Current workload descriptor 
   *
   * @generated from field: stroppy.WorkloadDescriptor workload = 5;
   */
  workload?: WorkloadDescriptorJson;
};

export type StepContextValid = StepContext;

/**
 * Describes the message stroppy.StepContext.
 * Use `create(StepContextSchema)` to create a new message.
 */
export const StepContextSchema: GenMessage<StepContext, {jsonType: StepContextJson, validType: StepContextValid}> = /*@__PURE__*/
  messageDesc(file_proto_stroppy_runtime, 0);

/**
 * *
 * UnitBuildContext provides the context needed to build a unit from a
 * WorkloadUnitDescriptor.
 *
 * @generated from message stroppy.UnitContext
 */
export type UnitContext = Message<"stroppy.UnitContext"> & {
  /**
   * * Step context 
   *
   * @generated from field: stroppy.StepContext step_context = 1;
   */
  stepContext?: StepContext;

  /**
   * * Current unit descriptor 
   *
   * @generated from field: stroppy.WorkloadUnitDescriptor unit_descriptor = 2;
   */
  unitDescriptor?: WorkloadUnitDescriptor;
};

/**
 * *
 * UnitBuildContext provides the context needed to build a unit from a
 * WorkloadUnitDescriptor.
 *
 * @generated from message stroppy.UnitContext
 */
export type UnitContextJson = {
  /**
   * * Step context 
   *
   * @generated from field: stroppy.StepContext step_context = 1;
   */
  stepContext?: StepContextJson;

  /**
   * * Current unit descriptor 
   *
   * @generated from field: stroppy.WorkloadUnitDescriptor unit_descriptor = 2;
   */
  unitDescriptor?: WorkloadUnitDescriptorJson;
};

export type UnitContextValid = UnitContext;

/**
 * Describes the message stroppy.UnitContext.
 * Use `create(UnitContextSchema)` to create a new message.
 */
export const UnitContextSchema: GenMessage<UnitContext, {jsonType: UnitContextJson, validType: UnitContextValid}> = /*@__PURE__*/
  messageDesc(file_proto_stroppy_runtime, 1);

/**
 * *
 * DriverQuery represents a query that can be executed by a database driver.
 *
 * @generated from message stroppy.DriverQuery
 */
export type DriverQuery = Message<"stroppy.DriverQuery"> & {
  /**
   * * Name of the query 
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * * Request of the query 
   *
   * @generated from field: string request = 2;
   */
  request: string;

  /**
   * * Parameters of the query 
   *
   * @generated from field: repeated stroppy.Value params = 3;
   */
  params: Value[];

  /**
   * * If alternate insertion method required 
   *
   * @generated from field: optional stroppy.InsertMethod method = 4;
   */
  method?: InsertMethod;
};

/**
 * *
 * DriverQuery represents a query that can be executed by a database driver.
 *
 * @generated from message stroppy.DriverQuery
 */
export type DriverQueryJson = {
  /**
   * * Name of the query 
   *
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * * Request of the query 
   *
   * @generated from field: string request = 2;
   */
  request?: string;

  /**
   * * Parameters of the query 
   *
   * @generated from field: repeated stroppy.Value params = 3;
   */
  params?: ValueJson[];

  /**
   * * If alternate insertion method required 
   *
   * @generated from field: optional stroppy.InsertMethod method = 4;
   */
  method?: InsertMethodJson;
};

export type DriverQueryValid = DriverQuery;

/**
 * Describes the message stroppy.DriverQuery.
 * Use `create(DriverQuerySchema)` to create a new message.
 */
export const DriverQuerySchema: GenMessage<DriverQuery, {jsonType: DriverQueryJson, validType: DriverQueryValid}> = /*@__PURE__*/
  messageDesc(file_proto_stroppy_runtime, 2);

/**
 * *
 * DriverTransaction represents a transaction that can be executed by a database
 * driver.
 *
 * @generated from message stroppy.DriverTransaction
 */
export type DriverTransaction = Message<"stroppy.DriverTransaction"> & {
  /**
   * * Queries of the transaction 
   *
   * @generated from field: repeated stroppy.DriverQuery queries = 1;
   */
  queries: DriverQuery[];

  /**
   * * Isolation level of the transaction 
   *
   * @generated from field: stroppy.TxIsolationLevel isolation_level = 2;
   */
  isolationLevel: TxIsolationLevel;
};

/**
 * *
 * DriverTransaction represents a transaction that can be executed by a database
 * driver.
 *
 * @generated from message stroppy.DriverTransaction
 */
export type DriverTransactionJson = {
  /**
   * * Queries of the transaction 
   *
   * @generated from field: repeated stroppy.DriverQuery queries = 1;
   */
  queries?: DriverQueryJson[];

  /**
   * * Isolation level of the transaction 
   *
   * @generated from field: stroppy.TxIsolationLevel isolation_level = 2;
   */
  isolationLevel?: TxIsolationLevelJson;
};

export type DriverTransactionValid = DriverTransaction;

/**
 * Describes the message stroppy.DriverTransaction.
 * Use `create(DriverTransactionSchema)` to create a new message.
 */
export const DriverTransactionSchema: GenMessage<DriverTransaction, {jsonType: DriverTransactionJson, validType: DriverTransactionValid}> = /*@__PURE__*/
  messageDesc(file_proto_stroppy_runtime, 3);

/**
 * *
 * DriverQueryStat represent an actual time spent on single query.
 * exec_duration includes the network round-trip and exection on dbms.
 *
 * @generated from message stroppy.DriverQueryStat
 */
export type DriverQueryStat = Message<"stroppy.DriverQueryStat"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Duration exec_duration = 2;
   */
  execDuration?: Duration;
};

/**
 * *
 * DriverQueryStat represent an actual time spent on single query.
 * exec_duration includes the network round-trip and exection on dbms.
 *
 * @generated from message stroppy.DriverQueryStat
 */
export type DriverQueryStatJson = {
  /**
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * @generated from field: google.protobuf.Duration exec_duration = 2;
   */
  execDuration?: DurationJson;
};

export type DriverQueryStatValid = DriverQueryStat;

/**
 * Describes the message stroppy.DriverQueryStat.
 * Use `create(DriverQueryStatSchema)` to create a new message.
 */
export const DriverQueryStatSchema: GenMessage<DriverQueryStat, {jsonType: DriverQueryStatJson, validType: DriverQueryStatValid}> = /*@__PURE__*/
  messageDesc(file_proto_stroppy_runtime, 4);

/**
 * *
 * DriverTransactionStat represents an actual time spent on transaction.
 * exec_duration includes the network round-trip and exection on dbms.
 *
 * @generated from message stroppy.DriverTransactionStat
 */
export type DriverTransactionStat = Message<"stroppy.DriverTransactionStat"> & {
  /**
   * @generated from field: repeated stroppy.DriverQueryStat queries = 1;
   */
  queries: DriverQueryStat[];

  /**
   * @generated from field: google.protobuf.Duration exec_duration = 2;
   */
  execDuration?: Duration;

  /**
   * @generated from field: stroppy.TxIsolationLevel isolation_level = 3;
   */
  isolationLevel: TxIsolationLevel;
};

/**
 * *
 * DriverTransactionStat represents an actual time spent on transaction.
 * exec_duration includes the network round-trip and exection on dbms.
 *
 * @generated from message stroppy.DriverTransactionStat
 */
export type DriverTransactionStatJson = {
  /**
   * @generated from field: repeated stroppy.DriverQueryStat queries = 1;
   */
  queries?: DriverQueryStatJson[];

  /**
   * @generated from field: google.protobuf.Duration exec_duration = 2;
   */
  execDuration?: DurationJson;

  /**
   * @generated from field: stroppy.TxIsolationLevel isolation_level = 3;
   */
  isolationLevel?: TxIsolationLevelJson;
};

export type DriverTransactionStatValid = DriverTransactionStat;

/**
 * Describes the message stroppy.DriverTransactionStat.
 * Use `create(DriverTransactionStatSchema)` to create a new message.
 */
export const DriverTransactionStatSchema: GenMessage<DriverTransactionStat, {jsonType: DriverTransactionStatJson, validType: DriverTransactionStatValid}> = /*@__PURE__*/
  messageDesc(file_proto_stroppy_runtime, 5);

