// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.26.1
// source: panel/database.proto

package panel

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	crossplane "github.com/stroppy-io/stroppy-cloud-panel/internal/proto/crossplane"
	_ "github.com/yaroher/protoc-gen-pgx-orm/protopgx"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Run_Status int32

const (
	Run_STATUS_UNSPECIFIED Run_Status = 0
	Run_STATUS_IDLE        Run_Status = 1
	Run_STATUS_RUNNING     Run_Status = 2
	Run_STATUS_COMPLETED   Run_Status = 3
	Run_STATUS_FAILED      Run_Status = 4
	Run_STATUS_CANCELLED   Run_Status = 5
)

// Enum value maps for Run_Status.
var (
	Run_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_IDLE",
		2: "STATUS_RUNNING",
		3: "STATUS_COMPLETED",
		4: "STATUS_FAILED",
		5: "STATUS_CANCELLED",
	}
	Run_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_IDLE":        1,
		"STATUS_RUNNING":     2,
		"STATUS_COMPLETED":   3,
		"STATUS_FAILED":      4,
		"STATUS_CANCELLED":   5,
	}
)

func (x Run_Status) Enum() *Run_Status {
	p := new(Run_Status)
	*p = x
	return p
}

func (x Run_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Run_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_panel_database_proto_enumTypes[0].Descriptor()
}

func (Run_Status) Type() protoreflect.EnumType {
	return &file_panel_database_proto_enumTypes[0]
}

func (x Run_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Run_Status.Descriptor instead.
func (Run_Status) EnumDescriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{5, 0}
}

type Ulid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ulid) Reset() {
	*x = Ulid{}
	mi := &file_panel_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ulid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ulid) ProtoMessage() {}

func (x *Ulid) ProtoReflect() protoreflect.Message {
	mi := &file_panel_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ulid.ProtoReflect.Descriptor instead.
func (*Ulid) Descriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{0}
}

func (x *Ulid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Timing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timing) Reset() {
	*x = Timing{}
	mi := &file_panel_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timing) ProtoMessage() {}

func (x *Timing) ProtoReflect() protoreflect.Message {
	mi := &file_panel_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timing.ProtoReflect.Descriptor instead.
func (*Timing) Descriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{1}
}

func (x *Timing) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Timing) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Timing) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timing        *Timing                `protobuf:"bytes,2,opt,name=timing,proto3" json:"timing,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_panel_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_panel_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *User) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StroppyStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timing        *Timing                `protobuf:"bytes,2,opt,name=timing,proto3" json:"timing,omitempty"`
	RunId         *Ulid                  `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepRunInfo   []byte                 `protobuf:"bytes,4,opt,name=step_run_info,json=stepRunInfo,proto3" json:"step_run_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StroppyStep) Reset() {
	*x = StroppyStep{}
	mi := &file_panel_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StroppyStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StroppyStep) ProtoMessage() {}

func (x *StroppyStep) ProtoReflect() protoreflect.Message {
	mi := &file_panel_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StroppyStep.ProtoReflect.Descriptor instead.
func (*StroppyStep) Descriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{3}
}

func (x *StroppyStep) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *StroppyStep) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *StroppyStep) GetRunId() *Ulid {
	if x != nil {
		return x.RunId
	}
	return nil
}

func (x *StroppyStep) GetStepRunInfo() []byte {
	if x != nil {
		return x.StepRunInfo
	}
	return nil
}

type Resource struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Id               *Ulid                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timing           *Timing                        `protobuf:"bytes,2,opt,name=timing,proto3" json:"timing,omitempty"`
	Resource         *crossplane.ResourceWithStatus `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	ParentResourceId *Ulid                          `protobuf:"bytes,4,opt,name=parent_resource_id,json=parentResourceId,proto3,oneof" json:"parent_resource_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_panel_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_panel_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Resource) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *Resource) GetResource() *crossplane.ResourceWithStatus {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Resource) GetParentResourceId() *Ulid {
	if x != nil {
		return x.ParentResourceId
	}
	return nil
}

type Run struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timing              *Timing                `protobuf:"bytes,2,opt,name=timing,proto3" json:"timing,omitempty"`
	Status              Run_Status             `protobuf:"varint,3,opt,name=status,proto3,enum=panel.Run_Status" json:"status,omitempty"`
	TargetVmResourceId  *Ulid                  `protobuf:"bytes,4,opt,name=target_vm_resource_id,json=targetVmResourceId,proto3" json:"target_vm_resource_id,omitempty"`
	RunnerVmResourceId  *Ulid                  `protobuf:"bytes,5,opt,name=runner_vm_resource_id,json=runnerVmResourceId,proto3" json:"runner_vm_resource_id,omitempty"`
	RunInfo             []byte                 `protobuf:"bytes,6,opt,name=run_info,json=runInfo,proto3" json:"run_info,omitempty"`
	GrafanaDashboardUrl *string                `protobuf:"bytes,7,opt,name=grafana_dashboard_url,json=grafanaDashboardUrl,proto3,oneof" json:"grafana_dashboard_url,omitempty"`
	Steps               []*StroppyStep         `protobuf:"bytes,8,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_panel_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_panel_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{5}
}

func (x *Run) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Run) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *Run) GetStatus() Run_Status {
	if x != nil {
		return x.Status
	}
	return Run_STATUS_UNSPECIFIED
}

func (x *Run) GetTargetVmResourceId() *Ulid {
	if x != nil {
		return x.TargetVmResourceId
	}
	return nil
}

func (x *Run) GetRunnerVmResourceId() *Ulid {
	if x != nil {
		return x.RunnerVmResourceId
	}
	return nil
}

func (x *Run) GetRunInfo() []byte {
	if x != nil {
		return x.RunInfo
	}
	return nil
}

func (x *Run) GetGrafanaDashboardUrl() string {
	if x != nil && x.GrafanaDashboardUrl != nil {
		return *x.GrafanaDashboardUrl
	}
	return ""
}

func (x *Run) GetSteps() []*StroppyStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Resource_TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Children      []*Resource_TreeNode   `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource_TreeNode) Reset() {
	*x = Resource_TreeNode{}
	mi := &file_panel_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource_TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource_TreeNode) ProtoMessage() {}

func (x *Resource_TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_panel_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource_TreeNode.ProtoReflect.Descriptor instead.
func (*Resource_TreeNode) Descriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Resource_TreeNode) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Resource_TreeNode) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Resource_TreeNode) GetChildren() []*Resource_TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type Run_List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run_List) Reset() {
	*x = Run_List{}
	mi := &file_panel_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run_List) ProtoMessage() {}

func (x *Run_List) ProtoReflect() protoreflect.Message {
	mi := &file_panel_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run_List.ProtoReflect.Descriptor instead.
func (*Run_List) Descriptor() ([]byte, []int) {
	return file_panel_database_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Run_List) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

var File_panel_database_proto protoreflect.FileDescriptor

const file_panel_database_proto_rawDesc = "" +
	"\n" +
	"\x14panel/database.proto\x12\x05panel\x1a\x1bcrossplane/crossplane.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12protopgx/pgx.proto\x1a\x17validate/validate.proto\" \n" +
	"\x04Ulid\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x1aR\x02id\"\xcd\x01\n" +
	"\x06Timing\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_deleted_at\"\xc4\x01\n" +
	"\x04User\x122\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\x15\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01\xfaB\x05r\x03\x98\x01\x1aR\x02id\x12,\n" +
	"\x06timing\x18\x02 \x01(\v2\r.panel.TimingB\x05\xca>\x02@\x01R\x06timing\x12+\n" +
	"\x05email\x18\x03 \x01(\tB\x15\xca>\b\x12\x02\b\x01\x1a\x02\b\x01\xfaB\ar\x05\x10\x03\x18\xff\x01R\x05email:-\xca>*\b\x01\x12\x05users\"\x1f\n" +
	"\rpassword_hash\x12\x02\b\x01\x1a\n" +
	"\"\bNOT NULL\"\x89\x02\n" +
	"\vStroppyStep\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\r\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01R\x02id\x12,\n" +
	"\x06timing\x18\x02 \x01(\v2\r.panel.TimingB\x05\xca>\x02@\x01R\x06timing\x12_\n" +
	"\x06run_id\x18\x03 \x01(\v2\v.panel.UlidB;\xca>8\x12\x04\b\x01 \x01\x1a0\".NOT NULL REFERENCES runs(id) ON DELETE CASCADER\x05runId\x12)\n" +
	"\rstep_run_info\x18\x04 \x01(\fB\x05\xca>\x02@\x01R\vstepRunInfo:\x14\xca>\x11\b\x01\x12\rstroppy_steps\"\xc0\x03\n" +
	"\bResource\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\r\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01R\x02id\x12,\n" +
	"\x06timing\x18\x02 \x01(\v2\r.panel.TimingB\x05\xca>\x02@\x01R\x06timing\x12A\n" +
	"\bresource\x18\x03 \x01(\v2\x1e.crossplane.ResourceWithStatusB\x05\xca>\x02@\x01R\bresource\x12I\n" +
	"\x12parent_resource_id\x18\x04 \x01(\v2\v.panel.UlidB\t\xca>\x06\x12\x04\b\x01 \x01H\x00R\x10parentResourceId\x88\x01\x01\x1a\xa2\x01\n" +
	"\bTreeNode\x12%\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\b\xfaB\x05r\x03\x98\x01\x1aR\x02id\x122\n" +
	"\bresource\x18\x02 \x01(\v2\x0f.panel.ResourceB\x05\xca>\x02@\x01R\bresource\x12;\n" +
	"\bchildren\x18\x03 \x03(\v2\x18.panel.Resource.TreeNodeB\x05\xca>\x02@\x01R\bchildren:\x10\xca>\r\b\x01\x12\tresourcesB\x15\n" +
	"\x13_parent_resource_id\"\x91\x05\n" +
	"\x03Run\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\r\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01R\x02id\x12,\n" +
	"\x06timing\x18\x02 \x01(\v2\r.panel.TimingB\x05\xca>\x02@\x01R\x06timing\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.panel.Run.StatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12I\n" +
	"\x15target_vm_resource_id\x18\x04 \x01(\v2\v.panel.UlidB\t\xca>\x06\x12\x04\b\x01 \x01R\x12targetVmResourceId\x12I\n" +
	"\x15runner_vm_resource_id\x18\x05 \x01(\v2\v.panel.UlidB\t\xca>\x06\x12\x04\b\x01 \x01R\x12runnerVmResourceId\x12\x19\n" +
	"\brun_info\x18\x06 \x01(\fR\arunInfo\x127\n" +
	"\x15grafana_dashboard_url\x18\a \x01(\tH\x00R\x13grafanaDashboardUrl\x88\x01\x01\x12;\n" +
	"\x05steps\x18\b \x03(\v2\x12.panel.StroppyStepB\x11\xd2>\x0e\n" +
	"\f\n" +
	"\x06run_id\x18\x01 \x01R\x05steps\x1a&\n" +
	"\x04List\x12\x1e\n" +
	"\x04runs\x18\x01 \x03(\v2\n" +
	".panel.RunR\x04runs\"\x84\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSTATUS_IDLE\x10\x01\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x02\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x04\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x05:\v\xca>\b\b\x01\x12\x04runsB\x18\n" +
	"\x16_grafana_dashboard_urlB@Z>github.com/stroppy-io/stroppy-cloud-panel/internal/proto/panelb\x06proto3"

var (
	file_panel_database_proto_rawDescOnce sync.Once
	file_panel_database_proto_rawDescData []byte
)

func file_panel_database_proto_rawDescGZIP() []byte {
	file_panel_database_proto_rawDescOnce.Do(func() {
		file_panel_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panel_database_proto_rawDesc), len(file_panel_database_proto_rawDesc)))
	})
	return file_panel_database_proto_rawDescData
}

var file_panel_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_panel_database_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_panel_database_proto_goTypes = []any{
	(Run_Status)(0),                       // 0: panel.Run.Status
	(*Ulid)(nil),                          // 1: panel.Ulid
	(*Timing)(nil),                        // 2: panel.Timing
	(*User)(nil),                          // 3: panel.User
	(*StroppyStep)(nil),                   // 4: panel.StroppyStep
	(*Resource)(nil),                      // 5: panel.Resource
	(*Run)(nil),                           // 6: panel.Run
	(*Resource_TreeNode)(nil),             // 7: panel.Resource.TreeNode
	(*Run_List)(nil),                      // 8: panel.Run.List
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
	(*crossplane.ResourceWithStatus)(nil), // 10: crossplane.ResourceWithStatus
}
var file_panel_database_proto_depIdxs = []int32{
	9,  // 0: panel.Timing.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: panel.Timing.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: panel.Timing.deleted_at:type_name -> google.protobuf.Timestamp
	1,  // 3: panel.User.id:type_name -> panel.Ulid
	2,  // 4: panel.User.timing:type_name -> panel.Timing
	1,  // 5: panel.StroppyStep.id:type_name -> panel.Ulid
	2,  // 6: panel.StroppyStep.timing:type_name -> panel.Timing
	1,  // 7: panel.StroppyStep.run_id:type_name -> panel.Ulid
	1,  // 8: panel.Resource.id:type_name -> panel.Ulid
	2,  // 9: panel.Resource.timing:type_name -> panel.Timing
	10, // 10: panel.Resource.resource:type_name -> crossplane.ResourceWithStatus
	1,  // 11: panel.Resource.parent_resource_id:type_name -> panel.Ulid
	1,  // 12: panel.Run.id:type_name -> panel.Ulid
	2,  // 13: panel.Run.timing:type_name -> panel.Timing
	0,  // 14: panel.Run.status:type_name -> panel.Run.Status
	1,  // 15: panel.Run.target_vm_resource_id:type_name -> panel.Ulid
	1,  // 16: panel.Run.runner_vm_resource_id:type_name -> panel.Ulid
	4,  // 17: panel.Run.steps:type_name -> panel.StroppyStep
	1,  // 18: panel.Resource.TreeNode.id:type_name -> panel.Ulid
	5,  // 19: panel.Resource.TreeNode.resource:type_name -> panel.Resource
	7,  // 20: panel.Resource.TreeNode.children:type_name -> panel.Resource.TreeNode
	6,  // 21: panel.Run.List.runs:type_name -> panel.Run
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_panel_database_proto_init() }
func file_panel_database_proto_init() {
	if File_panel_database_proto != nil {
		return
	}
	file_panel_database_proto_msgTypes[1].OneofWrappers = []any{}
	file_panel_database_proto_msgTypes[4].OneofWrappers = []any{}
	file_panel_database_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panel_database_proto_rawDesc), len(file_panel_database_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_panel_database_proto_goTypes,
		DependencyIndexes: file_panel_database_proto_depIdxs,
		EnumInfos:         file_panel_database_proto_enumTypes,
		MessageInfos:      file_panel_database_proto_msgTypes,
	}.Build()
	File_panel_database_proto = out.File
	file_panel_database_proto_goTypes = nil
	file_panel_database_proto_depIdxs = nil
}
