// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: panel/template.proto

package panel

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	crossplane "github.com/stroppy-io/stroppy-cloud-panel/internal/proto/crossplane"
	_ "github.com/yaroher/protoc-gen-pgx-orm/protopgx"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timing        *Timing                `protobuf:"bytes,2,opt,name=timing,proto3" json:"timing,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Info          *KV_Info               `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVInfo) Reset() {
	*x = KVInfo{}
	mi := &file_panel_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVInfo) ProtoMessage() {}

func (x *KVInfo) ProtoReflect() protoreflect.Message {
	mi := &file_panel_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVInfo.ProtoReflect.Descriptor instead.
func (*KVInfo) Descriptor() ([]byte, []int) {
	return file_panel_template_proto_rawDescGZIP(), []int{0}
}

func (x *KVInfo) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *KVInfo) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *KVInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVInfo) GetInfo() *KV_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type Template struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timing    *Timing                `protobuf:"bytes,2,opt,name=timing,proto3" json:"timing,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AuthorId  *Ulid                  `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	IsDefault bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Tags      []*Tag                 `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// Types that are valid to be assigned to TemplateData:
	//
	//	*Template_MachineDeployment_
	//	*Template_DatabaseDeployment_
	//	*Template_StroppyDeployment_
	TemplateData  isTemplate_TemplateData `protobuf_oneof:"template_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_panel_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_panel_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_panel_template_proto_rawDescGZIP(), []int{1}
}

func (x *Template) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Template) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetAuthorId() *Ulid {
	if x != nil {
		return x.AuthorId
	}
	return nil
}

func (x *Template) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Template) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Template) GetTemplateData() isTemplate_TemplateData {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *Template) GetMachineDeployment() *Template_MachineDeployment {
	if x != nil {
		if x, ok := x.TemplateData.(*Template_MachineDeployment_); ok {
			return x.MachineDeployment
		}
	}
	return nil
}

func (x *Template) GetDatabaseDeployment() *Template_DatabaseDeployment {
	if x != nil {
		if x, ok := x.TemplateData.(*Template_DatabaseDeployment_); ok {
			return x.DatabaseDeployment
		}
	}
	return nil
}

func (x *Template) GetStroppyDeployment() *Template_StroppyDeployment {
	if x != nil {
		if x, ok := x.TemplateData.(*Template_StroppyDeployment_); ok {
			return x.StroppyDeployment
		}
	}
	return nil
}

type isTemplate_TemplateData interface {
	isTemplate_TemplateData()
}

type Template_MachineDeployment_ struct {
	MachineDeployment *Template_MachineDeployment `protobuf:"bytes,101,opt,name=machine_deployment,json=machineDeployment,proto3,oneof"`
}

type Template_DatabaseDeployment_ struct {
	DatabaseDeployment *Template_DatabaseDeployment `protobuf:"bytes,102,opt,name=database_deployment,json=databaseDeployment,proto3,oneof"`
}

type Template_StroppyDeployment_ struct {
	StroppyDeployment *Template_StroppyDeployment `protobuf:"bytes,103,opt,name=stroppy_deployment,json=stroppyDeployment,proto3,oneof"`
}

func (*Template_MachineDeployment_) isTemplate_TemplateData() {}

func (*Template_DatabaseDeployment_) isTemplate_TemplateData() {}

func (*Template_StroppyDeployment_) isTemplate_TemplateData() {}

type SearchTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TagsList      *Tag_List              `protobuf:"bytes,2,opt,name=tags_list,json=tagsList,proto3" json:"tags_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTemplatesRequest) Reset() {
	*x = SearchTemplatesRequest{}
	mi := &file_panel_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTemplatesRequest) ProtoMessage() {}

func (x *SearchTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panel_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTemplatesRequest.ProtoReflect.Descriptor instead.
func (*SearchTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_panel_template_proto_rawDescGZIP(), []int{2}
}

func (x *SearchTemplatesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchTemplatesRequest) GetTagsList() *Tag_List {
	if x != nil {
		return x.TagsList
	}
	return nil
}

type Template_DatabaseDeployment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrebuiltImageId string                 `protobuf:"bytes,1,opt,name=prebuilt_image_id,json=prebuiltImageId,proto3" json:"prebuilt_image_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Template_DatabaseDeployment) Reset() {
	*x = Template_DatabaseDeployment{}
	mi := &file_panel_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template_DatabaseDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template_DatabaseDeployment) ProtoMessage() {}

func (x *Template_DatabaseDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_panel_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template_DatabaseDeployment.ProtoReflect.Descriptor instead.
func (*Template_DatabaseDeployment) Descriptor() ([]byte, []int) {
	return file_panel_template_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Template_DatabaseDeployment) GetPrebuiltImageId() string {
	if x != nil {
		return x.PrebuiltImageId
	}
	return ""
}

type Template_MachineDeployment struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MachineInfo   *crossplane.MachineInfo `protobuf:"bytes,2,opt,name=machine_info,json=machineInfo,proto3" json:"machine_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template_MachineDeployment) Reset() {
	*x = Template_MachineDeployment{}
	mi := &file_panel_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template_MachineDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template_MachineDeployment) ProtoMessage() {}

func (x *Template_MachineDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_panel_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template_MachineDeployment.ProtoReflect.Descriptor instead.
func (*Template_MachineDeployment) Descriptor() ([]byte, []int) {
	return file_panel_template_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Template_MachineDeployment) GetMachineInfo() *crossplane.MachineInfo {
	if x != nil {
		return x.MachineInfo
	}
	return nil
}

type Template_StroppyDeployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*crossplane.FsFile   `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Cmd           *string                `protobuf:"bytes,2,opt,name=cmd,proto3,oneof" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template_StroppyDeployment) Reset() {
	*x = Template_StroppyDeployment{}
	mi := &file_panel_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template_StroppyDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template_StroppyDeployment) ProtoMessage() {}

func (x *Template_StroppyDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_panel_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template_StroppyDeployment.ProtoReflect.Descriptor instead.
func (*Template_StroppyDeployment) Descriptor() ([]byte, []int) {
	return file_panel_template_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Template_StroppyDeployment) GetFiles() []*crossplane.FsFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Template_StroppyDeployment) GetCmd() string {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return ""
}

type Template_List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template_List) Reset() {
	*x = Template_List{}
	mi := &file_panel_template_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template_List) ProtoMessage() {}

func (x *Template_List) ProtoReflect() protoreflect.Message {
	mi := &file_panel_template_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template_List.ProtoReflect.Descriptor instead.
func (*Template_List) Descriptor() ([]byte, []int) {
	return file_panel_template_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Template_List) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_panel_template_proto protoreflect.FileDescriptor

const file_panel_template_proto_rawDesc = "" +
	"\n" +
	"\x14panel/template.proto\x12\x05panel\x1a\x1bcrossplane/deployment.proto\x1a\x16crossplane/types.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11panel/types.proto\x1a\x12protopgx/pgx.proto\x1a\x17validate/validate.proto\"\xbf\x01\n" +
	"\x06KVInfo\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\r\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01R\x02id\x12,\n" +
	"\x06timing\x18\x02 \x01(\v2\r.panel.TimingB\x05\xca>\x02@\x01R\x06timing\x12\x19\n" +
	"\x03key\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03key\x12)\n" +
	"\x04info\x18\x05 \x01(\v2\x0e.panel.KV.InfoB\x05\xca>\x02@\x01R\x04info:\x15\xca>\x12\b\x01\x12\x0esystem_kv_info\"\x99\a\n" +
	"\bTemplate\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\r\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01R\x02id\x12,\n" +
	"\x06timing\x18\x02 \x01(\v2\r.panel.TimingB\x05\xca>\x02@\x01R\x06timing\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x03\x18\xff\x01R\x04name\x12f\n" +
	"\tauthor_id\x18\x04 \x01(\v2\v.panel.UlidB<\xca>9\x12\x04\b\x01 \x01\x1a1\"/NOT NULL REFERENCES users(id) ON DELETE CASCADER\bauthorId\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12)\n" +
	"\x04tags\x18\x06 \x03(\v2\n" +
	".panel.TagB\t\xca>\x06\x12\x04\b\x01 \x01R\x04tags\x12R\n" +
	"\x12machine_deployment\x18e \x01(\v2!.panel.Template.MachineDeploymentH\x00R\x11machineDeployment\x12U\n" +
	"\x13database_deployment\x18f \x01(\v2\".panel.Template.DatabaseDeploymentH\x00R\x12databaseDeployment\x12R\n" +
	"\x12stroppy_deployment\x18g \x01(\v2!.panel.Template.StroppyDeploymentH\x00R\x11stroppyDeployment\x1aI\n" +
	"\x12DatabaseDeployment\x123\n" +
	"\x11prebuilt_image_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0fprebuiltImageId\x1aV\n" +
	"\x11MachineDeployment\x12A\n" +
	"\fmachine_info\x18\x02 \x01(\v2\x17.crossplane.MachineInfoB\x05\xca>\x02@\x01R\vmachineInfo\x1ae\n" +
	"\x11StroppyDeployment\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.crossplane.FsFileR\x05files\x12\x1e\n" +
	"\x03cmd\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\x03cmd\x88\x01\x01B\x06\n" +
	"\x04_cmd\x1a5\n" +
	"\x04List\x12-\n" +
	"\ttemplates\x18\x01 \x03(\v2\x0f.panel.TemplateR\ttemplates:\x10\xca>\r\b\x01\x12\ttemplatesB\x0f\n" +
	"\rtemplate_data\"c\n" +
	"\x16SearchTemplatesRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12,\n" +
	"\ttags_list\x18\x02 \x01(\v2\x0f.panel.Tag.ListR\btagsList2\x91\x03\n" +
	"\x0fTemplateService\x12<\n" +
	"\x11ListTemplatesTags\x12\x16.google.protobuf.Empty\x1a\x0f.panel.Tag.List\x12F\n" +
	"\x0fSearchTemplates\x12\x1d.panel.SearchTemplatesRequest\x1a\x14.panel.Template.List\x12,\n" +
	"\x0eGetTemplateKvs\x12\v.panel.Ulid\x1a\r.panel.KV.Map\x12+\n" +
	"\vGetTemplate\x12\v.panel.Ulid\x1a\x0f.panel.Template\x122\n" +
	"\x0eCreateTemplate\x12\x0f.panel.Template\x1a\x0f.panel.Template\x122\n" +
	"\x0eUpdateTemplate\x12\x0f.panel.Template\x1a\x0f.panel.Template\x125\n" +
	"\x0eDeleteTemplate\x12\v.panel.Ulid\x1a\x16.google.protobuf.EmptyB@Z>github.com/stroppy-io/stroppy-cloud-panel/internal/proto/panelb\x06proto3"

var (
	file_panel_template_proto_rawDescOnce sync.Once
	file_panel_template_proto_rawDescData []byte
)

func file_panel_template_proto_rawDescGZIP() []byte {
	file_panel_template_proto_rawDescOnce.Do(func() {
		file_panel_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panel_template_proto_rawDesc), len(file_panel_template_proto_rawDesc)))
	})
	return file_panel_template_proto_rawDescData
}

var file_panel_template_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_panel_template_proto_goTypes = []any{
	(*KVInfo)(nil),                      // 0: panel.KVInfo
	(*Template)(nil),                    // 1: panel.Template
	(*SearchTemplatesRequest)(nil),      // 2: panel.SearchTemplatesRequest
	(*Template_DatabaseDeployment)(nil), // 3: panel.Template.DatabaseDeployment
	(*Template_MachineDeployment)(nil),  // 4: panel.Template.MachineDeployment
	(*Template_StroppyDeployment)(nil),  // 5: panel.Template.StroppyDeployment
	(*Template_List)(nil),               // 6: panel.Template.List
	(*Ulid)(nil),                        // 7: panel.Ulid
	(*Timing)(nil),                      // 8: panel.Timing
	(*KV_Info)(nil),                     // 9: panel.KV.Info
	(*Tag)(nil),                         // 10: panel.Tag
	(*Tag_List)(nil),                    // 11: panel.Tag.List
	(*crossplane.MachineInfo)(nil),      // 12: crossplane.MachineInfo
	(*crossplane.FsFile)(nil),           // 13: crossplane.FsFile
	(*emptypb.Empty)(nil),               // 14: google.protobuf.Empty
	(*KV_Map)(nil),                      // 15: panel.KV.Map
}
var file_panel_template_proto_depIdxs = []int32{
	7,  // 0: panel.KVInfo.id:type_name -> panel.Ulid
	8,  // 1: panel.KVInfo.timing:type_name -> panel.Timing
	9,  // 2: panel.KVInfo.info:type_name -> panel.KV.Info
	7,  // 3: panel.Template.id:type_name -> panel.Ulid
	8,  // 4: panel.Template.timing:type_name -> panel.Timing
	7,  // 5: panel.Template.author_id:type_name -> panel.Ulid
	10, // 6: panel.Template.tags:type_name -> panel.Tag
	4,  // 7: panel.Template.machine_deployment:type_name -> panel.Template.MachineDeployment
	3,  // 8: panel.Template.database_deployment:type_name -> panel.Template.DatabaseDeployment
	5,  // 9: panel.Template.stroppy_deployment:type_name -> panel.Template.StroppyDeployment
	11, // 10: panel.SearchTemplatesRequest.tags_list:type_name -> panel.Tag.List
	12, // 11: panel.Template.MachineDeployment.machine_info:type_name -> crossplane.MachineInfo
	13, // 12: panel.Template.StroppyDeployment.files:type_name -> crossplane.FsFile
	1,  // 13: panel.Template.List.templates:type_name -> panel.Template
	14, // 14: panel.TemplateService.ListTemplatesTags:input_type -> google.protobuf.Empty
	2,  // 15: panel.TemplateService.SearchTemplates:input_type -> panel.SearchTemplatesRequest
	7,  // 16: panel.TemplateService.GetTemplateKvs:input_type -> panel.Ulid
	7,  // 17: panel.TemplateService.GetTemplate:input_type -> panel.Ulid
	1,  // 18: panel.TemplateService.CreateTemplate:input_type -> panel.Template
	1,  // 19: panel.TemplateService.UpdateTemplate:input_type -> panel.Template
	7,  // 20: panel.TemplateService.DeleteTemplate:input_type -> panel.Ulid
	11, // 21: panel.TemplateService.ListTemplatesTags:output_type -> panel.Tag.List
	6,  // 22: panel.TemplateService.SearchTemplates:output_type -> panel.Template.List
	15, // 23: panel.TemplateService.GetTemplateKvs:output_type -> panel.KV.Map
	1,  // 24: panel.TemplateService.GetTemplate:output_type -> panel.Template
	1,  // 25: panel.TemplateService.CreateTemplate:output_type -> panel.Template
	1,  // 26: panel.TemplateService.UpdateTemplate:output_type -> panel.Template
	14, // 27: panel.TemplateService.DeleteTemplate:output_type -> google.protobuf.Empty
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_panel_template_proto_init() }
func file_panel_template_proto_init() {
	if File_panel_template_proto != nil {
		return
	}
	file_panel_types_proto_init()
	file_panel_template_proto_msgTypes[1].OneofWrappers = []any{
		(*Template_MachineDeployment_)(nil),
		(*Template_DatabaseDeployment_)(nil),
		(*Template_StroppyDeployment_)(nil),
	}
	file_panel_template_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panel_template_proto_rawDesc), len(file_panel_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panel_template_proto_goTypes,
		DependencyIndexes: file_panel_template_proto_depIdxs,
		MessageInfos:      file_panel_template_proto_msgTypes,
	}.Build()
	File_panel_template_proto = out.File
	file_panel_template_proto_goTypes = nil
	file_panel_template_proto_depIdxs = nil
}
