// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: panel/wrokflow.proto

package panel

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/yaroher/protoc-gen-pgx-orm/protopgx"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowTaskNode_Status int32

const (
	WorkflowTaskNode_WORKFLOW_STATUS_UNSPECIFIED WorkflowTaskNode_Status = 0
	WorkflowTaskNode_WORKFLOW_STATUS_PENDING     WorkflowTaskNode_Status = 1
	WorkflowTaskNode_WORKFLOW_STATUS_RUNNING     WorkflowTaskNode_Status = 2
	WorkflowTaskNode_WORKFLOW_STATUS_COMPLETED   WorkflowTaskNode_Status = 3
	WorkflowTaskNode_WORKFLOW_STATUS_FAILED      WorkflowTaskNode_Status = 4
	WorkflowTaskNode_WORKFLOW_STATUS_CANCELLED   WorkflowTaskNode_Status = 5
)

// Enum value maps for WorkflowTaskNode_Status.
var (
	WorkflowTaskNode_Status_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_PENDING",
		2: "WORKFLOW_STATUS_RUNNING",
		3: "WORKFLOW_STATUS_COMPLETED",
		4: "WORKFLOW_STATUS_FAILED",
		5: "WORKFLOW_STATUS_CANCELLED",
	}
	WorkflowTaskNode_Status_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED": 0,
		"WORKFLOW_STATUS_PENDING":     1,
		"WORKFLOW_STATUS_RUNNING":     2,
		"WORKFLOW_STATUS_COMPLETED":   3,
		"WORKFLOW_STATUS_FAILED":      4,
		"WORKFLOW_STATUS_CANCELLED":   5,
	}
)

func (x WorkflowTaskNode_Status) Enum() *WorkflowTaskNode_Status {
	p := new(WorkflowTaskNode_Status)
	*p = x
	return p
}

func (x WorkflowTaskNode_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowTaskNode_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_panel_wrokflow_proto_enumTypes[0].Descriptor()
}

func (WorkflowTaskNode_Status) Type() protoreflect.EnumType {
	return &file_panel_wrokflow_proto_enumTypes[0]
}

func (x WorkflowTaskNode_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowTaskNode_Status.Descriptor instead.
func (WorkflowTaskNode_Status) EnumDescriptor() ([]byte, []int) {
	return file_panel_wrokflow_proto_rawDescGZIP(), []int{0, 0}
}

type WorkflowTaskNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timing        *Timing                `protobuf:"bytes,2,opt,name=timing,proto3" json:"timing,omitempty"`
	Attempt       uint32                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Logs          []*LogRecord           `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	RetrySettings *Retry                 `protobuf:"bytes,5,opt,name=retry_settings,json=retrySettings,proto3" json:"retry_settings,omitempty"`
	// Types that are valid to be assigned to Task:
	//
	//	*WorkflowTaskNode_DeployDatabaseTask_
	//	*WorkflowTaskNode_DeployStroppyTask_
	//	*WorkflowTaskNode_CollectRunResults_
	Task          isWorkflowTaskNode_Task `protobuf_oneof:"task"`
	Metadata      *Metadata               `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTaskNode) Reset() {
	*x = WorkflowTaskNode{}
	mi := &file_panel_wrokflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTaskNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTaskNode) ProtoMessage() {}

func (x *WorkflowTaskNode) ProtoReflect() protoreflect.Message {
	mi := &file_panel_wrokflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTaskNode.ProtoReflect.Descriptor instead.
func (*WorkflowTaskNode) Descriptor() ([]byte, []int) {
	return file_panel_wrokflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowTaskNode) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *WorkflowTaskNode) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *WorkflowTaskNode) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *WorkflowTaskNode) GetLogs() []*LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *WorkflowTaskNode) GetRetrySettings() *Retry {
	if x != nil {
		return x.RetrySettings
	}
	return nil
}

func (x *WorkflowTaskNode) GetTask() isWorkflowTaskNode_Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *WorkflowTaskNode) GetDeployDatabaseTask() *WorkflowTaskNode_DeployDatabaseTask {
	if x != nil {
		if x, ok := x.Task.(*WorkflowTaskNode_DeployDatabaseTask_); ok {
			return x.DeployDatabaseTask
		}
	}
	return nil
}

func (x *WorkflowTaskNode) GetDeployStroppyTask() *WorkflowTaskNode_DeployStroppyTask {
	if x != nil {
		if x, ok := x.Task.(*WorkflowTaskNode_DeployStroppyTask_); ok {
			return x.DeployStroppyTask
		}
	}
	return nil
}

func (x *WorkflowTaskNode) GetCollectRunResults() *WorkflowTaskNode_CollectRunResults {
	if x != nil {
		if x, ok := x.Task.(*WorkflowTaskNode_CollectRunResults_); ok {
			return x.CollectRunResults
		}
	}
	return nil
}

func (x *WorkflowTaskNode) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isWorkflowTaskNode_Task interface {
	isWorkflowTaskNode_Task()
}

type WorkflowTaskNode_DeployDatabaseTask_ struct {
	DeployDatabaseTask *WorkflowTaskNode_DeployDatabaseTask `protobuf:"bytes,101,opt,name=deploy_database_task,json=deployDatabaseTask,proto3,oneof"`
}

type WorkflowTaskNode_DeployStroppyTask_ struct {
	DeployStroppyTask *WorkflowTaskNode_DeployStroppyTask `protobuf:"bytes,102,opt,name=deploy_stroppy_task,json=deployStroppyTask,proto3,oneof"`
}

type WorkflowTaskNode_CollectRunResults_ struct {
	CollectRunResults *WorkflowTaskNode_CollectRunResults `protobuf:"bytes,103,opt,name=collect_run_results,json=collectRunResults,proto3,oneof"`
}

func (*WorkflowTaskNode_DeployDatabaseTask_) isWorkflowTaskNode_Task() {}

func (*WorkflowTaskNode_DeployStroppyTask_) isWorkflowTaskNode_Task() {}

func (*WorkflowTaskNode_CollectRunResults_) isWorkflowTaskNode_Task() {}

type WorkflowEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          *Ulid                  `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *Ulid                  `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowEdge) Reset() {
	*x = WorkflowEdge{}
	mi := &file_panel_wrokflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEdge) ProtoMessage() {}

func (x *WorkflowEdge) ProtoReflect() protoreflect.Message {
	mi := &file_panel_wrokflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEdge.ProtoReflect.Descriptor instead.
func (*WorkflowEdge) Descriptor() ([]byte, []int) {
	return file_panel_wrokflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowEdge) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *WorkflowEdge) GetFrom() *Ulid {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *WorkflowEdge) GetTo() *Ulid {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *WorkflowEdge) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Ulid                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timing        *Timing                `protobuf:"bytes,2,opt,name=timing,proto3" json:"timing,omitempty"`
	Nodes         []*WorkflowTaskNode    `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*WorkflowEdge        `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_panel_wrokflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_panel_wrokflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_panel_wrokflow_proto_rawDescGZIP(), []int{2}
}

func (x *Workflow) GetId() *Ulid {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Workflow) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *Workflow) GetNodes() []*WorkflowTaskNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Workflow) GetEdges() []*WorkflowEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type WorkflowTaskNode_DeployDatabaseTask struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	ClusterDeployment *DatabaseInstanceTemplate `protobuf:"bytes,1,opt,name=cluster_deployment,json=clusterDeployment,proto3" json:"cluster_deployment,omitempty"` // input
	Deployment        *Deployment               `protobuf:"bytes,100,opt,name=deployment,proto3,oneof" json:"deployment,omitempty"`                                // output
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkflowTaskNode_DeployDatabaseTask) Reset() {
	*x = WorkflowTaskNode_DeployDatabaseTask{}
	mi := &file_panel_wrokflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTaskNode_DeployDatabaseTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTaskNode_DeployDatabaseTask) ProtoMessage() {}

func (x *WorkflowTaskNode_DeployDatabaseTask) ProtoReflect() protoreflect.Message {
	mi := &file_panel_wrokflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTaskNode_DeployDatabaseTask.ProtoReflect.Descriptor instead.
func (*WorkflowTaskNode_DeployDatabaseTask) Descriptor() ([]byte, []int) {
	return file_panel_wrokflow_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WorkflowTaskNode_DeployDatabaseTask) GetClusterDeployment() *DatabaseInstanceTemplate {
	if x != nil {
		return x.ClusterDeployment
	}
	return nil
}

func (x *WorkflowTaskNode_DeployDatabaseTask) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type WorkflowTaskNode_DeployStroppyTask struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	StroppyInstanceTemplate *StroppyInstanceTemplate `protobuf:"bytes,1,opt,name=stroppy_instance_template,json=stroppyInstanceTemplate,proto3" json:"stroppy_instance_template,omitempty"` // input
	DatabaseDeployment      *Deployment              `protobuf:"bytes,2,opt,name=database_deployment,json=databaseDeployment,proto3" json:"database_deployment,omitempty"`                  // input
	Deployment              *Deployment              `protobuf:"bytes,100,opt,name=deployment,proto3,oneof" json:"deployment,omitempty"`                                                    // output
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WorkflowTaskNode_DeployStroppyTask) Reset() {
	*x = WorkflowTaskNode_DeployStroppyTask{}
	mi := &file_panel_wrokflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTaskNode_DeployStroppyTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTaskNode_DeployStroppyTask) ProtoMessage() {}

func (x *WorkflowTaskNode_DeployStroppyTask) ProtoReflect() protoreflect.Message {
	mi := &file_panel_wrokflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTaskNode_DeployStroppyTask.ProtoReflect.Descriptor instead.
func (*WorkflowTaskNode_DeployStroppyTask) Descriptor() ([]byte, []int) {
	return file_panel_wrokflow_proto_rawDescGZIP(), []int{0, 1}
}

func (x *WorkflowTaskNode_DeployStroppyTask) GetStroppyInstanceTemplate() *StroppyInstanceTemplate {
	if x != nil {
		return x.StroppyInstanceTemplate
	}
	return nil
}

func (x *WorkflowTaskNode_DeployStroppyTask) GetDatabaseDeployment() *Deployment {
	if x != nil {
		return x.DatabaseDeployment
	}
	return nil
}

func (x *WorkflowTaskNode_DeployStroppyTask) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type WorkflowTaskNode_CollectRunResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StroppyRunId  *Ulid                  `protobuf:"bytes,1,opt,name=stroppy_run_id,json=stroppyRunId,proto3" json:"stroppy_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTaskNode_CollectRunResults) Reset() {
	*x = WorkflowTaskNode_CollectRunResults{}
	mi := &file_panel_wrokflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTaskNode_CollectRunResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTaskNode_CollectRunResults) ProtoMessage() {}

func (x *WorkflowTaskNode_CollectRunResults) ProtoReflect() protoreflect.Message {
	mi := &file_panel_wrokflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTaskNode_CollectRunResults.ProtoReflect.Descriptor instead.
func (*WorkflowTaskNode_CollectRunResults) Descriptor() ([]byte, []int) {
	return file_panel_wrokflow_proto_rawDescGZIP(), []int{0, 2}
}

func (x *WorkflowTaskNode_CollectRunResults) GetStroppyRunId() *Ulid {
	if x != nil {
		return x.StroppyRunId
	}
	return nil
}

var File_panel_wrokflow_proto protoreflect.FileDescriptor

const file_panel_wrokflow_proto_rawDesc = "" +
	"\n" +
	"\x14panel/wrokflow.proto\x12\x05panel\x1a\x1bcrossplane/deployment.proto\x1a\x14panel/template.proto\x1a\x11panel/types.proto\x1a\x12protopgx/pgx.proto\x1a\x17validate/validate.proto\"\xa3\n" +
	"\n" +
	"\x10WorkflowTaskNode\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\r\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01R\x02id\x12,\n" +
	"\x06timing\x18\x02 \x01(\v2\r.panel.TimingB\x05\xca>\x02@\x01R\x06timing\x12!\n" +
	"\aattempt\x18\x03 \x01(\rB\a\xfaB\x04*\x02 \x00R\aattempt\x12.\n" +
	"\x04logs\x18\x04 \x03(\v2\x10.panel.LogRecordB\b\xfaB\x05\x92\x01\x02\b\x01R\x04logs\x123\n" +
	"\x0eretry_settings\x18\x05 \x01(\v2\f.panel.RetryR\rretrySettings\x12^\n" +
	"\x14deploy_database_task\x18e \x01(\v2*.panel.WorkflowTaskNode.DeployDatabaseTaskH\x00R\x12deployDatabaseTask\x12[\n" +
	"\x13deploy_stroppy_task\x18f \x01(\v2).panel.WorkflowTaskNode.DeployStroppyTaskH\x00R\x11deployStroppyTask\x12[\n" +
	"\x13collect_run_results\x18g \x01(\v2).panel.WorkflowTaskNode.CollectRunResultsH\x00R\x11collectRunResults\x122\n" +
	"\bmetadata\x18\x06 \x01(\v2\x0f.panel.MetadataB\x05\xca>\x02H\x01R\bmetadata\x1a\xb0\x01\n" +
	"\x12DeployDatabaseTask\x12N\n" +
	"\x12cluster_deployment\x18\x01 \x01(\v2\x1f.panel.DatabaseInstanceTemplateR\x11clusterDeployment\x12;\n" +
	"\n" +
	"deployment\x18d \x01(\v2\x16.crossplane.DeploymentH\x00R\n" +
	"deployment\x88\x01\x01B\r\n" +
	"\v_deployment\x1a\x84\x02\n" +
	"\x11DeployStroppyTask\x12Z\n" +
	"\x19stroppy_instance_template\x18\x01 \x01(\v2\x1e.panel.StroppyInstanceTemplateR\x17stroppyInstanceTemplate\x12G\n" +
	"\x13database_deployment\x18\x02 \x01(\v2\x16.crossplane.DeploymentR\x12databaseDeployment\x12;\n" +
	"\n" +
	"deployment\x18d \x01(\v2\x16.crossplane.DeploymentH\x00R\n" +
	"deployment\x88\x01\x01B\r\n" +
	"\v_deployment\x1aF\n" +
	"\x11CollectRunResults\x121\n" +
	"\x0estroppy_run_id\x18\x01 \x01(\v2\v.panel.UlidR\fstroppyRunId\"\xbd\x01\n" +
	"\x06Status\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_CANCELLED\x10\x05:\x15\xca>\x12\b\x01\x12\x0eworkflow_nodesB\x06\n" +
	"\x04task\"\xca\x02\n" +
	"\fWorkflowEdge\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\r\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01R\x02id\x12f\n" +
	"\x04from\x18\x02 \x01(\v2\v.panel.UlidBE\xca>B\x12\x04\b\x01 \x01\x1a:\"8NOT NULL REFERENCES workflow_nodes(id) ON DELETE CASCADER\x04from\x12b\n" +
	"\x02to\x18\x03 \x01(\v2\v.panel.UlidBE\xca>B\x12\x04\b\x01 \x01\x1a:\"8NOT NULL REFERENCES workflow_nodes(id) ON DELETE CASCADER\x02to\x12+\n" +
	"\bmetadata\x18\x04 \x01(\v2\x0f.panel.MetadataR\bmetadata:\x15\xca>\x12\b\x01\x12\x0eworkflow_edges\"\xfc\x01\n" +
	"\bWorkflow\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\v.panel.UlidB\r\xca>\n" +
	"\x12\x04\b\x01 \x01\x1a\x02\x10\x01R\x02id\x12,\n" +
	"\x06timing\x18\x02 \x01(\v2\r.panel.TimingB\x05\xca>\x02@\x01R\x06timing\x12C\n" +
	"\x05nodes\x18\x03 \x03(\v2\x17.panel.WorkflowTaskNodeB\x14\xd2>\x11\n" +
	"\x0f\n" +
	"\vworkflow_id\x18\x01R\x05nodes\x12?\n" +
	"\x05edges\x18\x04 \x03(\v2\x13.panel.WorkflowEdgeB\x14\xd2>\x11\n" +
	"\x0f\n" +
	"\vworkflow_id\x18\x01R\x05edges:\x10\xca>\r\b\x01\x12\tworkflows2n\n" +
	"\x0fWorkflowService\x12+\n" +
	"\vGetWorkflow\x12\v.panel.Ulid\x1a\x0f.panel.Workflow\x12.\n" +
	"\x0eCancelWorkflow\x12\v.panel.Ulid\x1a\x0f.panel.WorkflowB@Z>github.com/stroppy-io/stroppy-cloud-panel/internal/proto/panelb\x06proto3"

var (
	file_panel_wrokflow_proto_rawDescOnce sync.Once
	file_panel_wrokflow_proto_rawDescData []byte
)

func file_panel_wrokflow_proto_rawDescGZIP() []byte {
	file_panel_wrokflow_proto_rawDescOnce.Do(func() {
		file_panel_wrokflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panel_wrokflow_proto_rawDesc), len(file_panel_wrokflow_proto_rawDesc)))
	})
	return file_panel_wrokflow_proto_rawDescData
}

var file_panel_wrokflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_panel_wrokflow_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_panel_wrokflow_proto_goTypes = []any{
	(WorkflowTaskNode_Status)(0),                // 0: panel.WorkflowTaskNode.Status
	(*WorkflowTaskNode)(nil),                    // 1: panel.WorkflowTaskNode
	(*WorkflowEdge)(nil),                        // 2: panel.WorkflowEdge
	(*Workflow)(nil),                            // 3: panel.Workflow
	(*WorkflowTaskNode_DeployDatabaseTask)(nil), // 4: panel.WorkflowTaskNode.DeployDatabaseTask
	(*WorkflowTaskNode_DeployStroppyTask)(nil),  // 5: panel.WorkflowTaskNode.DeployStroppyTask
	(*WorkflowTaskNode_CollectRunResults)(nil),  // 6: panel.WorkflowTaskNode.CollectRunResults
	(*Ulid)(nil),                                // 7: panel.Ulid
	(*Timing)(nil),                              // 8: panel.Timing
	(*LogRecord)(nil),                           // 9: panel.LogRecord
	(*Retry)(nil),                               // 10: panel.Retry
	(*Metadata)(nil),                            // 11: panel.Metadata
	(*DatabaseInstanceTemplate)(nil),            // 12: panel.DatabaseInstanceTemplate
	(*Deployment)(nil),                          // 13: crossplane.Deployment
	(*StroppyInstanceTemplate)(nil),             // 14: panel.StroppyInstanceTemplate
}
var file_panel_wrokflow_proto_depIdxs = []int32{
	7,  // 0: panel.WorkflowTaskNode.id:type_name -> panel.Ulid
	8,  // 1: panel.WorkflowTaskNode.timing:type_name -> panel.Timing
	9,  // 2: panel.WorkflowTaskNode.logs:type_name -> panel.LogRecord
	10, // 3: panel.WorkflowTaskNode.retry_settings:type_name -> panel.Retry
	4,  // 4: panel.WorkflowTaskNode.deploy_database_task:type_name -> panel.WorkflowTaskNode.DeployDatabaseTask
	5,  // 5: panel.WorkflowTaskNode.deploy_stroppy_task:type_name -> panel.WorkflowTaskNode.DeployStroppyTask
	6,  // 6: panel.WorkflowTaskNode.collect_run_results:type_name -> panel.WorkflowTaskNode.CollectRunResults
	11, // 7: panel.WorkflowTaskNode.metadata:type_name -> panel.Metadata
	7,  // 8: panel.WorkflowEdge.id:type_name -> panel.Ulid
	7,  // 9: panel.WorkflowEdge.from:type_name -> panel.Ulid
	7,  // 10: panel.WorkflowEdge.to:type_name -> panel.Ulid
	11, // 11: panel.WorkflowEdge.metadata:type_name -> panel.Metadata
	7,  // 12: panel.Workflow.id:type_name -> panel.Ulid
	8,  // 13: panel.Workflow.timing:type_name -> panel.Timing
	1,  // 14: panel.Workflow.nodes:type_name -> panel.WorkflowTaskNode
	2,  // 15: panel.Workflow.edges:type_name -> panel.WorkflowEdge
	12, // 16: panel.WorkflowTaskNode.DeployDatabaseTask.cluster_deployment:type_name -> panel.DatabaseInstanceTemplate
	13, // 17: panel.WorkflowTaskNode.DeployDatabaseTask.deployment:type_name -> crossplane.Deployment
	14, // 18: panel.WorkflowTaskNode.DeployStroppyTask.stroppy_instance_template:type_name -> panel.StroppyInstanceTemplate
	13, // 19: panel.WorkflowTaskNode.DeployStroppyTask.database_deployment:type_name -> crossplane.Deployment
	13, // 20: panel.WorkflowTaskNode.DeployStroppyTask.deployment:type_name -> crossplane.Deployment
	7,  // 21: panel.WorkflowTaskNode.CollectRunResults.stroppy_run_id:type_name -> panel.Ulid
	7,  // 22: panel.WorkflowService.GetWorkflow:input_type -> panel.Ulid
	7,  // 23: panel.WorkflowService.CancelWorkflow:input_type -> panel.Ulid
	3,  // 24: panel.WorkflowService.GetWorkflow:output_type -> panel.Workflow
	3,  // 25: panel.WorkflowService.CancelWorkflow:output_type -> panel.Workflow
	24, // [24:26] is the sub-list for method output_type
	22, // [22:24] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_panel_wrokflow_proto_init() }
func file_panel_wrokflow_proto_init() {
	if File_panel_wrokflow_proto != nil {
		return
	}
	file_crossplane_deployment_proto_init()
	file_panel_template_proto_init()
	file_panel_types_proto_init()
	file_panel_wrokflow_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkflowTaskNode_DeployDatabaseTask_)(nil),
		(*WorkflowTaskNode_DeployStroppyTask_)(nil),
		(*WorkflowTaskNode_CollectRunResults_)(nil),
	}
	file_panel_wrokflow_proto_msgTypes[3].OneofWrappers = []any{}
	file_panel_wrokflow_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panel_wrokflow_proto_rawDesc), len(file_panel_wrokflow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panel_wrokflow_proto_goTypes,
		DependencyIndexes: file_panel_wrokflow_proto_depIdxs,
		EnumInfos:         file_panel_wrokflow_proto_enumTypes,
		MessageInfos:      file_panel_wrokflow_proto_msgTypes,
	}.Build()
	File_panel_wrokflow_proto = out.File
	file_panel_wrokflow_proto_goTypes = nil
	file_panel_wrokflow_proto_depIdxs = nil
}
