// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CloudAutomations struct {
	ID                     string             `db:"id"`
	CreatedAt              pgtype.Timestamptz `db:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at"`
	DeletedAt              pgtype.Timestamptz `db:"deleted_at"`
	Status                 int32              `db:"status"`
	AuthorID               string             `db:"author_id"`
	DatabaseRootResourceID string             `db:"database_root_resource_id"`
	WorkloadRootResourceID string             `db:"workload_root_resource_id"`
}

type CloudResources struct {
	ID               string             `db:"id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at"`
	Status           int32              `db:"status"`
	Ref              []byte             `db:"ref"`
	ResourceDef      []byte             `db:"resource_def"`
	ResourceYaml     string             `db:"resource_yaml"`
	Synced           bool               `db:"synced"`
	Ready            bool               `db:"ready"`
	ExternalID       string             `db:"external_id"`
	ParentResourceID *string            `db:"parent_resource_id"`
}

type RunRecords struct {
	ID                string             `db:"id"`
	AuthorID          string             `db:"author_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at"`
	Status            int32              `db:"status"`
	Tps               []byte             `db:"tps"`
	Database          []byte             `db:"database"`
	Workload          []byte             `db:"workload"`
	CloudAutomationID *string            `db:"cloud_automation_id"`
}

type StroppyRuns struct {
	ID                  string             `db:"id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at"`
	Status              int32              `db:"status"`
	RunInfo             []byte             `db:"run_info"`
	CloudAutomationID   string             `db:"cloud_automation_id"`
	GrafanaDashboardUrl string             `db:"grafana_dashboard_url"`
}

type StroppySteps struct {
	ID        string             `db:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
	Status    int32              `db:"status"`
	RunID     string             `db:"run_id"`
	StepInfo  []byte             `db:"step_info"`
}

type Users struct {
	ID            string             `db:"id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at"`
	Email         string             `db:"email"`
	Admin         bool               `db:"admin"`
	PasswordHash  string             `db:"password_hash"`
	RefreshTokens []string           `db:"refresh_tokens"`
}
