// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetResourceTree(ctx context.Context, id string) ([]*GetResourceTreeRow, error)
}

var _ Querier = (*Queries)(nil)
