// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetResourceTree = `-- name: GetResourceTree :many
WITH RECURSIVE tree AS (
    SELECT id, created_at, updated_at, deleted_at, ref, resource_def, resource_yaml, synced, ready, external_id, parent_resource_id
    FROM cloud_resources
    WHERE cloud_resources.id = $1

    UNION ALL

    SELECT c.id, c.created_at, c.updated_at, c.deleted_at, c.ref, c.resource_def, c.resource_yaml, c.synced, c.ready, c.external_id, c.parent_resource_id
    FROM cloud_resources c
             INNER JOIN tree t ON c.parent_resource_id = t.id
)
SELECT id, created_at, updated_at, deleted_at, ref, resource_def, resource_yaml, synced, ready, external_id, parent_resource_id
FROM tree
`

type GetResourceTreeRow struct {
	ID               string             `db:"id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at"`
	Ref              []byte             `db:"ref"`
	ResourceDef      []byte             `db:"resource_def"`
	ResourceYaml     string             `db:"resource_yaml"`
	Synced           bool               `db:"synced"`
	Ready            bool               `db:"ready"`
	ExternalID       string             `db:"external_id"`
	ParentResourceID *string            `db:"parent_resource_id"`
}

func (q *Queries) GetResourceTree(ctx context.Context, id string) ([]*GetResourceTreeRow, error) {
	rows, err := q.db.Query(ctx, GetResourceTree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetResourceTreeRow
	for rows.Next() {
		var i GetResourceTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Ref,
			&i.ResourceDef,
			&i.ResourceYaml,
			&i.Synced,
			&i.Ready,
			&i.ExternalID,
			&i.ParentResourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
