CREATE TABLE IF NOT EXISTS "users" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	email TEXT  UNIQUE NOT NULL,
	admin BOOLEAN  NOT NULL DEFAULT FALSE,
	password_hash TEXT NOT NULL,
	refresh_tokens TEXT[]  NULL
);
CREATE TABLE IF NOT EXISTS "machine_templates" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	tags JSONB  NOT NULL,
	cores INTEGER  NOT NULL DEFAULT 0,
	memory INTEGER  NOT NULL DEFAULT 0,
	disk INTEGER  NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "stroppy_deployment_templates" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	name TEXT  NOT NULL,
	tags JSONB  NOT NULL,
	script_body JSONB  NOT NULL,
	stroppy_version TEXT  NOT NULL,
	env_data JSONB  NOT NULL
);
CREATE TABLE IF NOT EXISTS "database_deployment_templates" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	name TEXT  NOT NULL,
	tags JSONB  NOT NULL,
	prebuilt_image_id TEXT  NOT NULL
);
CREATE TABLE IF NOT EXISTS "run_records" (
	id TEXT  PRIMARY KEY NOT NULL,
	author_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	status INTEGER  NOT NULL DEFAULT 0,
	run_info JSONB  NOT NULL,
	tps JSONB  NOT NULL,
	grafana_dashboard_url TEXT  NOT NULL,
	workflow_id TEXT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
	database_instance_template JSONB  NULL,
	stroppy_deployment_info JSONB  NULL
);
CREATE TABLE IF NOT EXISTS "run_record_steps" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	run_id TEXT NOT NULL REFERENCES run_records(id) ON DELETE CASCADE,
	status INTEGER  NOT NULL DEFAULT 0,
	step_info JSONB  NOT NULL
);
CREATE TABLE IF NOT EXISTS "workflow_nodes" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	attempt INTEGER  NOT NULL DEFAULT 0,
	metadata JSONB  NOT NULL,
	workflow_id TEXT REFERENCES workflows (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "workflow_edges" (
	id TEXT  PRIMARY KEY NOT NULL,
	from TEXT NOT NULL REFERENCES workflow_nodes(id) ON DELETE CASCADE,
	to TEXT NOT NULL REFERENCES workflow_nodes(id) ON DELETE CASCADE,
	workflow_id TEXT REFERENCES workflows (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "workflows" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null
);
