CREATE TABLE IF NOT EXISTS "users" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	email TEXT  UNIQUE NOT NULL,
	admin BOOLEAN  NOT NULL DEFAULT FALSE,
	password_hash TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "refresh_tokens" (
	user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	token TEXT  NOT NULL
);
CREATE TABLE IF NOT EXISTS "templates" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	name TEXT  NOT NULL,
	author_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	is_default BOOLEAN  NOT NULL DEFAULT FALSE,
	tags TEXT[]  NOT NULL
);
CREATE TABLE IF NOT EXISTS "kv_infos" (
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	key TEXT  PRIMARY KEY NOT NULL,
	info JSONB  NOT NULL
);
CREATE TABLE IF NOT EXISTS "run_records" (
	id TEXT  PRIMARY KEY NOT NULL,
	author_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	status INTEGER  NOT NULL DEFAULT 0,
	run_info JSONB  NOT NULL,
	tps JSONB  NOT NULL,
	grafana_dashboard_url TEXT  NOT NULL,
	workflow_id TEXT  NULL,
	cloud_run_params JSONB  NULL
);
CREATE TABLE IF NOT EXISTS "run_record_steps" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	run_id TEXT NOT NULL REFERENCES run_records(id) ON DELETE CASCADE,
	status INTEGER  NOT NULL DEFAULT 0,
	step_info JSONB  NOT NULL
);
CREATE TABLE IF NOT EXISTS "quotas" (
	cloud INTEGER  NOT NULL DEFAULT 0,
	kind INTEGER  NOT NULL DEFAULT 0,
	maximum INTEGER  NOT NULL DEFAULT 0,
	current INTEGER  NOT NULL DEFAULT 0,
	UNIQUE(cloud, kind)
);
CREATE TABLE IF NOT EXISTS "workflows" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null
);
CREATE TABLE IF NOT EXISTS "workflow_tasks" (
	id TEXT  PRIMARY KEY NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL,
	updated_at TIMESTAMPTZ  NOT NULL,
	deleted_at TIMESTAMPTZ  NULL DEFAULT null,
	task_type INTEGER  NOT NULL DEFAULT 0,
	status INTEGER  NOT NULL DEFAULT 0,
	workflow_id TEXT  NOT NULL,
	cleaned_up BOOLEAN  NOT NULL DEFAULT FALSE,
	on_worker TEXT  NOT NULL,
	retry_state JSONB  NOT NULL,
	logs JSONB[]  NOT NULL,
	retry_settings JSONB  NOT NULL,
	input JSONB  NOT NULL,
	output JSONB  NOT NULL,
	metadata JSONB  NOT NULL
);
CREATE TABLE IF NOT EXISTS "workflow_edges" (
	from_id TEXT NOT NULL REFERENCES workflow_tasks(id) ON DELETE CASCADE,
	to_id TEXT NOT NULL REFERENCES workflow_tasks(id) ON DELETE CASCADE,
	workflow_id TEXT REFERENCES workflows (id) ON DELETE CASCADE
);
