// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts,import_extension=ts"
// @generated from file panel/template.proto (package panel, syntax proto3)
/* eslint-disable */

import { KvService } from "./template_pb.ts";

/**
 * @generated from rpc panel.KvService.ListKvs
 */
export const listKvs = KvService.method.listKvs;

/**
 * @generated from rpc panel.KvService.PutKv
 */
export const putKv = KvService.method.putKv;

/**
 * @generated from rpc panel.KvService.UpdateKv
 */
export const updateKv = KvService.method.updateKv;

/**
 * @generated from rpc panel.KvService.DeleteKv
 */
export const deleteKv = KvService.method.deleteKv;
