// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: panel/automate.proto

package panelconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	panel "github.com/stroppy-io/stroppy-cloud-panel/internal/proto/panel"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResourcesServiceName is the fully-qualified name of the ResourcesService service.
	ResourcesServiceName = "panel.ResourcesService"
	// AutomateServiceName is the fully-qualified name of the AutomateService service.
	AutomateServiceName = "panel.AutomateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResourcesServiceGetResourceProcedure is the fully-qualified name of the ResourcesService's
	// GetResource RPC.
	ResourcesServiceGetResourceProcedure = "/panel.ResourcesService/GetResource"
	// AutomateServiceGetAutomationProcedure is the fully-qualified name of the AutomateService's
	// GetAutomation RPC.
	AutomateServiceGetAutomationProcedure = "/panel.AutomateService/GetAutomation"
	// AutomateServiceListAutomationsProcedure is the fully-qualified name of the AutomateService's
	// ListAutomations RPC.
	AutomateServiceListAutomationsProcedure = "/panel.AutomateService/ListAutomations"
	// AutomateServiceRunAutomationProcedure is the fully-qualified name of the AutomateService's
	// RunAutomation RPC.
	AutomateServiceRunAutomationProcedure = "/panel.AutomateService/RunAutomation"
	// AutomateServiceCancelAutomationProcedure is the fully-qualified name of the AutomateService's
	// CancelAutomation RPC.
	AutomateServiceCancelAutomationProcedure = "/panel.AutomateService/CancelAutomation"
)

// ResourcesServiceClient is a client for the panel.ResourcesService service.
type ResourcesServiceClient interface {
	GetResource(context.Context, *panel.Ulid) (*panel.CloudResource_TreeNode, error)
}

// NewResourcesServiceClient constructs a client for the panel.ResourcesService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResourcesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResourcesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resourcesServiceMethods := panel.File_panel_automate_proto.Services().ByName("ResourcesService").Methods()
	return &resourcesServiceClient{
		getResource: connect.NewClient[panel.Ulid, panel.CloudResource_TreeNode](
			httpClient,
			baseURL+ResourcesServiceGetResourceProcedure,
			connect.WithSchema(resourcesServiceMethods.ByName("GetResource")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resourcesServiceClient implements ResourcesServiceClient.
type resourcesServiceClient struct {
	getResource *connect.Client[panel.Ulid, panel.CloudResource_TreeNode]
}

// GetResource calls panel.ResourcesService.GetResource.
func (c *resourcesServiceClient) GetResource(ctx context.Context, req *panel.Ulid) (*panel.CloudResource_TreeNode, error) {
	response, err := c.getResource.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ResourcesServiceHandler is an implementation of the panel.ResourcesService service.
type ResourcesServiceHandler interface {
	GetResource(context.Context, *panel.Ulid) (*panel.CloudResource_TreeNode, error)
}

// NewResourcesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResourcesServiceHandler(svc ResourcesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resourcesServiceMethods := panel.File_panel_automate_proto.Services().ByName("ResourcesService").Methods()
	resourcesServiceGetResourceHandler := connect.NewUnaryHandlerSimple(
		ResourcesServiceGetResourceProcedure,
		svc.GetResource,
		connect.WithSchema(resourcesServiceMethods.ByName("GetResource")),
		connect.WithHandlerOptions(opts...),
	)
	return "/panel.ResourcesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResourcesServiceGetResourceProcedure:
			resourcesServiceGetResourceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResourcesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResourcesServiceHandler struct{}

func (UnimplementedResourcesServiceHandler) GetResource(context.Context, *panel.Ulid) (*panel.CloudResource_TreeNode, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panel.ResourcesService.GetResource is not implemented"))
}

// AutomateServiceClient is a client for the panel.AutomateService service.
type AutomateServiceClient interface {
	GetAutomation(context.Context, *panel.Ulid) (*panel.CloudAutomation, error)
	ListAutomations(context.Context, *panel.ListAutomationsRequest) (*panel.CloudAutomation_List, error)
	RunAutomation(context.Context, *panel.RunAutomationRequest) (*panel.RunRecord, error)
	CancelAutomation(context.Context, *panel.Ulid) (*emptypb.Empty, error)
}

// NewAutomateServiceClient constructs a client for the panel.AutomateService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAutomateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AutomateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	automateServiceMethods := panel.File_panel_automate_proto.Services().ByName("AutomateService").Methods()
	return &automateServiceClient{
		getAutomation: connect.NewClient[panel.Ulid, panel.CloudAutomation](
			httpClient,
			baseURL+AutomateServiceGetAutomationProcedure,
			connect.WithSchema(automateServiceMethods.ByName("GetAutomation")),
			connect.WithClientOptions(opts...),
		),
		listAutomations: connect.NewClient[panel.ListAutomationsRequest, panel.CloudAutomation_List](
			httpClient,
			baseURL+AutomateServiceListAutomationsProcedure,
			connect.WithSchema(automateServiceMethods.ByName("ListAutomations")),
			connect.WithClientOptions(opts...),
		),
		runAutomation: connect.NewClient[panel.RunAutomationRequest, panel.RunRecord](
			httpClient,
			baseURL+AutomateServiceRunAutomationProcedure,
			connect.WithSchema(automateServiceMethods.ByName("RunAutomation")),
			connect.WithClientOptions(opts...),
		),
		cancelAutomation: connect.NewClient[panel.Ulid, emptypb.Empty](
			httpClient,
			baseURL+AutomateServiceCancelAutomationProcedure,
			connect.WithSchema(automateServiceMethods.ByName("CancelAutomation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// automateServiceClient implements AutomateServiceClient.
type automateServiceClient struct {
	getAutomation    *connect.Client[panel.Ulid, panel.CloudAutomation]
	listAutomations  *connect.Client[panel.ListAutomationsRequest, panel.CloudAutomation_List]
	runAutomation    *connect.Client[panel.RunAutomationRequest, panel.RunRecord]
	cancelAutomation *connect.Client[panel.Ulid, emptypb.Empty]
}

// GetAutomation calls panel.AutomateService.GetAutomation.
func (c *automateServiceClient) GetAutomation(ctx context.Context, req *panel.Ulid) (*panel.CloudAutomation, error) {
	response, err := c.getAutomation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListAutomations calls panel.AutomateService.ListAutomations.
func (c *automateServiceClient) ListAutomations(ctx context.Context, req *panel.ListAutomationsRequest) (*panel.CloudAutomation_List, error) {
	response, err := c.listAutomations.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RunAutomation calls panel.AutomateService.RunAutomation.
func (c *automateServiceClient) RunAutomation(ctx context.Context, req *panel.RunAutomationRequest) (*panel.RunRecord, error) {
	response, err := c.runAutomation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CancelAutomation calls panel.AutomateService.CancelAutomation.
func (c *automateServiceClient) CancelAutomation(ctx context.Context, req *panel.Ulid) (*emptypb.Empty, error) {
	response, err := c.cancelAutomation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AutomateServiceHandler is an implementation of the panel.AutomateService service.
type AutomateServiceHandler interface {
	GetAutomation(context.Context, *panel.Ulid) (*panel.CloudAutomation, error)
	ListAutomations(context.Context, *panel.ListAutomationsRequest) (*panel.CloudAutomation_List, error)
	RunAutomation(context.Context, *panel.RunAutomationRequest) (*panel.RunRecord, error)
	CancelAutomation(context.Context, *panel.Ulid) (*emptypb.Empty, error)
}

// NewAutomateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAutomateServiceHandler(svc AutomateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	automateServiceMethods := panel.File_panel_automate_proto.Services().ByName("AutomateService").Methods()
	automateServiceGetAutomationHandler := connect.NewUnaryHandlerSimple(
		AutomateServiceGetAutomationProcedure,
		svc.GetAutomation,
		connect.WithSchema(automateServiceMethods.ByName("GetAutomation")),
		connect.WithHandlerOptions(opts...),
	)
	automateServiceListAutomationsHandler := connect.NewUnaryHandlerSimple(
		AutomateServiceListAutomationsProcedure,
		svc.ListAutomations,
		connect.WithSchema(automateServiceMethods.ByName("ListAutomations")),
		connect.WithHandlerOptions(opts...),
	)
	automateServiceRunAutomationHandler := connect.NewUnaryHandlerSimple(
		AutomateServiceRunAutomationProcedure,
		svc.RunAutomation,
		connect.WithSchema(automateServiceMethods.ByName("RunAutomation")),
		connect.WithHandlerOptions(opts...),
	)
	automateServiceCancelAutomationHandler := connect.NewUnaryHandlerSimple(
		AutomateServiceCancelAutomationProcedure,
		svc.CancelAutomation,
		connect.WithSchema(automateServiceMethods.ByName("CancelAutomation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/panel.AutomateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AutomateServiceGetAutomationProcedure:
			automateServiceGetAutomationHandler.ServeHTTP(w, r)
		case AutomateServiceListAutomationsProcedure:
			automateServiceListAutomationsHandler.ServeHTTP(w, r)
		case AutomateServiceRunAutomationProcedure:
			automateServiceRunAutomationHandler.ServeHTTP(w, r)
		case AutomateServiceCancelAutomationProcedure:
			automateServiceCancelAutomationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAutomateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAutomateServiceHandler struct{}

func (UnimplementedAutomateServiceHandler) GetAutomation(context.Context, *panel.Ulid) (*panel.CloudAutomation, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panel.AutomateService.GetAutomation is not implemented"))
}

func (UnimplementedAutomateServiceHandler) ListAutomations(context.Context, *panel.ListAutomationsRequest) (*panel.CloudAutomation_List, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panel.AutomateService.ListAutomations is not implemented"))
}

func (UnimplementedAutomateServiceHandler) RunAutomation(context.Context, *panel.RunAutomationRequest) (*panel.RunRecord, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panel.AutomateService.RunAutomation is not implemented"))
}

func (UnimplementedAutomateServiceHandler) CancelAutomation(context.Context, *panel.Ulid) (*emptypb.Empty, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panel.AutomateService.CancelAutomation is not implemented"))
}
