// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: panel/run.proto

package panelconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	panel "github.com/stroppy-io/stroppy-cloud-panel/internal/proto/panel"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RunServiceName is the fully-qualified name of the RunService service.
	RunServiceName = "panel.RunService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RunServiceListRunsProcedure is the fully-qualified name of the RunService's ListRuns RPC.
	RunServiceListRunsProcedure = "/panel.RunService/ListRuns"
	// RunServiceListTopRunsProcedure is the fully-qualified name of the RunService's ListTopRuns RPC.
	RunServiceListTopRunsProcedure = "/panel.RunService/ListTopRuns"
	// RunServiceAddRunProcedure is the fully-qualified name of the RunService's AddRun RPC.
	RunServiceAddRunProcedure = "/panel.RunService/AddRun"
)

// RunServiceClient is a client for the panel.RunService service.
type RunServiceClient interface {
	ListRuns(context.Context, *panel.ListRunsRequest) (*panel.RunRecord_List, error)
	ListTopRuns(context.Context, *emptypb.Empty) (*panel.RunRecord_List, error)
	AddRun(context.Context, *panel.RunRecord) (*panel.RunRecord, error)
}

// NewRunServiceClient constructs a client for the panel.RunService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runServiceMethods := panel.File_panel_run_proto.Services().ByName("RunService").Methods()
	return &runServiceClient{
		listRuns: connect.NewClient[panel.ListRunsRequest, panel.RunRecord_List](
			httpClient,
			baseURL+RunServiceListRunsProcedure,
			connect.WithSchema(runServiceMethods.ByName("ListRuns")),
			connect.WithClientOptions(opts...),
		),
		listTopRuns: connect.NewClient[emptypb.Empty, panel.RunRecord_List](
			httpClient,
			baseURL+RunServiceListTopRunsProcedure,
			connect.WithSchema(runServiceMethods.ByName("ListTopRuns")),
			connect.WithClientOptions(opts...),
		),
		addRun: connect.NewClient[panel.RunRecord, panel.RunRecord](
			httpClient,
			baseURL+RunServiceAddRunProcedure,
			connect.WithSchema(runServiceMethods.ByName("AddRun")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runServiceClient implements RunServiceClient.
type runServiceClient struct {
	listRuns    *connect.Client[panel.ListRunsRequest, panel.RunRecord_List]
	listTopRuns *connect.Client[emptypb.Empty, panel.RunRecord_List]
	addRun      *connect.Client[panel.RunRecord, panel.RunRecord]
}

// ListRuns calls panel.RunService.ListRuns.
func (c *runServiceClient) ListRuns(ctx context.Context, req *panel.ListRunsRequest) (*panel.RunRecord_List, error) {
	response, err := c.listRuns.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListTopRuns calls panel.RunService.ListTopRuns.
func (c *runServiceClient) ListTopRuns(ctx context.Context, req *emptypb.Empty) (*panel.RunRecord_List, error) {
	response, err := c.listTopRuns.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AddRun calls panel.RunService.AddRun.
func (c *runServiceClient) AddRun(ctx context.Context, req *panel.RunRecord) (*panel.RunRecord, error) {
	response, err := c.addRun.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RunServiceHandler is an implementation of the panel.RunService service.
type RunServiceHandler interface {
	ListRuns(context.Context, *panel.ListRunsRequest) (*panel.RunRecord_List, error)
	ListTopRuns(context.Context, *emptypb.Empty) (*panel.RunRecord_List, error)
	AddRun(context.Context, *panel.RunRecord) (*panel.RunRecord, error)
}

// NewRunServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunServiceHandler(svc RunServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runServiceMethods := panel.File_panel_run_proto.Services().ByName("RunService").Methods()
	runServiceListRunsHandler := connect.NewUnaryHandlerSimple(
		RunServiceListRunsProcedure,
		svc.ListRuns,
		connect.WithSchema(runServiceMethods.ByName("ListRuns")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceListTopRunsHandler := connect.NewUnaryHandlerSimple(
		RunServiceListTopRunsProcedure,
		svc.ListTopRuns,
		connect.WithSchema(runServiceMethods.ByName("ListTopRuns")),
		connect.WithHandlerOptions(opts...),
	)
	runServiceAddRunHandler := connect.NewUnaryHandlerSimple(
		RunServiceAddRunProcedure,
		svc.AddRun,
		connect.WithSchema(runServiceMethods.ByName("AddRun")),
		connect.WithHandlerOptions(opts...),
	)
	return "/panel.RunService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunServiceListRunsProcedure:
			runServiceListRunsHandler.ServeHTTP(w, r)
		case RunServiceListTopRunsProcedure:
			runServiceListTopRunsHandler.ServeHTTP(w, r)
		case RunServiceAddRunProcedure:
			runServiceAddRunHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRunServiceHandler struct{}

func (UnimplementedRunServiceHandler) ListRuns(context.Context, *panel.ListRunsRequest) (*panel.RunRecord_List, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panel.RunService.ListRuns is not implemented"))
}

func (UnimplementedRunServiceHandler) ListTopRuns(context.Context, *emptypb.Empty) (*panel.RunRecord_List, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panel.RunService.ListTopRuns is not implemented"))
}

func (UnimplementedRunServiceHandler) AddRun(context.Context, *panel.RunRecord) (*panel.RunRecord, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("panel.RunService.AddRun is not implemented"))
}
