// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.26.1
// source: sidecar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_proto_rawDesc = "" +
	"\n" +
	"\rsidecar.proto\x12\astroppy\x1a\fconfig.proto\x1a\x1bgoogle/protobuf/empty.proto2\xfa\x01\n" +
	"\rSidecarPlugin\x125\n" +
	"\n" +
	"Initialize\x12\x0f.stroppy.Config\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\vOnStepStart\x12\x14.stroppy.StepContext\x1a\x16.google.protobuf.Empty\x129\n" +
	"\tOnStepEnd\x12\x14.stroppy.StepContext\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bTeardown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB.Z,github.com/stroppy-io/stroppy/pkg/core/protob\x06proto3"

var file_sidecar_proto_goTypes = []any{
	(*Config)(nil),        // 0: stroppy.Config
	(*StepContext)(nil),   // 1: stroppy.StepContext
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_sidecar_proto_depIdxs = []int32{
	0, // 0: stroppy.SidecarPlugin.Initialize:input_type -> stroppy.Config
	1, // 1: stroppy.SidecarPlugin.OnStepStart:input_type -> stroppy.StepContext
	1, // 2: stroppy.SidecarPlugin.OnStepEnd:input_type -> stroppy.StepContext
	2, // 3: stroppy.SidecarPlugin.Teardown:input_type -> google.protobuf.Empty
	2, // 4: stroppy.SidecarPlugin.Initialize:output_type -> google.protobuf.Empty
	2, // 5: stroppy.SidecarPlugin.OnStepStart:output_type -> google.protobuf.Empty
	2, // 6: stroppy.SidecarPlugin.OnStepEnd:output_type -> google.protobuf.Empty
	2, // 7: stroppy.SidecarPlugin.Teardown:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sidecar_proto_init() }
func file_sidecar_proto_init() {
	if File_sidecar_proto != nil {
		return
	}
	file_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_proto_rawDesc), len(file_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_proto_depIdxs,
	}.Build()
	File_sidecar_proto = out.File
	file_sidecar_proto_goTypes = nil
	file_sidecar_proto_depIdxs = nil
}
