-- name: GetAllResourcesIps :many
-- SELECT DISTINCT (jsonb_array_elements(c.resource_def -> 'spec' -> 'yandexCloudVm' -> 'networkInterface') ->
--                  'ipAddress')::TEXT AS ip_address
-- FROM cloud_resources as c
-- WHERE status = ANY($1::int[]);
