// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/stroppy/config.proto

package stroppy

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DriverConfig_DriverType int32

const (
	DriverConfig_DRIVER_TYPE_UNSPECIFIED DriverConfig_DriverType = 0
	DriverConfig_DRIVER_TYPE_POSTGRES    DriverConfig_DriverType = 1
)

// Enum value maps for DriverConfig_DriverType.
var (
	DriverConfig_DriverType_name = map[int32]string{
		0: "DRIVER_TYPE_UNSPECIFIED",
		1: "DRIVER_TYPE_POSTGRES",
	}
	DriverConfig_DriverType_value = map[string]int32{
		"DRIVER_TYPE_UNSPECIFIED": 0,
		"DRIVER_TYPE_POSTGRES":    1,
	}
)

func (x DriverConfig_DriverType) Enum() *DriverConfig_DriverType {
	p := new(DriverConfig_DriverType)
	*p = x
	return p
}

func (x DriverConfig_DriverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DriverConfig_DriverType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stroppy_config_proto_enumTypes[0].Descriptor()
}

func (DriverConfig_DriverType) Type() protoreflect.EnumType {
	return &file_proto_stroppy_config_proto_enumTypes[0]
}

func (x DriverConfig_DriverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DriverConfig_DriverType.Descriptor instead.
func (DriverConfig_DriverType) EnumDescriptor() ([]byte, []int) {
	return file_proto_stroppy_config_proto_rawDescGZIP(), []int{0, 0}
}

type LoggerConfig_LogLevel int32

const (
	LoggerConfig_LOG_LEVEL_DEBUG LoggerConfig_LogLevel = 0
	LoggerConfig_LOG_LEVEL_INFO  LoggerConfig_LogLevel = 1
	LoggerConfig_LOG_LEVEL_WARN  LoggerConfig_LogLevel = 2
	LoggerConfig_LOG_LEVEL_ERROR LoggerConfig_LogLevel = 3
	LoggerConfig_LOG_LEVEL_FATAL LoggerConfig_LogLevel = 4
)

// Enum value maps for LoggerConfig_LogLevel.
var (
	LoggerConfig_LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_DEBUG",
		1: "LOG_LEVEL_INFO",
		2: "LOG_LEVEL_WARN",
		3: "LOG_LEVEL_ERROR",
		4: "LOG_LEVEL_FATAL",
	}
	LoggerConfig_LogLevel_value = map[string]int32{
		"LOG_LEVEL_DEBUG": 0,
		"LOG_LEVEL_INFO":  1,
		"LOG_LEVEL_WARN":  2,
		"LOG_LEVEL_ERROR": 3,
		"LOG_LEVEL_FATAL": 4,
	}
)

func (x LoggerConfig_LogLevel) Enum() *LoggerConfig_LogLevel {
	p := new(LoggerConfig_LogLevel)
	*p = x
	return p
}

func (x LoggerConfig_LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoggerConfig_LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stroppy_config_proto_enumTypes[1].Descriptor()
}

func (LoggerConfig_LogLevel) Type() protoreflect.EnumType {
	return &file_proto_stroppy_config_proto_enumTypes[1]
}

func (x LoggerConfig_LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoggerConfig_LogLevel.Descriptor instead.
func (LoggerConfig_LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_stroppy_config_proto_rawDescGZIP(), []int{1, 0}
}

type LoggerConfig_LogMode int32

const (
	LoggerConfig_LOG_MODE_DEVELOPMENT LoggerConfig_LogMode = 0
	LoggerConfig_LOG_MODE_PRODUCTION  LoggerConfig_LogMode = 1
)

// Enum value maps for LoggerConfig_LogMode.
var (
	LoggerConfig_LogMode_name = map[int32]string{
		0: "LOG_MODE_DEVELOPMENT",
		1: "LOG_MODE_PRODUCTION",
	}
	LoggerConfig_LogMode_value = map[string]int32{
		"LOG_MODE_DEVELOPMENT": 0,
		"LOG_MODE_PRODUCTION":  1,
	}
)

func (x LoggerConfig_LogMode) Enum() *LoggerConfig_LogMode {
	p := new(LoggerConfig_LogMode)
	*p = x
	return p
}

func (x LoggerConfig_LogMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoggerConfig_LogMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stroppy_config_proto_enumTypes[2].Descriptor()
}

func (LoggerConfig_LogMode) Type() protoreflect.EnumType {
	return &file_proto_stroppy_config_proto_enumTypes[2]
}

func (x LoggerConfig_LogMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoggerConfig_LogMode.Descriptor instead.
func (LoggerConfig_LogMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_stroppy_config_proto_rawDescGZIP(), []int{1, 1}
}

// *
// DriverConfig contains configuration for connecting to a database driver.
// Driver is created as an empty shell via DriverX.create() and configured
// via driver.setup(config) at runtime. Sharing semantics are determined
// by the k6 lifecycle stage: init phase = shared, iteration = per-VU.
type DriverConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Database connection URL
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// * Name/Type of chosen driver
	DriverType DriverConfig_DriverType `protobuf:"varint,2,opt,name=driver_type,json=driverType,proto3,enum=stroppy.DriverConfig_DriverType" json:"driver_type,omitempty"`
	// * Driver-specific configuration, exactly one must match driver_type
	// Types that are valid to be assigned to DriverSpecific:
	//
	//	*DriverConfig_Postgres
	DriverSpecific isDriverConfig_DriverSpecific `protobuf_oneof:"driver_specific"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DriverConfig) Reset() {
	*x = DriverConfig{}
	mi := &file_proto_stroppy_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverConfig) ProtoMessage() {}

func (x *DriverConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stroppy_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverConfig.ProtoReflect.Descriptor instead.
func (*DriverConfig) Descriptor() ([]byte, []int) {
	return file_proto_stroppy_config_proto_rawDescGZIP(), []int{0}
}

func (x *DriverConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DriverConfig) GetDriverType() DriverConfig_DriverType {
	if x != nil {
		return x.DriverType
	}
	return DriverConfig_DRIVER_TYPE_UNSPECIFIED
}

func (x *DriverConfig) GetDriverSpecific() isDriverConfig_DriverSpecific {
	if x != nil {
		return x.DriverSpecific
	}
	return nil
}

func (x *DriverConfig) GetPostgres() *DriverConfig_PostgresConfig {
	if x != nil {
		if x, ok := x.DriverSpecific.(*DriverConfig_Postgres); ok {
			return x.Postgres
		}
	}
	return nil
}

type isDriverConfig_DriverSpecific interface {
	isDriverConfig_DriverSpecific()
}

type DriverConfig_Postgres struct {
	Postgres *DriverConfig_PostgresConfig `protobuf:"bytes,10,opt,name=postgres,proto3,oneof"`
}

func (*DriverConfig_Postgres) isDriverConfig_DriverSpecific() {}

// *
// LoggerConfig contains configuration for the logging system.
// It controls log levels and output formatting.
type LoggerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Minimum log level to output
	LogLevel LoggerConfig_LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=stroppy.LoggerConfig_LogLevel" json:"log_level,omitempty"`
	// * Logging mode (development or production)
	LogMode       LoggerConfig_LogMode `protobuf:"varint,2,opt,name=log_mode,json=logMode,proto3,enum=stroppy.LoggerConfig_LogMode" json:"log_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggerConfig) Reset() {
	*x = LoggerConfig{}
	mi := &file_proto_stroppy_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggerConfig) ProtoMessage() {}

func (x *LoggerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stroppy_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggerConfig.ProtoReflect.Descriptor instead.
func (*LoggerConfig) Descriptor() ([]byte, []int) {
	return file_proto_stroppy_config_proto_rawDescGZIP(), []int{1}
}

func (x *LoggerConfig) GetLogLevel() LoggerConfig_LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LoggerConfig_LOG_LEVEL_DEBUG
}

func (x *LoggerConfig) GetLogMode() LoggerConfig_LogMode {
	if x != nil {
		return x.LogMode
	}
	return LoggerConfig_LOG_MODE_DEVELOPMENT
}

// *
// OtlpExporterConfig contains named configuration for an OTLP exporter.
type ExporterConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Name of the OTLP exporter
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// * Configuration for the OTLP exporter
	OtlpExport    *OtlpExport `protobuf:"bytes,2,opt,name=otlp_export,json=otlpExport,proto3" json:"otlp_export,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterConfig) Reset() {
	*x = ExporterConfig{}
	mi := &file_proto_stroppy_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterConfig) ProtoMessage() {}

func (x *ExporterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stroppy_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterConfig.ProtoReflect.Descriptor instead.
func (*ExporterConfig) Descriptor() ([]byte, []int) {
	return file_proto_stroppy_config_proto_rawDescGZIP(), []int{2}
}

func (x *ExporterConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExporterConfig) GetOtlpExport() *OtlpExport {
	if x != nil {
		return x.OtlpExport
	}
	return nil
}

type GlobalConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Version of the configuration format e.g. proto files version.
	// This is used for backward compatibility of configs
	// and will be set automatically from binary run if not present.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// *
	// Run identifier for reproducible test runs or debugging
	// If set to "generate()" stroppy eval ulid for run_id
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// * Random seed for reproducible test runs
	Seed uint64 `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	// * Arbitrary metadata, may be passed to result labels and json output
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// * Logging configuration
	Logger *LoggerConfig `protobuf:"bytes,5,opt,name=logger,proto3" json:"logger,omitempty"`
	// * Exporter configuration
	Exporter      *ExporterConfig `protobuf:"bytes,6,opt,name=exporter,proto3" json:"exporter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	mi := &file_proto_stroppy_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stroppy_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfig.ProtoReflect.Descriptor instead.
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return file_proto_stroppy_config_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GlobalConfig) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GlobalConfig) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *GlobalConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GlobalConfig) GetLogger() *LoggerConfig {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *GlobalConfig) GetExporter() *ExporterConfig {
	if x != nil {
		return x.Exporter
	}
	return nil
}

// * PostgreSQL-specific pool and connection configuration
type DriverConfig_PostgresConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * pgx trace log level: debug, info, warn, error
	TraceLogLevel *string `protobuf:"bytes,1,opt,name=trace_log_level,json=traceLogLevel,proto3,oneof" json:"trace_log_level,omitempty"`
	// * Max connection lifetime (Go duration string, e.g. "1h")
	MaxConnLifetime *string `protobuf:"bytes,2,opt,name=max_conn_lifetime,json=maxConnLifetime,proto3,oneof" json:"max_conn_lifetime,omitempty"`
	// * Max connection idle time (Go duration string, e.g. "10m")
	MaxConnIdleTime *string `protobuf:"bytes,3,opt,name=max_conn_idle_time,json=maxConnIdleTime,proto3,oneof" json:"max_conn_idle_time,omitempty"`
	// * Maximum number of connections in the pool
	MaxConns *int32 `protobuf:"varint,4,opt,name=max_conns,json=maxConns,proto3,oneof" json:"max_conns,omitempty"`
	// * Minimum number of connections in the pool
	MinConns *int32 `protobuf:"varint,5,opt,name=min_conns,json=minConns,proto3,oneof" json:"min_conns,omitempty"`
	// * Minimum number of idle connections
	MinIdleConns *int32 `protobuf:"varint,6,opt,name=min_idle_conns,json=minIdleConns,proto3,oneof" json:"min_idle_conns,omitempty"`
	// * Query execution mode: exec, cache_statement, cache_describe,
	// describe_exec, simple_protocol
	DefaultQueryExecMode *string `protobuf:"bytes,7,opt,name=default_query_exec_mode,json=defaultQueryExecMode,proto3,oneof" json:"default_query_exec_mode,omitempty"`
	// * Description cache capacity (only with cache_describe mode)
	DescriptionCacheCapacity *int32 `protobuf:"varint,8,opt,name=description_cache_capacity,json=descriptionCacheCapacity,proto3,oneof" json:"description_cache_capacity,omitempty"`
	// * Statement cache capacity (only with cache_statement mode)
	StatementCacheCapacity *int32 `protobuf:"varint,9,opt,name=statement_cache_capacity,json=statementCacheCapacity,proto3,oneof" json:"statement_cache_capacity,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DriverConfig_PostgresConfig) Reset() {
	*x = DriverConfig_PostgresConfig{}
	mi := &file_proto_stroppy_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverConfig_PostgresConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverConfig_PostgresConfig) ProtoMessage() {}

func (x *DriverConfig_PostgresConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stroppy_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverConfig_PostgresConfig.ProtoReflect.Descriptor instead.
func (*DriverConfig_PostgresConfig) Descriptor() ([]byte, []int) {
	return file_proto_stroppy_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DriverConfig_PostgresConfig) GetTraceLogLevel() string {
	if x != nil && x.TraceLogLevel != nil {
		return *x.TraceLogLevel
	}
	return ""
}

func (x *DriverConfig_PostgresConfig) GetMaxConnLifetime() string {
	if x != nil && x.MaxConnLifetime != nil {
		return *x.MaxConnLifetime
	}
	return ""
}

func (x *DriverConfig_PostgresConfig) GetMaxConnIdleTime() string {
	if x != nil && x.MaxConnIdleTime != nil {
		return *x.MaxConnIdleTime
	}
	return ""
}

func (x *DriverConfig_PostgresConfig) GetMaxConns() int32 {
	if x != nil && x.MaxConns != nil {
		return *x.MaxConns
	}
	return 0
}

func (x *DriverConfig_PostgresConfig) GetMinConns() int32 {
	if x != nil && x.MinConns != nil {
		return *x.MinConns
	}
	return 0
}

func (x *DriverConfig_PostgresConfig) GetMinIdleConns() int32 {
	if x != nil && x.MinIdleConns != nil {
		return *x.MinIdleConns
	}
	return 0
}

func (x *DriverConfig_PostgresConfig) GetDefaultQueryExecMode() string {
	if x != nil && x.DefaultQueryExecMode != nil {
		return *x.DefaultQueryExecMode
	}
	return ""
}

func (x *DriverConfig_PostgresConfig) GetDescriptionCacheCapacity() int32 {
	if x != nil && x.DescriptionCacheCapacity != nil {
		return *x.DescriptionCacheCapacity
	}
	return 0
}

func (x *DriverConfig_PostgresConfig) GetStatementCacheCapacity() int32 {
	if x != nil && x.StatementCacheCapacity != nil {
		return *x.StatementCacheCapacity
	}
	return 0
}

var File_proto_stroppy_config_proto protoreflect.FileDescriptor

const file_proto_stroppy_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/stroppy/config.proto\x12\astroppy\x1a\x1aproto/stroppy/common.proto\x1a\x17validate/validate.proto\"\xab\a\n" +
	"\fDriverConfig\x12\x1a\n" +
	"\x03url\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x90\x01\x01R\x03url\x12K\n" +
	"\vdriver_type\x18\x02 \x01(\x0e2 .stroppy.DriverConfig.DriverTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\n" +
	"driverType\x12B\n" +
	"\bpostgres\x18\n" +
	" \x01(\v2$.stroppy.DriverConfig.PostgresConfigH\x00R\bpostgres\x1a\x95\x05\n" +
	"\x0ePostgresConfig\x12+\n" +
	"\x0ftrace_log_level\x18\x01 \x01(\tH\x00R\rtraceLogLevel\x88\x01\x01\x12/\n" +
	"\x11max_conn_lifetime\x18\x02 \x01(\tH\x01R\x0fmaxConnLifetime\x88\x01\x01\x120\n" +
	"\x12max_conn_idle_time\x18\x03 \x01(\tH\x02R\x0fmaxConnIdleTime\x88\x01\x01\x12 \n" +
	"\tmax_conns\x18\x04 \x01(\x05H\x03R\bmaxConns\x88\x01\x01\x12 \n" +
	"\tmin_conns\x18\x05 \x01(\x05H\x04R\bminConns\x88\x01\x01\x12)\n" +
	"\x0emin_idle_conns\x18\x06 \x01(\x05H\x05R\fminIdleConns\x88\x01\x01\x12:\n" +
	"\x17default_query_exec_mode\x18\a \x01(\tH\x06R\x14defaultQueryExecMode\x88\x01\x01\x12A\n" +
	"\x1adescription_cache_capacity\x18\b \x01(\x05H\aR\x18descriptionCacheCapacity\x88\x01\x01\x12=\n" +
	"\x18statement_cache_capacity\x18\t \x01(\x05H\bR\x16statementCacheCapacity\x88\x01\x01B\x12\n" +
	"\x10_trace_log_levelB\x14\n" +
	"\x12_max_conn_lifetimeB\x15\n" +
	"\x13_max_conn_idle_timeB\f\n" +
	"\n" +
	"_max_connsB\f\n" +
	"\n" +
	"_min_connsB\x11\n" +
	"\x0f_min_idle_connsB\x1a\n" +
	"\x18_default_query_exec_modeB\x1d\n" +
	"\x1b_description_cache_capacityB\x1b\n" +
	"\x19_statement_cache_capacity\"C\n" +
	"\n" +
	"DriverType\x12\x1b\n" +
	"\x17DRIVER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DRIVER_TYPE_POSTGRES\x10\x01B\x11\n" +
	"\x0fdriver_specific\"\xca\x02\n" +
	"\fLoggerConfig\x12E\n" +
	"\tlog_level\x18\x01 \x01(\x0e2\x1e.stroppy.LoggerConfig.LogLevelB\b\xfaB\x05\x82\x01\x02\x10\x01R\blogLevel\x12B\n" +
	"\blog_mode\x18\x02 \x01(\x0e2\x1d.stroppy.LoggerConfig.LogModeB\b\xfaB\x05\x82\x01\x02\x10\x01R\alogMode\"q\n" +
	"\bLogLevel\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x00\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x02\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_FATAL\x10\x04\"<\n" +
	"\aLogMode\x12\x18\n" +
	"\x14LOG_MODE_DEVELOPMENT\x10\x00\x12\x17\n" +
	"\x13LOG_MODE_PRODUCTION\x10\x01\"m\n" +
	"\x0eExporterConfig\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12>\n" +
	"\votlp_export\x18\x02 \x01(\v2\x13.stroppy.OtlpExportB\b\xfaB\x05\x8a\x01\x02\x10\x01R\n" +
	"otlpExport\"\xbe\x02\n" +
	"\fGlobalConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\x04seed\x18\x03 \x01(\x04B\a\xfaB\x042\x02(\x00R\x04seed\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.stroppy.GlobalConfig.MetadataEntryR\bmetadata\x12-\n" +
	"\x06logger\x18\x05 \x01(\v2\x15.stroppy.LoggerConfigR\x06logger\x123\n" +
	"\bexporter\x18\x06 \x01(\v2\x17.stroppy.ExporterConfigR\bexporter\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B8Z6github.com/stroppy-io/stroppy/pkg/common/proto/stroppyb\x06proto3"

var (
	file_proto_stroppy_config_proto_rawDescOnce sync.Once
	file_proto_stroppy_config_proto_rawDescData []byte
)

func file_proto_stroppy_config_proto_rawDescGZIP() []byte {
	file_proto_stroppy_config_proto_rawDescOnce.Do(func() {
		file_proto_stroppy_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stroppy_config_proto_rawDesc), len(file_proto_stroppy_config_proto_rawDesc)))
	})
	return file_proto_stroppy_config_proto_rawDescData
}

var file_proto_stroppy_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_stroppy_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_stroppy_config_proto_goTypes = []any{
	(DriverConfig_DriverType)(0),        // 0: stroppy.DriverConfig.DriverType
	(LoggerConfig_LogLevel)(0),          // 1: stroppy.LoggerConfig.LogLevel
	(LoggerConfig_LogMode)(0),           // 2: stroppy.LoggerConfig.LogMode
	(*DriverConfig)(nil),                // 3: stroppy.DriverConfig
	(*LoggerConfig)(nil),                // 4: stroppy.LoggerConfig
	(*ExporterConfig)(nil),              // 5: stroppy.ExporterConfig
	(*GlobalConfig)(nil),                // 6: stroppy.GlobalConfig
	(*DriverConfig_PostgresConfig)(nil), // 7: stroppy.DriverConfig.PostgresConfig
	nil,                                 // 8: stroppy.GlobalConfig.MetadataEntry
	(*OtlpExport)(nil),                  // 9: stroppy.OtlpExport
}
var file_proto_stroppy_config_proto_depIdxs = []int32{
	0, // 0: stroppy.DriverConfig.driver_type:type_name -> stroppy.DriverConfig.DriverType
	7, // 1: stroppy.DriverConfig.postgres:type_name -> stroppy.DriverConfig.PostgresConfig
	1, // 2: stroppy.LoggerConfig.log_level:type_name -> stroppy.LoggerConfig.LogLevel
	2, // 3: stroppy.LoggerConfig.log_mode:type_name -> stroppy.LoggerConfig.LogMode
	9, // 4: stroppy.ExporterConfig.otlp_export:type_name -> stroppy.OtlpExport
	8, // 5: stroppy.GlobalConfig.metadata:type_name -> stroppy.GlobalConfig.MetadataEntry
	4, // 6: stroppy.GlobalConfig.logger:type_name -> stroppy.LoggerConfig
	5, // 7: stroppy.GlobalConfig.exporter:type_name -> stroppy.ExporterConfig
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_stroppy_config_proto_init() }
func file_proto_stroppy_config_proto_init() {
	if File_proto_stroppy_config_proto != nil {
		return
	}
	file_proto_stroppy_common_proto_init()
	file_proto_stroppy_config_proto_msgTypes[0].OneofWrappers = []any{
		(*DriverConfig_Postgres)(nil),
	}
	file_proto_stroppy_config_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stroppy_config_proto_rawDesc), len(file_proto_stroppy_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stroppy_config_proto_goTypes,
		DependencyIndexes: file_proto_stroppy_config_proto_depIdxs,
		EnumInfos:         file_proto_stroppy_config_proto_enumTypes,
		MessageInfos:      file_proto_stroppy_config_proto_msgTypes,
	}.Build()
	File_proto_stroppy_config_proto = out.File
	file_proto_stroppy_config_proto_goTypes = nil
	file_proto_stroppy_config_proto_depIdxs = nil
}
