// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/stroppy/run.proto

package stroppy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// DriverRunConfig is the user-facing driver configuration for the stroppy config file.
// It mirrors the TypeScript DriverSetup interface so that protojson serialization
// (camelCase field names, string values) is directly readable by declareDriverSetup()
// in the TypeScript layer via the STROPPY_DRIVER_N environment variable.
//
// This is intentionally separate from DriverConfig (the runtime binary proto for TS->Go dispatch).
type DriverRunConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Driver type. One of: "postgres", "mysql", "picodata", "ydb", "noop".
	// Matches TS DriverSetup.driverType (string union, not proto enum).
	DriverType string `protobuf:"bytes,1,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"`
	// * Database connection URL
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// *
	// Default insert method. One of: "native", "plain_bulk", "plain_query".
	// Matches TS DriverSetup.defaultInsertMethod.
	DefaultInsertMethod string                      `protobuf:"bytes,3,opt,name=default_insert_method,json=defaultInsertMethod,proto3" json:"default_insert_method,omitempty"`
	Pool                *DriverRunConfig_PoolConfig `protobuf:"bytes,4,opt,name=pool,proto3,oneof" json:"pool,omitempty"`
	// *
	// Error handling mode. One of: "silent", "log", "throw", "fail", "abort".
	// Matches TS DriverSetup.errorMode.
	ErrorMode string `protobuf:"bytes,5,opt,name=error_mode,json=errorMode,proto3" json:"error_mode,omitempty"`
	// * Rows per bulk INSERT statement. Matches TS DriverSetup.bulkSize.
	BulkSize *int32 `protobuf:"varint,6,opt,name=bulk_size,json=bulkSize,proto3,oneof" json:"bulk_size,omitempty"`
	// * Path to CA certificate PEM file. Matches TS DriverSetup.caCertFile.
	CaCertFile *string `protobuf:"bytes,7,opt,name=ca_cert_file,json=caCertFile,proto3,oneof" json:"ca_cert_file,omitempty"`
	// * Authentication token (e.g. IAM token). Matches TS DriverSetup.authToken.
	AuthToken *string `protobuf:"bytes,8,opt,name=auth_token,json=authToken,proto3,oneof" json:"auth_token,omitempty"`
	// * Username for static credentials. Matches TS DriverSetup.authUser.
	AuthUser *string `protobuf:"bytes,9,opt,name=auth_user,json=authUser,proto3,oneof" json:"auth_user,omitempty"`
	// * Password for static credentials. Matches TS DriverSetup.authPassword.
	AuthPassword *string `protobuf:"bytes,10,opt,name=auth_password,json=authPassword,proto3,oneof" json:"auth_password,omitempty"`
	// * Skip TLS certificate verification. Matches TS DriverSetup.tlsInsecureSkipVerify.
	TlsInsecureSkipVerify *bool `protobuf:"varint,11,opt,name=tls_insecure_skip_verify,json=tlsInsecureSkipVerify,proto3,oneof" json:"tls_insecure_skip_verify,omitempty"`
	// *
	// Default transaction isolation level.
	// One of: "read_uncommitted", "read_committed", "repeatable_read", "serializable".
	// Matches TS DriverSetup.defaultTxIsolation.
	DefaultTxIsolation string `protobuf:"bytes,12,opt,name=default_tx_isolation,json=defaultTxIsolation,proto3" json:"default_tx_isolation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DriverRunConfig) Reset() {
	*x = DriverRunConfig{}
	mi := &file_proto_stroppy_run_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRunConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRunConfig) ProtoMessage() {}

func (x *DriverRunConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stroppy_run_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRunConfig.ProtoReflect.Descriptor instead.
func (*DriverRunConfig) Descriptor() ([]byte, []int) {
	return file_proto_stroppy_run_proto_rawDescGZIP(), []int{0}
}

func (x *DriverRunConfig) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *DriverRunConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DriverRunConfig) GetDefaultInsertMethod() string {
	if x != nil {
		return x.DefaultInsertMethod
	}
	return ""
}

func (x *DriverRunConfig) GetPool() *DriverRunConfig_PoolConfig {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *DriverRunConfig) GetErrorMode() string {
	if x != nil {
		return x.ErrorMode
	}
	return ""
}

func (x *DriverRunConfig) GetBulkSize() int32 {
	if x != nil && x.BulkSize != nil {
		return *x.BulkSize
	}
	return 0
}

func (x *DriverRunConfig) GetCaCertFile() string {
	if x != nil && x.CaCertFile != nil {
		return *x.CaCertFile
	}
	return ""
}

func (x *DriverRunConfig) GetAuthToken() string {
	if x != nil && x.AuthToken != nil {
		return *x.AuthToken
	}
	return ""
}

func (x *DriverRunConfig) GetAuthUser() string {
	if x != nil && x.AuthUser != nil {
		return *x.AuthUser
	}
	return ""
}

func (x *DriverRunConfig) GetAuthPassword() string {
	if x != nil && x.AuthPassword != nil {
		return *x.AuthPassword
	}
	return ""
}

func (x *DriverRunConfig) GetTlsInsecureSkipVerify() bool {
	if x != nil && x.TlsInsecureSkipVerify != nil {
		return *x.TlsInsecureSkipVerify
	}
	return false
}

func (x *DriverRunConfig) GetDefaultTxIsolation() string {
	if x != nil {
		return x.DefaultTxIsolation
	}
	return ""
}

// *
// RunConfig is the top-level stroppy config file schema.
//
// Default file: ./stroppy-config.json (auto-discovered by stroppy run and stroppy probe).
// Override with -f/--file flag.
//
// Precedence (highest to lowest):
//
//	real env > -e flags > this file > -d/-D presets > script defaults
//
// Example (stroppy-config.json):
//
//	{
//	  "version": "1",
//	  "script": "tpcc",
//	  "global": {
//	    "logger": { "logLevel": "LOG_LEVEL_INFO" }
//	  },
//	  "drivers": {
//	    "0": { "driverType": "postgres", "url": "postgres://user:pass@db:5432/bench",
//	            "pool": { "maxConns": 200 } }
//	  },
//	  "env": { "WAREHOUSES": "10" },
//	  "k6Args": ["--vus", "10", "--duration", "30m"]
//	}
type RunConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * Config file format version. Currently "1".
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// *
	// Script to run: preset name (e.g. "tpcc"), .ts path, .sql path, or inline SQL.
	// If omitted, the first CLI positional argument is used.
	Script *string `protobuf:"bytes,2,opt,name=script,proto3,oneof" json:"script,omitempty"`
	// *
	// SQL file: path or name. If omitted, auto-resolved from script/preset.
	Sql *string `protobuf:"bytes,3,opt,name=sql,proto3,oneof" json:"sql,omitempty"`
	// *
	// Global stroppy settings: logger level/mode, OTEL exporter, seed, run_id, metadata.
	// These activate the previously-dead GlobalConfig plumbing.
	Global *GlobalConfig `protobuf:"bytes,4,opt,name=global,proto3" json:"global,omitempty"`
	// *
	// Driver configurations indexed by driver number (0-based string key in JSON).
	// Equivalent to -d/-D CLI flags but type-safe and with full pool config support.
	// CLI -d/-D takes precedence over entries here.
	Drivers map[uint32]*DriverRunConfig `protobuf:"bytes,5,rep,name=drivers,proto3" json:"drivers,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// *
	// Environment variable overrides for the k6 script.
	// Equivalent to -e KEY=VALUE. All keys are uppercased on load.
	// Precedence: real env > -e flags > this map > script ENV() defaults.
	Env map[string]string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// *
	// Step allowlist. Equivalent to --steps.
	// CLI --steps takes precedence; this is used only when --steps is absent.
	Steps []string `protobuf:"bytes,7,rep,name=steps,proto3" json:"steps,omitempty"`
	// *
	// Step blocklist. Equivalent to --no-steps.
	// CLI --no-steps takes precedence; this is used only when --no-steps is absent.
	NoSteps []string `protobuf:"bytes,8,rep,name=no_steps,json=noSteps,proto3" json:"no_steps,omitempty"`
	// *
	// Additional raw args passed directly to "k6 run".
	// Placed before CLI -- args, so CLI args can override (last-wins for most k6 flags).
	// Example: ["--vus", "10", "--duration", "30m"]
	K6Args []string `protobuf:"bytes,9,rep,name=k6_args,json=k6Args,proto3" json:"k6_args,omitempty"`
	// *
	// Optional path to a k6 native config JSON file.
	// If set, "--config <path>" is prepended to k6 run args.
	// Useful for setting scenarios, thresholds, or other options not available via CLI flags.
	K6Config      *string `protobuf:"bytes,10,opt,name=k6_config,json=k6Config,proto3,oneof" json:"k6_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunConfig) Reset() {
	*x = RunConfig{}
	mi := &file_proto_stroppy_run_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunConfig) ProtoMessage() {}

func (x *RunConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stroppy_run_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunConfig.ProtoReflect.Descriptor instead.
func (*RunConfig) Descriptor() ([]byte, []int) {
	return file_proto_stroppy_run_proto_rawDescGZIP(), []int{1}
}

func (x *RunConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RunConfig) GetScript() string {
	if x != nil && x.Script != nil {
		return *x.Script
	}
	return ""
}

func (x *RunConfig) GetSql() string {
	if x != nil && x.Sql != nil {
		return *x.Sql
	}
	return ""
}

func (x *RunConfig) GetGlobal() *GlobalConfig {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *RunConfig) GetDrivers() map[uint32]*DriverRunConfig {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *RunConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunConfig) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RunConfig) GetNoSteps() []string {
	if x != nil {
		return x.NoSteps
	}
	return nil
}

func (x *RunConfig) GetK6Args() []string {
	if x != nil {
		return x.K6Args
	}
	return nil
}

func (x *RunConfig) GetK6Config() string {
	if x != nil && x.K6Config != nil {
		return *x.K6Config
	}
	return ""
}

// *
// Pool configuration. Sugar field that maps to PostgresConfig or SqlConfig
// in the TypeScript layer based on driver_type.
// Matches TS DriverSetup.pool (PoolConfig).
type DriverRunConfig_PoolConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pgx / postgres pool fields
	MaxConns                 *int32  `protobuf:"varint,1,opt,name=max_conns,json=maxConns,proto3,oneof" json:"max_conns,omitempty"`
	MinConns                 *int32  `protobuf:"varint,2,opt,name=min_conns,json=minConns,proto3,oneof" json:"min_conns,omitempty"`
	MinIdleConns             *int32  `protobuf:"varint,3,opt,name=min_idle_conns,json=minIdleConns,proto3,oneof" json:"min_idle_conns,omitempty"`
	MaxConnLifetime          *string `protobuf:"bytes,4,opt,name=max_conn_lifetime,json=maxConnLifetime,proto3,oneof" json:"max_conn_lifetime,omitempty"`
	MaxConnIdleTime          *string `protobuf:"bytes,5,opt,name=max_conn_idle_time,json=maxConnIdleTime,proto3,oneof" json:"max_conn_idle_time,omitempty"`
	TraceLogLevel            *string `protobuf:"bytes,6,opt,name=trace_log_level,json=traceLogLevel,proto3,oneof" json:"trace_log_level,omitempty"`
	DefaultQueryExecMode     *string `protobuf:"bytes,7,opt,name=default_query_exec_mode,json=defaultQueryExecMode,proto3,oneof" json:"default_query_exec_mode,omitempty"`
	DescriptionCacheCapacity *int32  `protobuf:"varint,8,opt,name=description_cache_capacity,json=descriptionCacheCapacity,proto3,oneof" json:"description_cache_capacity,omitempty"`
	StatementCacheCapacity   *int32  `protobuf:"varint,9,opt,name=statement_cache_capacity,json=statementCacheCapacity,proto3,oneof" json:"statement_cache_capacity,omitempty"`
	// database/sql pool fields (mysql, ydb)
	MaxOpenConns    *int32  `protobuf:"varint,10,opt,name=max_open_conns,json=maxOpenConns,proto3,oneof" json:"max_open_conns,omitempty"`
	MaxIdleConns    *int32  `protobuf:"varint,11,opt,name=max_idle_conns,json=maxIdleConns,proto3,oneof" json:"max_idle_conns,omitempty"`
	ConnMaxLifetime *string `protobuf:"bytes,12,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3,oneof" json:"conn_max_lifetime,omitempty"`
	ConnMaxIdleTime *string `protobuf:"bytes,13,opt,name=conn_max_idle_time,json=connMaxIdleTime,proto3,oneof" json:"conn_max_idle_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DriverRunConfig_PoolConfig) Reset() {
	*x = DriverRunConfig_PoolConfig{}
	mi := &file_proto_stroppy_run_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRunConfig_PoolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRunConfig_PoolConfig) ProtoMessage() {}

func (x *DriverRunConfig_PoolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stroppy_run_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRunConfig_PoolConfig.ProtoReflect.Descriptor instead.
func (*DriverRunConfig_PoolConfig) Descriptor() ([]byte, []int) {
	return file_proto_stroppy_run_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DriverRunConfig_PoolConfig) GetMaxConns() int32 {
	if x != nil && x.MaxConns != nil {
		return *x.MaxConns
	}
	return 0
}

func (x *DriverRunConfig_PoolConfig) GetMinConns() int32 {
	if x != nil && x.MinConns != nil {
		return *x.MinConns
	}
	return 0
}

func (x *DriverRunConfig_PoolConfig) GetMinIdleConns() int32 {
	if x != nil && x.MinIdleConns != nil {
		return *x.MinIdleConns
	}
	return 0
}

func (x *DriverRunConfig_PoolConfig) GetMaxConnLifetime() string {
	if x != nil && x.MaxConnLifetime != nil {
		return *x.MaxConnLifetime
	}
	return ""
}

func (x *DriverRunConfig_PoolConfig) GetMaxConnIdleTime() string {
	if x != nil && x.MaxConnIdleTime != nil {
		return *x.MaxConnIdleTime
	}
	return ""
}

func (x *DriverRunConfig_PoolConfig) GetTraceLogLevel() string {
	if x != nil && x.TraceLogLevel != nil {
		return *x.TraceLogLevel
	}
	return ""
}

func (x *DriverRunConfig_PoolConfig) GetDefaultQueryExecMode() string {
	if x != nil && x.DefaultQueryExecMode != nil {
		return *x.DefaultQueryExecMode
	}
	return ""
}

func (x *DriverRunConfig_PoolConfig) GetDescriptionCacheCapacity() int32 {
	if x != nil && x.DescriptionCacheCapacity != nil {
		return *x.DescriptionCacheCapacity
	}
	return 0
}

func (x *DriverRunConfig_PoolConfig) GetStatementCacheCapacity() int32 {
	if x != nil && x.StatementCacheCapacity != nil {
		return *x.StatementCacheCapacity
	}
	return 0
}

func (x *DriverRunConfig_PoolConfig) GetMaxOpenConns() int32 {
	if x != nil && x.MaxOpenConns != nil {
		return *x.MaxOpenConns
	}
	return 0
}

func (x *DriverRunConfig_PoolConfig) GetMaxIdleConns() int32 {
	if x != nil && x.MaxIdleConns != nil {
		return *x.MaxIdleConns
	}
	return 0
}

func (x *DriverRunConfig_PoolConfig) GetConnMaxLifetime() string {
	if x != nil && x.ConnMaxLifetime != nil {
		return *x.ConnMaxLifetime
	}
	return ""
}

func (x *DriverRunConfig_PoolConfig) GetConnMaxIdleTime() string {
	if x != nil && x.ConnMaxIdleTime != nil {
		return *x.ConnMaxIdleTime
	}
	return ""
}

var File_proto_stroppy_run_proto protoreflect.FileDescriptor

const file_proto_stroppy_run_proto_rawDesc = "" +
	"\n" +
	"\x17proto/stroppy/run.proto\x12\astroppy\x1a\x1aproto/stroppy/config.proto\"\x92\f\n" +
	"\x0fDriverRunConfig\x12\x1f\n" +
	"\vdriver_type\x18\x01 \x01(\tR\n" +
	"driverType\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x122\n" +
	"\x15default_insert_method\x18\x03 \x01(\tR\x13defaultInsertMethod\x12<\n" +
	"\x04pool\x18\x04 \x01(\v2#.stroppy.DriverRunConfig.PoolConfigH\x00R\x04pool\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"error_mode\x18\x05 \x01(\tR\terrorMode\x12 \n" +
	"\tbulk_size\x18\x06 \x01(\x05H\x01R\bbulkSize\x88\x01\x01\x12%\n" +
	"\fca_cert_file\x18\a \x01(\tH\x02R\n" +
	"caCertFile\x88\x01\x01\x12\"\n" +
	"\n" +
	"auth_token\x18\b \x01(\tH\x03R\tauthToken\x88\x01\x01\x12 \n" +
	"\tauth_user\x18\t \x01(\tH\x04R\bauthUser\x88\x01\x01\x12(\n" +
	"\rauth_password\x18\n" +
	" \x01(\tH\x05R\fauthPassword\x88\x01\x01\x12<\n" +
	"\x18tls_insecure_skip_verify\x18\v \x01(\bH\x06R\x15tlsInsecureSkipVerify\x88\x01\x01\x120\n" +
	"\x14default_tx_isolation\x18\f \x01(\tR\x12defaultTxIsolation\x1a\x9d\a\n" +
	"\n" +
	"PoolConfig\x12 \n" +
	"\tmax_conns\x18\x01 \x01(\x05H\x00R\bmaxConns\x88\x01\x01\x12 \n" +
	"\tmin_conns\x18\x02 \x01(\x05H\x01R\bminConns\x88\x01\x01\x12)\n" +
	"\x0emin_idle_conns\x18\x03 \x01(\x05H\x02R\fminIdleConns\x88\x01\x01\x12/\n" +
	"\x11max_conn_lifetime\x18\x04 \x01(\tH\x03R\x0fmaxConnLifetime\x88\x01\x01\x120\n" +
	"\x12max_conn_idle_time\x18\x05 \x01(\tH\x04R\x0fmaxConnIdleTime\x88\x01\x01\x12+\n" +
	"\x0ftrace_log_level\x18\x06 \x01(\tH\x05R\rtraceLogLevel\x88\x01\x01\x12:\n" +
	"\x17default_query_exec_mode\x18\a \x01(\tH\x06R\x14defaultQueryExecMode\x88\x01\x01\x12A\n" +
	"\x1adescription_cache_capacity\x18\b \x01(\x05H\aR\x18descriptionCacheCapacity\x88\x01\x01\x12=\n" +
	"\x18statement_cache_capacity\x18\t \x01(\x05H\bR\x16statementCacheCapacity\x88\x01\x01\x12)\n" +
	"\x0emax_open_conns\x18\n" +
	" \x01(\x05H\tR\fmaxOpenConns\x88\x01\x01\x12)\n" +
	"\x0emax_idle_conns\x18\v \x01(\x05H\n" +
	"R\fmaxIdleConns\x88\x01\x01\x12/\n" +
	"\x11conn_max_lifetime\x18\f \x01(\tH\vR\x0fconnMaxLifetime\x88\x01\x01\x120\n" +
	"\x12conn_max_idle_time\x18\r \x01(\tH\fR\x0fconnMaxIdleTime\x88\x01\x01B\f\n" +
	"\n" +
	"_max_connsB\f\n" +
	"\n" +
	"_min_connsB\x11\n" +
	"\x0f_min_idle_connsB\x14\n" +
	"\x12_max_conn_lifetimeB\x15\n" +
	"\x13_max_conn_idle_timeB\x12\n" +
	"\x10_trace_log_levelB\x1a\n" +
	"\x18_default_query_exec_modeB\x1d\n" +
	"\x1b_description_cache_capacityB\x1b\n" +
	"\x19_statement_cache_capacityB\x11\n" +
	"\x0f_max_open_connsB\x11\n" +
	"\x0f_max_idle_connsB\x14\n" +
	"\x12_conn_max_lifetimeB\x15\n" +
	"\x13_conn_max_idle_timeB\a\n" +
	"\x05_poolB\f\n" +
	"\n" +
	"_bulk_sizeB\x0f\n" +
	"\r_ca_cert_fileB\r\n" +
	"\v_auth_tokenB\f\n" +
	"\n" +
	"_auth_userB\x10\n" +
	"\x0e_auth_passwordB\x1b\n" +
	"\x19_tls_insecure_skip_verify\"\x8d\x04\n" +
	"\tRunConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1b\n" +
	"\x06script\x18\x02 \x01(\tH\x00R\x06script\x88\x01\x01\x12\x15\n" +
	"\x03sql\x18\x03 \x01(\tH\x01R\x03sql\x88\x01\x01\x12-\n" +
	"\x06global\x18\x04 \x01(\v2\x15.stroppy.GlobalConfigR\x06global\x129\n" +
	"\adrivers\x18\x05 \x03(\v2\x1f.stroppy.RunConfig.DriversEntryR\adrivers\x12-\n" +
	"\x03env\x18\x06 \x03(\v2\x1b.stroppy.RunConfig.EnvEntryR\x03env\x12\x14\n" +
	"\x05steps\x18\a \x03(\tR\x05steps\x12\x19\n" +
	"\bno_steps\x18\b \x03(\tR\anoSteps\x12\x17\n" +
	"\ak6_args\x18\t \x03(\tR\x06k6Args\x12 \n" +
	"\tk6_config\x18\n" +
	" \x01(\tH\x02R\bk6Config\x88\x01\x01\x1aT\n" +
	"\fDriversEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.stroppy.DriverRunConfigR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_scriptB\x06\n" +
	"\x04_sqlB\f\n" +
	"\n" +
	"_k6_configB8Z6github.com/stroppy-io/stroppy/pkg/common/proto/stroppyb\x06proto3"

var (
	file_proto_stroppy_run_proto_rawDescOnce sync.Once
	file_proto_stroppy_run_proto_rawDescData []byte
)

func file_proto_stroppy_run_proto_rawDescGZIP() []byte {
	file_proto_stroppy_run_proto_rawDescOnce.Do(func() {
		file_proto_stroppy_run_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stroppy_run_proto_rawDesc), len(file_proto_stroppy_run_proto_rawDesc)))
	})
	return file_proto_stroppy_run_proto_rawDescData
}

var file_proto_stroppy_run_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_stroppy_run_proto_goTypes = []any{
	(*DriverRunConfig)(nil),            // 0: stroppy.DriverRunConfig
	(*RunConfig)(nil),                  // 1: stroppy.RunConfig
	(*DriverRunConfig_PoolConfig)(nil), // 2: stroppy.DriverRunConfig.PoolConfig
	nil,                                // 3: stroppy.RunConfig.DriversEntry
	nil,                                // 4: stroppy.RunConfig.EnvEntry
	(*GlobalConfig)(nil),               // 5: stroppy.GlobalConfig
}
var file_proto_stroppy_run_proto_depIdxs = []int32{
	2, // 0: stroppy.DriverRunConfig.pool:type_name -> stroppy.DriverRunConfig.PoolConfig
	5, // 1: stroppy.RunConfig.global:type_name -> stroppy.GlobalConfig
	3, // 2: stroppy.RunConfig.drivers:type_name -> stroppy.RunConfig.DriversEntry
	4, // 3: stroppy.RunConfig.env:type_name -> stroppy.RunConfig.EnvEntry
	0, // 4: stroppy.RunConfig.DriversEntry.value:type_name -> stroppy.DriverRunConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_stroppy_run_proto_init() }
func file_proto_stroppy_run_proto_init() {
	if File_proto_stroppy_run_proto != nil {
		return
	}
	file_proto_stroppy_config_proto_init()
	file_proto_stroppy_run_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_stroppy_run_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_stroppy_run_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stroppy_run_proto_rawDesc), len(file_proto_stroppy_run_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stroppy_run_proto_goTypes,
		DependencyIndexes: file_proto_stroppy_run_proto_depIdxs,
		MessageInfos:      file_proto_stroppy_run_proto_msgTypes,
	}.Build()
	File_proto_stroppy_run_proto = out.File
	file_proto_stroppy_run_proto_goTypes = nil
	file_proto_stroppy_run_proto_depIdxs = nil
}
