// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.26.1
// source: crossplane/api.proto

package crossplane

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ResourceDef           `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	WaitForSync   bool                   `protobuf:"varint,2,opt,name=wait_for_sync,json=waitForSync,proto3" json:"wait_for_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_crossplane_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_crossplane_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateResourceRequest) GetResource() *ResourceDef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CreateResourceRequest) GetWaitForSync() bool {
	if x != nil {
		return x.WaitForSync
	}
	return false
}

type CreateResourcesManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*ResourceDef         `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	WaitForSync   bool                   `protobuf:"varint,2,opt,name=wait_for_sync,json=waitForSync,proto3" json:"wait_for_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourcesManyRequest) Reset() {
	*x = CreateResourcesManyRequest{}
	mi := &file_crossplane_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourcesManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourcesManyRequest) ProtoMessage() {}

func (x *CreateResourcesManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourcesManyRequest.ProtoReflect.Descriptor instead.
func (*CreateResourcesManyRequest) Descriptor() ([]byte, []int) {
	return file_crossplane_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResourcesManyRequest) GetResources() []*ResourceDef {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CreateResourcesManyRequest) GetWaitForSync() bool {
	if x != nil {
		return x.WaitForSync
	}
	return false
}

type CreateResourcesManyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*ResourceWithStatus  `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourcesManyResponse) Reset() {
	*x = CreateResourcesManyResponse{}
	mi := &file_crossplane_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourcesManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourcesManyResponse) ProtoMessage() {}

func (x *CreateResourcesManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourcesManyResponse.ProtoReflect.Descriptor instead.
func (*CreateResourcesManyResponse) Descriptor() ([]byte, []int) {
	return file_crossplane_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResourcesManyResponse) GetResponses() []*ResourceWithStatus {
	if x != nil {
		return x.Responses
	}
	return nil
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	WaitForSync   bool                   `protobuf:"varint,2,opt,name=wait_for_sync,json=waitForSync,proto3" json:"wait_for_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_crossplane_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_crossplane_api_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResourceRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *DeleteResourceRequest) GetWaitForSync() bool {
	if x != nil {
		return x.WaitForSync
	}
	return false
}

type GetResourceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceStatusRequest) Reset() {
	*x = GetResourceStatusRequest{}
	mi := &file_crossplane_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceStatusRequest) ProtoMessage() {}

func (x *GetResourceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetResourceStatusRequest) Descriptor() ([]byte, []int) {
	return file_crossplane_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetResourceStatusRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Synced        bool                   `protobuf:"varint,1,opt,name=synced,proto3" json:"synced,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_crossplane_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_crossplane_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResourceResponse) GetSynced() bool {
	if x != nil {
		return x.Synced
	}
	return false
}

func (x *DeleteResourceResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_crossplane_api_proto protoreflect.FileDescriptor

const file_crossplane_api_proto_rawDesc = "" +
	"\n" +
	"\x14crossplane/api.proto\x12\n" +
	"crossplane\x1a\x1bcrossplane/crossplane.proto\x1a\x17validate/validate.proto\"z\n" +
	"\x15CreateResourceRequest\x12=\n" +
	"\bresource\x18\x01 \x01(\v2\x17.crossplane.ResourceDefB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bresource\x12\"\n" +
	"\rwait_for_sync\x18\x02 \x01(\bR\vwaitForSync\"\x81\x01\n" +
	"\x1aCreateResourcesManyRequest\x12?\n" +
	"\tresources\x18\x01 \x03(\v2\x17.crossplane.ResourceDefB\b\xfaB\x05\x92\x01\x02\b\x01R\tresources\x12\"\n" +
	"\rwait_for_sync\x18\x02 \x01(\bR\vwaitForSync\"e\n" +
	"\x1bCreateResourcesManyResponse\x12F\n" +
	"\tresponses\x18\x01 \x03(\v2\x1e.crossplane.ResourceWithStatusB\b\xfaB\x05\x92\x01\x02\b\x01R\tresponses\"h\n" +
	"\x15DeleteResourceRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.crossplane.RefB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x03ref\x12\"\n" +
	"\rwait_for_sync\x18\x02 \x01(\bR\vwaitForSync\"G\n" +
	"\x18GetResourceStatusRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.crossplane.RefB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x03ref\"J\n" +
	"\x16DeleteResourceResponse\x12\x16\n" +
	"\x06synced\x18\x01 \x01(\bR\x06synced\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted2\xfd\x02\n" +
	"\n" +
	"Crossplane\x12S\n" +
	"\x0eCreateResource\x12!.crossplane.CreateResourceRequest\x1a\x1e.crossplane.ResourceWithStatus\x12f\n" +
	"\x13CreateResourcesMany\x12&.crossplane.CreateResourcesManyRequest\x1a'.crossplane.CreateResourcesManyResponse\x12Y\n" +
	"\x11GetResourceStatus\x12$.crossplane.GetResourceStatusRequest\x1a\x1e.crossplane.ResourceWithStatus\x12W\n" +
	"\x0eDeleteResource\x12!.crossplane.DeleteResourceRequest\x1a\".crossplane.DeleteResourceResponseBEZCgithub.com/stroppy-io/stroppy-cloud-panel/internal/proto/crossplaneb\x06proto3"

var (
	file_crossplane_api_proto_rawDescOnce sync.Once
	file_crossplane_api_proto_rawDescData []byte
)

func file_crossplane_api_proto_rawDescGZIP() []byte {
	file_crossplane_api_proto_rawDescOnce.Do(func() {
		file_crossplane_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crossplane_api_proto_rawDesc), len(file_crossplane_api_proto_rawDesc)))
	})
	return file_crossplane_api_proto_rawDescData
}

var file_crossplane_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_crossplane_api_proto_goTypes = []any{
	(*CreateResourceRequest)(nil),       // 0: crossplane.CreateResourceRequest
	(*CreateResourcesManyRequest)(nil),  // 1: crossplane.CreateResourcesManyRequest
	(*CreateResourcesManyResponse)(nil), // 2: crossplane.CreateResourcesManyResponse
	(*DeleteResourceRequest)(nil),       // 3: crossplane.DeleteResourceRequest
	(*GetResourceStatusRequest)(nil),    // 4: crossplane.GetResourceStatusRequest
	(*DeleteResourceResponse)(nil),      // 5: crossplane.DeleteResourceResponse
	(*ResourceDef)(nil),                 // 6: crossplane.ResourceDef
	(*ResourceWithStatus)(nil),          // 7: crossplane.ResourceWithStatus
	(*Ref)(nil),                         // 8: crossplane.Ref
}
var file_crossplane_api_proto_depIdxs = []int32{
	6, // 0: crossplane.CreateResourceRequest.resource:type_name -> crossplane.ResourceDef
	6, // 1: crossplane.CreateResourcesManyRequest.resources:type_name -> crossplane.ResourceDef
	7, // 2: crossplane.CreateResourcesManyResponse.responses:type_name -> crossplane.ResourceWithStatus
	8, // 3: crossplane.DeleteResourceRequest.ref:type_name -> crossplane.Ref
	8, // 4: crossplane.GetResourceStatusRequest.ref:type_name -> crossplane.Ref
	0, // 5: crossplane.Crossplane.CreateResource:input_type -> crossplane.CreateResourceRequest
	1, // 6: crossplane.Crossplane.CreateResourcesMany:input_type -> crossplane.CreateResourcesManyRequest
	4, // 7: crossplane.Crossplane.GetResourceStatus:input_type -> crossplane.GetResourceStatusRequest
	3, // 8: crossplane.Crossplane.DeleteResource:input_type -> crossplane.DeleteResourceRequest
	7, // 9: crossplane.Crossplane.CreateResource:output_type -> crossplane.ResourceWithStatus
	2, // 10: crossplane.Crossplane.CreateResourcesMany:output_type -> crossplane.CreateResourcesManyResponse
	7, // 11: crossplane.Crossplane.GetResourceStatus:output_type -> crossplane.ResourceWithStatus
	5, // 12: crossplane.Crossplane.DeleteResource:output_type -> crossplane.DeleteResourceResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_crossplane_api_proto_init() }
func file_crossplane_api_proto_init() {
	if File_crossplane_api_proto != nil {
		return
	}
	file_crossplane_crossplane_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crossplane_api_proto_rawDesc), len(file_crossplane_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crossplane_api_proto_goTypes,
		DependencyIndexes: file_crossplane_api_proto_depIdxs,
		MessageInfos:      file_crossplane_api_proto_msgTypes,
	}.Build()
	File_crossplane_api_proto = out.File
	file_crossplane_api_proto_goTypes = nil
	file_crossplane_api_proto_depIdxs = nil
}
