// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: crossplane/resource.proto

package crossplane

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/yaroher/protoc-gen-pgx-orm/protopgx"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource_Status int32

const (
	Resource_STATUS_UNSPECIFIED Resource_Status = 0
	Resource_STATUS_CREATING    Resource_Status = 1
	Resource_STATUS_READY       Resource_Status = 2
	Resource_STATUS_DESTROYING  Resource_Status = 3
	Resource_STATUS_DESTROYED   Resource_Status = 4
	Resource_STATUS_DEGRADED    Resource_Status = 5
)

// Enum value maps for Resource_Status.
var (
	Resource_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_CREATING",
		2: "STATUS_READY",
		3: "STATUS_DESTROYING",
		4: "STATUS_DESTROYED",
		5: "STATUS_DEGRADED",
	}
	Resource_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_CREATING":    1,
		"STATUS_READY":       2,
		"STATUS_DESTROYING":  3,
		"STATUS_DESTROYED":   4,
		"STATUS_DEGRADED":    5,
	}
)

func (x Resource_Status) Enum() *Resource_Status {
	p := new(Resource_Status)
	*p = x
	return p
}

func (x Resource_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resource_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_crossplane_resource_proto_enumTypes[0].Descriptor()
}

func (Resource_Status) Type() protoreflect.EnumType {
	return &file_crossplane_resource_proto_enumTypes[0]
}

func (x Resource_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resource_Status.Descriptor instead.
func (Resource_Status) EnumDescriptor() ([]byte, []int) {
	return file_crossplane_resource_proto_rawDescGZIP(), []int{0, 0}
}

type Resource struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Ref          *ExtRef                `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	ResourceYaml string                 `protobuf:"bytes,3,opt,name=resource_yaml,json=resourceYaml,proto3" json:"resource_yaml,omitempty"`
	Status       Resource_Status        `protobuf:"varint,4,opt,name=status,proto3,enum=crossplane.Resource_Status" json:"status,omitempty"`
	Synced       bool                   `protobuf:"varint,5,opt,name=synced,proto3" json:"synced,omitempty"`                          // crossplane default statuses
	Ready        bool                   `protobuf:"varint,6,opt,name=ready,proto3" json:"ready,omitempty"`                            // crossplane default statuses
	ExternalId   string                 `protobuf:"bytes,7,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // crossplane default statuses
	// Types that are valid to be assigned to ResourceDef:
	//
	//	*Resource_YandexCloudResourceDef
	ResourceDef   isResource_ResourceDef `protobuf_oneof:"resource_def"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_crossplane_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_crossplane_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetRef() *ExtRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Resource) GetResourceYaml() string {
	if x != nil {
		return x.ResourceYaml
	}
	return ""
}

func (x *Resource) GetStatus() Resource_Status {
	if x != nil {
		return x.Status
	}
	return Resource_STATUS_UNSPECIFIED
}

func (x *Resource) GetSynced() bool {
	if x != nil {
		return x.Synced
	}
	return false
}

func (x *Resource) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Resource) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Resource) GetResourceDef() isResource_ResourceDef {
	if x != nil {
		return x.ResourceDef
	}
	return nil
}

func (x *Resource) GetYandexCloudResourceDef() *YandexCloud_ResourceDef {
	if x != nil {
		if x, ok := x.ResourceDef.(*Resource_YandexCloudResourceDef); ok {
			return x.YandexCloudResourceDef
		}
	}
	return nil
}

type isResource_ResourceDef interface {
	isResource_ResourceDef()
}

type Resource_YandexCloudResourceDef struct {
	YandexCloudResourceDef *YandexCloud_ResourceDef `protobuf:"bytes,100,opt,name=yandex_cloud_resource_def,json=yandexCloudResourceDef,proto3,oneof"`
}

func (*Resource_YandexCloudResourceDef) isResource_ResourceDef() {}

type ResourceDag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nodes         []*ResourceDag_Node    `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*ResourceDag_Edge    `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDag) Reset() {
	*x = ResourceDag{}
	mi := &file_crossplane_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDag) ProtoMessage() {}

func (x *ResourceDag) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDag.ProtoReflect.Descriptor instead.
func (*ResourceDag) Descriptor() ([]byte, []int) {
	return file_crossplane_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceDag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceDag) GetNodes() []*ResourceDag_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ResourceDag) GetEdges() []*ResourceDag_Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type ResourceDag_Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDag_Node) Reset() {
	*x = ResourceDag_Node{}
	mi := &file_crossplane_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDag_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDag_Node) ProtoMessage() {}

func (x *ResourceDag_Node) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDag_Node.ProtoReflect.Descriptor instead.
func (*ResourceDag_Node) Descriptor() ([]byte, []int) {
	return file_crossplane_resource_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResourceDag_Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceDag_Node) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ResourceDag_Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDag_Edge) Reset() {
	*x = ResourceDag_Edge{}
	mi := &file_crossplane_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDag_Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDag_Edge) ProtoMessage() {}

func (x *ResourceDag_Edge) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDag_Edge.ProtoReflect.Descriptor instead.
func (*ResourceDag_Edge) Descriptor() ([]byte, []int) {
	return file_crossplane_resource_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ResourceDag_Edge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ResourceDag_Edge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

var File_crossplane_resource_proto protoreflect.FileDescriptor

const file_crossplane_resource_proto_rawDesc = "" +
	"\n" +
	"\x19crossplane/resource.proto\x12\n" +
	"crossplane\x1a\x16crossplane/types.proto\x1a\x17crossplane/yandex.proto\x1a\x12protopgx/pgx.proto\x1a\x17validate/validate.proto\"\x83\x04\n" +
	"\bResource\x123\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.crossplane.ExtRefB\r\xca>\x02H\x01\xfaB\x05\x8a\x01\x02\x10\x01R\x03ref\x12,\n" +
	"\rresource_yaml\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\fresourceYaml\x12=\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.crossplane.Resource.StatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\x12\x16\n" +
	"\x06synced\x18\x05 \x01(\bR\x06synced\x12\x14\n" +
	"\x05ready\x18\x06 \x01(\bR\x05ready\x12\x1f\n" +
	"\vexternal_id\x18\a \x01(\tR\n" +
	"externalId\x12j\n" +
	"\x19yandex_cloud_resource_def\x18d \x01(\v2#.crossplane.YandexCloud.ResourceDefB\b\xfaB\x05\x8a\x01\x02\x10\x01H\x00R\x16yandexCloudResourceDef\"\x89\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_CREATING\x10\x01\x12\x10\n" +
	"\fSTATUS_READY\x10\x02\x12\x15\n" +
	"\x11STATUS_DESTROYING\x10\x03\x12\x14\n" +
	"\x10STATUS_DESTROYED\x10\x04\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x05B\x0e\n" +
	"\fresource_def\"\xbd\x02\n" +
	"\vResourceDag\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12<\n" +
	"\x05nodes\x18\x02 \x03(\v2\x1c.crossplane.ResourceDag.NodeB\b\xfaB\x05\x92\x01\x02\b\x01R\x05nodes\x12<\n" +
	"\x05edges\x18\x03 \x03(\v2\x1c.crossplane.ResourceDag.EdgeB\b\xfaB\x05\x92\x01\x02\b\x01R\x05edges\x1a[\n" +
	"\x04Node\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12:\n" +
	"\bresource\x18\x02 \x01(\v2\x14.crossplane.ResourceB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bresource\x1a<\n" +
	"\x04Edge\x12\x1b\n" +
	"\x04from\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04from\x12\x17\n" +
	"\x02to\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02toBEZCgithub.com/stroppy-io/stroppy-cloud-panel/internal/proto/crossplaneb\x06proto3"

var (
	file_crossplane_resource_proto_rawDescOnce sync.Once
	file_crossplane_resource_proto_rawDescData []byte
)

func file_crossplane_resource_proto_rawDescGZIP() []byte {
	file_crossplane_resource_proto_rawDescOnce.Do(func() {
		file_crossplane_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crossplane_resource_proto_rawDesc), len(file_crossplane_resource_proto_rawDesc)))
	})
	return file_crossplane_resource_proto_rawDescData
}

var file_crossplane_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_crossplane_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_crossplane_resource_proto_goTypes = []any{
	(Resource_Status)(0),            // 0: crossplane.Resource.Status
	(*Resource)(nil),                // 1: crossplane.Resource
	(*ResourceDag)(nil),             // 2: crossplane.ResourceDag
	(*ResourceDag_Node)(nil),        // 3: crossplane.ResourceDag.Node
	(*ResourceDag_Edge)(nil),        // 4: crossplane.ResourceDag.Edge
	(*ExtRef)(nil),                  // 5: crossplane.ExtRef
	(*YandexCloud_ResourceDef)(nil), // 6: crossplane.YandexCloud.ResourceDef
}
var file_crossplane_resource_proto_depIdxs = []int32{
	5, // 0: crossplane.Resource.ref:type_name -> crossplane.ExtRef
	0, // 1: crossplane.Resource.status:type_name -> crossplane.Resource.Status
	6, // 2: crossplane.Resource.yandex_cloud_resource_def:type_name -> crossplane.YandexCloud.ResourceDef
	3, // 3: crossplane.ResourceDag.nodes:type_name -> crossplane.ResourceDag.Node
	4, // 4: crossplane.ResourceDag.edges:type_name -> crossplane.ResourceDag.Edge
	1, // 5: crossplane.ResourceDag.Node.resource:type_name -> crossplane.Resource
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_crossplane_resource_proto_init() }
func file_crossplane_resource_proto_init() {
	if File_crossplane_resource_proto != nil {
		return
	}
	file_crossplane_types_proto_init()
	file_crossplane_yandex_proto_init()
	file_crossplane_resource_proto_msgTypes[0].OneofWrappers = []any{
		(*Resource_YandexCloudResourceDef)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crossplane_resource_proto_rawDesc), len(file_crossplane_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crossplane_resource_proto_goTypes,
		DependencyIndexes: file_crossplane_resource_proto_depIdxs,
		EnumInfos:         file_crossplane_resource_proto_enumTypes,
		MessageInfos:      file_crossplane_resource_proto_msgTypes,
	}.Build()
	File_crossplane_resource_proto = out.File
	file_crossplane_resource_proto_goTypes = nil
	file_crossplane_resource_proto_depIdxs = nil
}
