// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: crossplane/types.proto

package crossplane

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupportedCloud int32

const (
	SupportedCloud_SUPPORTED_CLOUD_UNSPECIFIED SupportedCloud = 0
	SupportedCloud_SUPPORTED_CLOUD_YANDEX      SupportedCloud = 1
)

// Enum value maps for SupportedCloud.
var (
	SupportedCloud_name = map[int32]string{
		0: "SUPPORTED_CLOUD_UNSPECIFIED",
		1: "SUPPORTED_CLOUD_YANDEX",
	}
	SupportedCloud_value = map[string]int32{
		"SUPPORTED_CLOUD_UNSPECIFIED": 0,
		"SUPPORTED_CLOUD_YANDEX":      1,
	}
)

func (x SupportedCloud) Enum() *SupportedCloud {
	p := new(SupportedCloud)
	*p = x
	return p
}

func (x SupportedCloud) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SupportedCloud) Descriptor() protoreflect.EnumDescriptor {
	return file_crossplane_types_proto_enumTypes[0].Descriptor()
}

func (SupportedCloud) Type() protoreflect.EnumType {
	return &file_crossplane_types_proto_enumTypes[0]
}

func (x SupportedCloud) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SupportedCloud.Descriptor instead.
func (SupportedCloud) EnumDescriptor() ([]byte, []int) {
	return file_crossplane_types_proto_rawDescGZIP(), []int{0}
}

type OnlyNameRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlyNameRef) Reset() {
	*x = OnlyNameRef{}
	mi := &file_crossplane_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlyNameRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlyNameRef) ProtoMessage() {}

func (x *OnlyNameRef) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlyNameRef.ProtoReflect.Descriptor instead.
func (*OnlyNameRef) Descriptor() ([]byte, []int) {
	return file_crossplane_types_proto_rawDescGZIP(), []int{0}
}

func (x *OnlyNameRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_crossplane_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_crossplane_types_proto_rawDescGZIP(), []int{1}
}

func (x *Ref) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Ref) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExtRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtRef) Reset() {
	*x = ExtRef{}
	mi := &file_crossplane_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtRef) ProtoMessage() {}

func (x *ExtRef) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtRef.ProtoReflect.Descriptor instead.
func (*ExtRef) Descriptor() ([]byte, []int) {
	return file_crossplane_types_proto_rawDescGZIP(), []int{2}
}

func (x *ExtRef) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ExtRef) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ExtRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_crossplane_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_crossplane_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_crossplane_types_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_crossplane_types_proto protoreflect.FileDescriptor

const file_crossplane_types_proto_rawDesc = "" +
	"\n" +
	"\x16crossplane/types.proto\x12\n" +
	"crossplane\x1a\x17validate/validate.proto\"*\n" +
	"\vOnlyNameRef\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"I\n" +
	"\x03Ref\x12%\n" +
	"\tnamespace\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tnamespace\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\"|\n" +
	"\x06ExtRef\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x0f.crossplane.RefB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x03ref\x12(\n" +
	"\vapi_version\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"apiVersion\x12\x1b\n" +
	"\x04kind\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04kind\"\xd7\x01\n" +
	"\bMetadata\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12%\n" +
	"\tnamespace\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tnamespace\x12G\n" +
	"\vannotations\x18\x03 \x03(\v2%.crossplane.Metadata.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*M\n" +
	"\x0eSupportedCloud\x12\x1f\n" +
	"\x1bSUPPORTED_CLOUD_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SUPPORTED_CLOUD_YANDEX\x10\x01BEZCgithub.com/stroppy-io/stroppy-cloud-panel/internal/proto/crossplaneb\x06proto3"

var (
	file_crossplane_types_proto_rawDescOnce sync.Once
	file_crossplane_types_proto_rawDescData []byte
)

func file_crossplane_types_proto_rawDescGZIP() []byte {
	file_crossplane_types_proto_rawDescOnce.Do(func() {
		file_crossplane_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crossplane_types_proto_rawDesc), len(file_crossplane_types_proto_rawDesc)))
	})
	return file_crossplane_types_proto_rawDescData
}

var file_crossplane_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_crossplane_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_crossplane_types_proto_goTypes = []any{
	(SupportedCloud)(0), // 0: crossplane.SupportedCloud
	(*OnlyNameRef)(nil), // 1: crossplane.OnlyNameRef
	(*Ref)(nil),         // 2: crossplane.Ref
	(*ExtRef)(nil),      // 3: crossplane.ExtRef
	(*Metadata)(nil),    // 4: crossplane.Metadata
	nil,                 // 5: crossplane.Metadata.AnnotationsEntry
}
var file_crossplane_types_proto_depIdxs = []int32{
	2, // 0: crossplane.ExtRef.ref:type_name -> crossplane.Ref
	5, // 1: crossplane.Metadata.annotations:type_name -> crossplane.Metadata.AnnotationsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_crossplane_types_proto_init() }
func file_crossplane_types_proto_init() {
	if File_crossplane_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crossplane_types_proto_rawDesc), len(file_crossplane_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crossplane_types_proto_goTypes,
		DependencyIndexes: file_crossplane_types_proto_depIdxs,
		EnumInfos:         file_crossplane_types_proto_enumTypes,
		MessageInfos:      file_crossplane_types_proto_msgTypes,
	}.Build()
	File_crossplane_types_proto = out.File
	file_crossplane_types_proto_goTypes = nil
	file_crossplane_types_proto_depIdxs = nil
}
